/**
 * Workspace-конфиги: capability → вкладки/фичи для поэтапного развития без новых маршрутов.
 * SoT для PillarCapabilityWorkspaceChrome.
 */
import type { CoreChainRoleId, CoreHubPillarId } from '@/lib/platform-core-hub-matrix.types';

export type PillarCapabilityFeatureStatus = 'live' | 'stub' | 'planned';

export type PillarCapabilityFeature = {
  id: string;
  labelRu: string;
  summaryRu: string;
  status: PillarCapabilityFeatureStatus;
  testId: string;
  externalRef?: string;
};

export type PillarCapabilityWorkspace = {
  id: string;
  /** Якорь в pillar-capability-registry.ts */
  capabilityId: string;
  titleRu: string;
  leadRu: string;
  pillar: CoreHubPillarId;
  role: CoreChainRoleId;
  defaultFeatureId: string;
  features: readonly PillarCapabilityFeature[];
  /** Override cross-links anchor (default: capabilityId) */
  crossLinkAnchorId?: string;
};

export const PILLAR_CAPABILITY_FEATURE_PARAM = 'pcf';

export const PILLAR_CAPABILITY_WORKSPACES: Record<string, PillarCapabilityWorkspace> = {
  'shop-order-comms': {
    id: 'shop-order-comms',
    capabilityId: 'comms-order-context',
    titleRu: 'Чат по заказу · трекинг',
    leadRu: 'NuOrder: chain status + order chat + calendar.',
    pillar: 'comms',
    role: 'shop',
    defaultFeatureId: 'tracking',
    crossLinkAnchorId: 'comms-order-context',
    features: [
      {
        id: 'tracking',
        labelRu: 'Трекинг',
        summaryRu: 'B2B chain · reserve · shipment.',
        status: 'live',
        testId: 'shop-order-comms-feature-tracking',
      },
      {
        id: 'chat',
        labelRu: 'Чат',
        summaryRu: 'Messages + collaborative comms.',
        status: 'live',
        testId: 'shop-order-comms-feature-chat',
        externalRef: 'NuOrder',
      },
      {
        id: 'calendar',
        labelRu: 'Календарь',
        summaryRu: 'Delivery · milestones · working order.',
        status: 'live',
        testId: 'shop-order-comms-feature-calendar',
      },
    ],
  },
  'shop-replenishment': {
    id: 'shop-replenishment',
    capabilityId: 'co-replenishment-workspace',
    titleRu: 'Replenishment workspace',
    leadRu: 'Onfinity-style: алерты → ATP-таблица → правила → reorder в матрицу.',
    pillar: 'collection_order',
    role: 'shop',
    defaultFeatureId: 'alerts',
    crossLinkAnchorId: 'co-replenishment-workspace',
    features: [
      {
        id: 'alerts',
        labelRu: 'Алерты',
        summaryRu: 'AI/POS-signals и черновики пополнения.',
        status: 'live',
        testId: 'shop-replenishment-feature-alerts',
        externalRef: 'Onfinity Replenish',
      },
      {
        id: 'stock-atp',
        labelRu: 'Stock · ATP',
        summaryRu: 'Таблица: on hand, reserved, ATP, unconfirmed + filter slices.',
        status: 'live',
        testId: 'shop-replenishment-feature-stock-atp',
        externalRef: 'Onfinity Inventory',
      },
      {
        id: 'rules',
        labelRu: 'Правила',
        summaryRu: 'Presets: sold/ATP/days, basic vs fashion.',
        status: 'live',
        testId: 'shop-replenishment-feature-rules',
        externalRef: 'Onfinity Parameters',
      },
    ],
  },
  'shop-showroom-buy': {
    id: 'shop-showroom-buy',
    capabilityId: 'sc-showroom-buy',
    titleRu: 'Showroom · buying tool',
    leadRu: 'JOOR/NuOrder: витрина → linesheet → buy path без новых маршрутов.',
    pillar: 'sample_collection',
    role: 'shop',
    defaultFeatureId: 'showroom',
    crossLinkAnchorId: 'sc-showroom-buy',
    features: [
      {
        id: 'showroom',
        labelRu: 'Showroom',
        summaryRu: 'Published assortment + quick add.',
        status: 'live',
        testId: 'shop-showroom-feature-showroom',
        externalRef: 'JOOR',
      },
      {
        id: 'linesheet',
        labelRu: 'Linesheet',
        summaryRu: 'Matrix · registry · collaborative.',
        status: 'live',
        testId: 'shop-showroom-feature-linesheet',
        externalRef: 'NuOrder',
      },
      {
        id: 'buy',
        labelRu: 'Buy',
        summaryRu: 'Checkout · working order · replenishment.',
        status: 'live',
        testId: 'shop-showroom-feature-buy',
        externalRef: 'Onfinity',
      },
      {
        id: '3d-stream',
        labelRu: '3D stream',
        summaryRu: 'Virtual showroom embed · session journal · article chat.',
        status: 'live',
        testId: 'shop-showroom-feature-3d-stream',
        externalRef: 'Matterport',
      },
    ],
  },
  'shop-wholesale-matrix': {
    id: 'shop-wholesale-matrix',
    capabilityId: 'co-wholesale-matrix',
    titleRu: 'Оптовая матрица',
    leadRu: 'JOOR/NuOrder grid + inspector артикула (read-only production attrs).',
    pillar: 'collection_order',
    role: 'shop',
    defaultFeatureId: 'matrix',
    crossLinkAnchorId: 'co-wholesale-matrix',
    features: [
      {
        id: 'matrix',
        labelRu: 'Матрица',
        summaryRu: 'Color×size, MOQ, delivery windows.',
        status: 'live',
        testId: 'shop-matrix-feature-grid',
      },
      {
        id: 'inspector',
        labelRu: 'Артикул',
        summaryRu: 'Supplier model, fabric, MOQ — read-only в контексте коллекции.',
        status: 'live',
        testId: 'shop-matrix-feature-inspector',
        externalRef: 'Onfinity Product Management',
      },
      {
        id: 'prepack',
        labelRu: 'Pre-pack',
        summaryRu: 'Size curve / pre-pack qty.',
        status: 'live',
        testId: 'shop-matrix-feature-prepack',
        externalRef: 'Aptos',
      },
    ],
  },
  'brand-attribute-schema': {
    id: 'brand-attribute-schema',
    capabilityId: 'dev-attribute-schema',
    titleRu: 'Схемы атрибутов',
    leadRu: 'Onfinity Attribute Set + Centric — health сейчас, schemas далее.',
    pillar: 'development',
    role: 'brand',
    defaultFeatureId: 'health',
    features: [
      {
        id: 'health',
        labelRu: 'Health',
        summaryRu: 'Пробелы SKU: media, season, composition…',
        status: 'live',
        testId: 'brand-attribute-feature-health',
      },
      {
        id: 'schemas',
        labelRu: 'Schemas',
        summaryRu: 'Color/size schema по category handbook.',
        status: 'live',
        testId: 'brand-attribute-feature-schemas',
        externalRef: 'Onfinity',
      },
      {
        id: 'size-chart',
        labelRu: 'Size chart',
        summaryRu: 'Grade rules → size schema SoT.',
        status: 'live',
        testId: 'brand-attribute-feature-size-chart',
        externalRef: 'Yunique PLM',
      },
    ],
  },
  'brand-release-gate': {
    id: 'brand-release-gate',
    capabilityId: 'sc-release-gate',
    titleRu: 'Release gate',
    leadRu: 'Centric checklist перед publish в B2B витрину.',
    pillar: 'sample_collection',
    role: 'brand',
    defaultFeatureId: 'checklist',
    crossLinkAnchorId: 'sc-release-gate',
    features: [
      {
        id: 'checklist',
        labelRu: 'Checklist',
        summaryRu: 'Launch readiness по SKU.',
        status: 'live',
        testId: 'brand-release-feature-checklist',
      },
      {
        id: 'syndication',
        labelRu: 'Syndication',
        summaryRu: 'Outbound linesheet feed после release.',
        status: 'live',
        testId: 'brand-release-feature-syndication',
        externalRef: 'Colect',
      },
      {
        id: 'showroom-publish',
        labelRu: 'Showroom',
        summaryRu: 'Bulk publish → brand preview · shop buy.',
        status: 'live',
        testId: 'brand-release-feature-showroom-publish',
        externalRef: 'JOOR',
      },
      {
        id: 'techpack-gate',
        labelRu: 'Factory pack',
        summaryRu: '6 листов green + qty bridge перед release.',
        status: 'live',
        testId: 'brand-release-feature-techpack-gate',
      },
    ],
  },
  'brand-production-ops': {
    id: 'brand-production-ops',
    capabilityId: 'op-cut-ticket-wip',
    titleRu: 'Операции цеха',
    leadRu: 'Apparel Magic/WFX: cut ticket, WIP routing, QC gate.',
    pillar: 'order_production',
    role: 'brand',
    defaultFeatureId: 'operations',
    features: [
      {
        id: 'operations',
        labelRu: 'Операции',
        summaryRu: 'Реестр производственных операций.',
        status: 'live',
        testId: 'brand-production-feature-operations',
      },
      {
        id: 'handoff',
        labelRu: 'Handoff',
        summaryRu: 'B2B PO → factory queue → shop tracking.',
        status: 'live',
        testId: 'brand-production-feature-handoff',
        externalRef: 'Apparel Magic',
      },
      {
        id: 'cut-ticket',
        labelRu: 'Cut ticket',
        summaryRu: 'Work packet из confirmed B2B lines.',
        status: 'live',
        testId: 'brand-production-feature-cut-ticket',
        externalRef: 'Apparel Magic',
      },
      {
        id: 'qc-gate',
        labelRu: 'QC gate',
        summaryRu: 'AQL checklist перед ship.',
        status: 'live',
        testId: 'brand-production-feature-qc-gate',
        externalRef: 'Inspectorio',
      },
    ],
  },
  'brand-sample-lifecycle': {
    id: 'brand-sample-lifecycle',
    capabilityId: 'dev-sample-lifecycle',
    titleRu: 'Sample lifecycle',
    leadRu: 'Centric/Lectra: proto → SMS → gold → approved → handoff.',
    pillar: 'development',
    role: 'brand',
    defaultFeatureId: 'hub',
    crossLinkAnchorId: 'dev-sample-lifecycle',
    features: [
      {
        id: 'hub',
        labelRu: 'Артикулы',
        summaryRu: 'Коллекция · состав · publish strip.',
        status: 'live',
        testId: 'brand-sample-feature-hub',
      },
      {
        id: 'rounds',
        labelRu: 'Раунды образца',
        summaryRu: 'Sample 1→2→approved по SKU.',
        status: 'live',
        testId: 'brand-sample-feature-rounds',
        externalRef: 'Centric PLM',
      },
    ],
  },
  'brand-showroom-buy': {
    id: 'brand-showroom-buy',
    capabilityId: 'sc-showroom-buy',
    titleRu: 'Showroom · publish & buy',
    leadRu: 'Centric release → shop mirror: preview · publish · shop buy.',
    pillar: 'sample_collection',
    role: 'brand',
    defaultFeatureId: 'preview',
    crossLinkAnchorId: 'sc-showroom-buy',
    features: [
      {
        id: 'preview',
        labelRu: 'Preview',
        summaryRu: 'Brand-side published assortment.',
        status: 'live',
        testId: 'brand-showroom-feature-preview',
        externalRef: 'Centric',
      },
      {
        id: 'publish',
        labelRu: 'Publish',
        summaryRu: 'Launch readiness · syndication.',
        status: 'live',
        testId: 'brand-showroom-feature-publish',
        externalRef: 'Colect',
      },
      {
        id: 'shop-buy',
        labelRu: 'Shop buy',
        summaryRu: 'Deep-link в shop showroom / buy path.',
        status: 'live',
        testId: 'brand-showroom-feature-shop-buy',
        externalRef: 'JOOR',
      },
    ],
  },
  'brand-material-passport': {
    id: 'brand-material-passport',
    capabilityId: 'dev-material-passport',
    titleRu: 'Material passport',
    leadRu: 'Material Exchange: rollup → certs → release gate.',
    pillar: 'development',
    role: 'brand',
    defaultFeatureId: 'rollup',
    crossLinkAnchorId: 'dev-material-passport',
    features: [
      {
        id: 'rollup',
        labelRu: 'Rollup',
        summaryRu: 'Composition + care CSV.',
        status: 'live',
        testId: 'brand-material-feature-rollup',
      },
      {
        id: 'certs',
        labelRu: 'Certs',
        summaryRu: 'Composition · care · eco gate.',
        status: 'live',
        testId: 'brand-material-feature-certs',
        externalRef: 'Material Exchange',
      },
      {
        id: 'release',
        labelRu: 'Release',
        summaryRu: 'Связь со sc-release-gate.',
        status: 'live',
        testId: 'brand-material-feature-release',
      },
    ],
  },
  'brand-order-comms': {
    id: 'brand-order-comms',
    capabilityId: 'comms-order-context',
    titleRu: 'Чат по заказу · карточка',
    leadRu: 'NuOrder: order detail + chat + production handoff bridges.',
    pillar: 'comms',
    role: 'brand',
    defaultFeatureId: 'detail',
    crossLinkAnchorId: 'comms-order-context',
    features: [
      {
        id: 'detail',
        labelRu: 'Detail',
        summaryRu: 'Facts · chain status · buyer context.',
        status: 'live',
        testId: 'brand-order-comms-feature-detail',
      },
      {
        id: 'chat',
        labelRu: 'Чат',
        summaryRu: 'Messages + entity threads + calendar.',
        status: 'live',
        testId: 'brand-order-comms-feature-chat',
        externalRef: 'NuOrder',
      },
      {
        id: 'handoff',
        labelRu: 'Handoff',
        summaryRu: 'Brand ops → factory queue → shop tracking.',
        status: 'live',
        testId: 'brand-order-comms-feature-handoff',
      },
    ],
  },
  'brand-rfq-supplier': {
    id: 'brand-rfq-supplier',
    capabilityId: 'dev-rfq-supplier',
    titleRu: 'Centric RFQ',
    leadRu: 'Style/BOM upstream → RFQ registry → comms.',
    pillar: 'development',
    role: 'brand',
    defaultFeatureId: 'upstream',
    crossLinkAnchorId: 'dev-rfq-supplier',
    features: [
      {
        id: 'upstream',
        labelRu: 'Upstream',
        summaryRu: 'Style · BOM · media import.',
        status: 'live',
        testId: 'brand-rfq-feature-upstream',
      },
      {
        id: 'rfq',
        labelRu: 'RFQ',
        summaryRu: 'Import + registry quote/award.',
        status: 'live',
        testId: 'brand-rfq-feature-rfq',
        externalRef: 'Centric PLM',
      },
      {
        id: 'comms',
        labelRu: 'Comms',
        summaryRu: 'Entity threads · supplier chat.',
        status: 'live',
        testId: 'brand-rfq-feature-comms',
      },
    ],
  },
  'brand-comms-workspace': {
    id: 'brand-comms-workspace',
    capabilityId: 'comms-entity-threads',
    titleRu: 'Сообщения · threads',
    leadRu: 'Inbox + structured BOM/sample/QC/RFQ threads.',
    pillar: 'comms',
    role: 'brand',
    defaultFeatureId: 'inbox',
    crossLinkAnchorId: 'comms-entity-threads',
    features: [
      {
        id: 'inbox',
        labelRu: 'Inbox',
        summaryRu: 'Contextual PG threads.',
        status: 'live',
        testId: 'brand-comms-feature-inbox',
      },
      {
        id: 'entities',
        labelRu: 'Entities',
        summaryRu: 'BOM · sample · QC · RFQ.',
        status: 'live',
        testId: 'brand-comms-feature-entities',
        externalRef: 'Centric PLM',
      },
    ],
  },
  'shop-collaborative-order': {
    id: 'shop-collaborative-order',
    capabilityId: 'co-collaborative-order',
    titleRu: 'Collaborative order',
    leadRu: 'NuOrder: co-edit matrix + approval chain + order comms.',
    pillar: 'collection_order',
    role: 'shop',
    defaultFeatureId: 'session',
    crossLinkAnchorId: 'co-collaborative-order',
    features: [
      {
        id: 'session',
        labelRu: 'Session',
        summaryRu: 'Участники co-edit на одной матрице.',
        status: 'live',
        testId: 'shop-collaborative-feature-session',
        externalRef: 'NuOrder',
      },
      {
        id: 'approvals',
        labelRu: 'Approvals',
        summaryRu: 'Matrix lock → margin → submit.',
        status: 'live',
        testId: 'shop-collaborative-feature-approvals',
      },
      {
        id: 'comms',
        labelRu: 'Comms',
        summaryRu: 'Order chat + calendar в контексте B2B.',
        status: 'live',
        testId: 'shop-collaborative-feature-comms',
      },
    ],
  },
  'brand-wssi-plan': {
    id: 'brand-wssi-plan',
    capabilityId: 'sc-wssi-plan',
    titleRu: 'Buy plan · WSSI',
    leadRu: 'Fast React: OTB mix → capacity → shop buy.',
    pillar: 'sample_collection',
    role: 'brand',
    defaultFeatureId: 'otb',
    crossLinkAnchorId: 'sc-wssi-plan',
    features: [
      {
        id: 'otb',
        labelRu: 'OTB',
        summaryRu: 'Category targets vs current mix.',
        status: 'live',
        testId: 'brand-wssi-feature-otb',
        externalRef: 'Fast React',
      },
      {
        id: 'mix',
        labelRu: 'Mix',
        summaryRu: 'Snapshot + CSV export route.',
        status: 'live',
        testId: 'brand-wssi-feature-mix',
      },
      {
        id: 'capacity',
        labelRu: 'Capacity',
        summaryRu: 'Buy plan vs factory slots · MRP.',
        status: 'live',
        testId: 'brand-wssi-feature-capacity',
      },
    ],
  },
  'shop-working-order': {
    id: 'shop-working-order',
    capabilityId: 'co-working-order',
    titleRu: 'Working order',
    leadRu: 'NuOrder: versions · bulk entry · handoff comms.',
    pillar: 'collection_order',
    role: 'shop',
    defaultFeatureId: 'versions',
    crossLinkAnchorId: 'co-working-order',
    features: [
      {
        id: 'versions',
        labelRu: 'Versions',
        summaryRu: 'Spine versions + export badge.',
        status: 'live',
        testId: 'shop-working-order-feature-versions',
        externalRef: 'NuOrder',
      },
      {
        id: 'bulk',
        labelRu: 'Bulk',
        summaryRu: 'Matrix · replenishment · pre-pack.',
        status: 'live',
        testId: 'shop-working-order-feature-bulk',
      },
      {
        id: 'handoff',
        labelRu: 'Handoff',
        summaryRu: 'Order card · approvals · comms.',
        status: 'live',
        testId: 'shop-working-order-feature-handoff',
      },
    ],
  },
  'brand-pricelist': {
    id: 'brand-pricelist',
    capabilityId: 'co-pricelist-version',
    titleRu: 'Pricelist · tier',
    leadRu: 'Onfinity: versions → customer tiers → shop matrix sync.',
    pillar: 'collection_order',
    role: 'brand',
    defaultFeatureId: 'versions',
    crossLinkAnchorId: 'co-pricelist-version',
    features: [
      {
        id: 'versions',
        labelRu: 'Versions',
        summaryRu: 'Channel · period · multiplier lists.',
        status: 'live',
        testId: 'brand-pricelist-feature-versions',
        externalRef: 'Onfinity',
      },
      {
        id: 'tiers',
        labelRu: 'Tiers',
        summaryRu: 'Customer groups → price lists.',
        status: 'live',
        testId: 'brand-pricelist-feature-tiers',
      },
      {
        id: 'shop-sync',
        labelRu: 'Shop sync',
        summaryRu: 'Matrix · landed margin · showroom.',
        status: 'live',
        testId: 'brand-pricelist-feature-shop-sync',
        externalRef: 'JOOR',
      },
    ],
  },
  'brand-pack-rules': {
    id: 'brand-pack-rules',
    capabilityId: 'co-prepack-curve',
    titleRu: 'Pack rules · curve',
    leadRu: 'Brand MOQ/case pack → size curve → shop pre-pack.',
    pillar: 'collection_order',
    role: 'brand',
    defaultFeatureId: 'rules',
    crossLinkAnchorId: 'co-prepack-curve',
    features: [
      {
        id: 'rules',
        labelRu: 'Rules',
        summaryRu: 'MOQ · case pack · lead time table.',
        status: 'live',
        testId: 'brand-pack-rules-feature-rules',
      },
      {
        id: 'curve',
        labelRu: 'Curve',
        summaryRu: 'Size weights SoT for pre-pack.',
        status: 'live',
        testId: 'brand-pack-rules-feature-curve',
        externalRef: 'Aptos',
      },
      {
        id: 'shop-prepack',
        labelRu: 'Shop pre-pack',
        summaryRu: 'Deep link to matrix prepack tab.',
        status: 'live',
        testId: 'brand-pack-rules-feature-shop-prepack',
        externalRef: 'Oracle Retail',
      },
    ],
  },
  'brand-agent-rep': {
    id: 'brand-agent-rep',
    capabilityId: 'co-agent-rep',
    titleRu: 'Rep oversight',
    leadRu: 'Brand ledger · reps · shop portal mirror.',
    pillar: 'collection_order',
    role: 'brand',
    defaultFeatureId: 'ledger',
    crossLinkAnchorId: 'co-agent-rep',
    features: [
      {
        id: 'ledger',
        labelRu: 'Ledger',
        summaryRu: 'Commission records approve/paid.',
        status: 'live',
        testId: 'brand-agent-rep-feature-ledger',
        externalRef: 'Zedonk',
      },
      {
        id: 'reps',
        labelRu: 'Reps',
        summaryRu: 'Active sub-agents roster.',
        status: 'live',
        testId: 'brand-agent-rep-feature-reps',
      },
      {
        id: 'shop-portal',
        labelRu: 'Shop portal',
        summaryRu: 'Links to shop rep workspace tabs.',
        status: 'live',
        testId: 'brand-agent-rep-feature-shop-portal',
        externalRef: 'RepSpark',
      },
    ],
  },
  'brand-supplier-bom': {
    id: 'brand-supplier-bom',
    capabilityId: 'dev-supplier-model-bom',
    titleRu: 'Supplier model · BOM',
    leadRu: 'Apparel Magic: BOM lines + procurement RFQ chain.',
    pillar: 'development',
    role: 'brand',
    defaultFeatureId: 'bom',
    crossLinkAnchorId: 'dev-supplier-model-bom',
    features: [
      {
        id: 'bom',
        labelRu: 'BOM lines',
        summaryRu: 'Snapshot lines + W2 material drill-down.',
        status: 'live',
        testId: 'brand-supplier-bom-feature-bom',
        externalRef: 'Apparel Magic',
      },
      {
        id: 'procurement',
        labelRu: 'Procurement',
        summaryRu: 'Centric RFQ · entity threads · supplier chat.',
        status: 'live',
        testId: 'brand-supplier-bom-feature-procurement',
        externalRef: 'Centric PLM',
      },
    ],
  },
  'shop-b2b-partners': {
    id: 'shop-b2b-partners',
    capabilityId: 'sc-showroom-buy',
    titleRu: 'Partners · buy-side',
    leadRu: 'Roster · discover radar · rep portal chain.',
    pillar: 'sample_collection',
    role: 'shop',
    defaultFeatureId: 'roster',
    crossLinkAnchorId: 'sc-showroom-buy',
    features: [
      {
        id: 'roster',
        labelRu: 'Roster',
        summaryRu: 'Connected brands · showroom/matrix.',
        status: 'live',
        testId: 'shop-b2b-partners-feature-roster',
        externalRef: 'JOOR',
      },
      {
        id: 'discover',
        labelRu: 'Discover',
        summaryRu: 'AI radar · invite · platform directory.',
        status: 'live',
        testId: 'shop-b2b-partners-feature-discover',
      },
      {
        id: 'rep',
        labelRu: 'Rep',
        summaryRu: 'Sales rep portal · collaborative.',
        status: 'live',
        testId: 'shop-b2b-partners-feature-rep',
        externalRef: 'RepSpark',
      },
    ],
  },
  'brand-landed-margin': {
    id: 'brand-landed-margin',
    capabilityId: 'co-landed-margin',
    titleRu: 'Landed cost · маржа',
    leadRu: 'BlueCherry: simulator → pricelist tier → shop roll-up.',
    pillar: 'collection_order',
    role: 'brand',
    defaultFeatureId: 'simulator',
    crossLinkAnchorId: 'co-landed-margin',
    features: [
      {
        id: 'simulator',
        labelRu: 'Simulator',
        summaryRu: 'Unit economics · SKU margin model.',
        status: 'live',
        testId: 'brand-landed-margin-feature-simulator',
        externalRef: 'BlueCherry',
      },
      {
        id: 'pricelist',
        labelRu: 'Pricelist',
        summaryRu: 'Brand tiers ↔ shop pricelist tab.',
        status: 'live',
        testId: 'brand-landed-margin-feature-pricelist',
        externalRef: 'Onfinity',
      },
      {
        id: 'shop-rollup',
        labelRu: 'Shop roll-up',
        summaryRu: 'Buyer landed margin · collaborative chain.',
        status: 'live',
        testId: 'brand-landed-margin-feature-shop-rollup',
      },
    ],
  },
  'shop-landed-margin': {
    id: 'shop-landed-margin',
    capabilityId: 'co-landed-margin',
    titleRu: 'Landed cost · маржа',
    leadRu: 'BlueCherry: hub → roll-up → pricelist tier.',
    pillar: 'collection_order',
    role: 'shop',
    defaultFeatureId: 'hub',
    crossLinkAnchorId: 'co-landed-margin',
    features: [
      {
        id: 'hub',
        labelRu: 'Hub',
        summaryRu: 'Калькулятор · отчёт · landed cost.',
        status: 'live',
        testId: 'shop-landed-margin-feature-hub',
        externalRef: 'BlueCherry',
      },
      {
        id: 'rollup',
        labelRu: 'Roll-up',
        summaryRu: 'Wholesale vs landed по active order.',
        status: 'live',
        testId: 'shop-landed-margin-feature-rollup',
      },
      {
        id: 'pricelist',
        labelRu: 'Pricelist',
        summaryRu: 'Tier + matrix + brand price lists.',
        status: 'live',
        testId: 'shop-landed-margin-feature-pricelist',
      },
    ],
  },
  'shop-agent-rep': {
    id: 'shop-agent-rep',
    capabilityId: 'co-agent-rep',
    titleRu: 'Agent / sales rep',
    leadRu: 'RepSpark: portal · commission · matrix entry.',
    pillar: 'collection_order',
    role: 'shop',
    defaultFeatureId: 'portal',
    crossLinkAnchorId: 'co-agent-rep',
    features: [
      {
        id: 'portal',
        labelRu: 'Portal',
        summaryRu: 'Appointments · showroom · linesheets.',
        status: 'live',
        testId: 'shop-agent-rep-feature-portal',
        externalRef: 'RepSpark',
      },
      {
        id: 'commission',
        labelRu: 'Commission',
        summaryRu: 'Preview · payout · share link.',
        status: 'live',
        testId: 'shop-agent-rep-feature-commission',
      },
      {
        id: 'matrix',
        labelRu: 'Matrix',
        summaryRu: 'Compact grid + W2 assortment.',
        status: 'live',
        testId: 'shop-agent-rep-feature-matrix',
        externalRef: 'NuOrder',
      },
    ],
  },
  'supplier-procurement': {
    id: 'supplier-procurement',
    capabilityId: 'dev-rfq-supplier',
    titleRu: 'MRP · procurement',
    leadRu: 'BOM под PO → RFQ chain → supplier inbox.',
    pillar: 'order_production',
    role: 'supplier',
    defaultFeatureId: 'bom',
    crossLinkAnchorId: 'dev-rfq-supplier',
    features: [
      {
        id: 'bom',
        labelRu: 'BOM',
        summaryRu: 'Progress + BOM lines snapshot.',
        status: 'live',
        testId: 'supplier-procurement-feature-bom',
        externalRef: 'Onfinity MRP',
      },
      {
        id: 'rfq',
        labelRu: 'RFQ',
        summaryRu: 'Centric · brand BOM · materials dossier.',
        status: 'live',
        testId: 'supplier-procurement-feature-rfq',
        externalRef: 'Centric PLM',
      },
      {
        id: 'supply',
        labelRu: 'Supply',
        summaryRu: 'MRP shortage → materials PO · W2 supply.',
        status: 'live',
        testId: 'supplier-procurement-feature-supply',
        externalRef: 'Onfinity MRP',
      },
      {
        id: 'order',
        labelRu: 'Order',
        summaryRu: 'B2B PO chat · calendar · MRP/supply bridges.',
        status: 'live',
        testId: 'supplier-procurement-feature-order',
        externalRef: 'NuOrder',
      },
      {
        id: 'inbox',
        labelRu: 'Inbox',
        summaryRu: 'Comms по заказу и артикулу.',
        status: 'live',
        testId: 'supplier-procurement-feature-inbox',
      },
      {
        id: 'forecast',
        labelRu: 'Forecast',
        summaryRu: 'B2B order × BOM need · collection_order peer.',
        status: 'live',
        testId: 'supplier-procurement-feature-forecast',
        externalRef: 'Onfinity MRP',
      },
      {
        id: 'entities',
        labelRu: 'Entities',
        summaryRu: 'BOM · RFQ · handoff · QC threads.',
        status: 'live',
        testId: 'supplier-procurement-feature-entities',
        externalRef: 'Centric PLM',
      },
    ],
  },
  'manufacturer-comms-workspace': {
    id: 'manufacturer-comms-workspace',
    capabilityId: 'comms-entity-threads',
    titleRu: 'Сообщения · threads',
    leadRu: 'Inbox + handoff/dossier/QC entity threads.',
    pillar: 'comms',
    role: 'manufacturer',
    defaultFeatureId: 'inbox',
    crossLinkAnchorId: 'comms-entity-threads',
    features: [
      {
        id: 'inbox',
        labelRu: 'Inbox',
        summaryRu: 'Order + article contextual threads.',
        status: 'live',
        testId: 'manufacturer-comms-feature-inbox',
      },
      {
        id: 'entities',
        labelRu: 'Entities',
        summaryRu: 'Handoff · dossier · QC · sample.',
        status: 'live',
        testId: 'manufacturer-comms-feature-entities',
        externalRef: 'Centric PLM',
      },
      {
        id: 'order',
        labelRu: 'Order',
        summaryRu: 'B2B PO chat · calendar · chain bridges.',
        status: 'live',
        testId: 'manufacturer-comms-feature-order',
        externalRef: 'NuOrder',
      },
    ],
  },
  'manufacturer-production-ops': {
    id: 'manufacturer-production-ops',
    capabilityId: 'op-cut-ticket-wip',
    titleRu: 'PO registry · WIP',
    leadRu: 'Factory orders · shop floor WIP · cut ticket bridges.',
    pillar: 'order_production',
    role: 'manufacturer',
    defaultFeatureId: 'orders',
    crossLinkAnchorId: 'op-cut-ticket-wip',
    features: [
      {
        id: 'orders',
        labelRu: 'Orders',
        summaryRu: 'Handoff queue registry · ERP ack.',
        status: 'live',
        testId: 'manufacturer-production-feature-orders',
        externalRef: 'WFX',
      },
      {
        id: 'wip',
        labelRu: 'WIP',
        summaryRu: 'MES strip · shop floor · materials.',
        status: 'live',
        testId: 'manufacturer-production-feature-wip',
        externalRef: 'Apparel Magic',
      },
      {
        id: 'cut-ticket',
        labelRu: 'Cut ticket',
        summaryRu: 'Техкарта раскроя бренда · досье · трекинг.',
        status: 'live',
        testId: 'manufacturer-production-feature-cut-ticket',
      },
    ],
  },
  'manufacturer-handoff-queue': {
    id: 'manufacturer-handoff-queue',
    capabilityId: 'op-handoff-queue',
    titleRu: 'Handoff · очередь цеха',
    leadRu: 'W2: sample queue → B2B handoff → production orders.',
    pillar: 'order_production',
    role: 'manufacturer',
    defaultFeatureId: 'handoff',
    crossLinkAnchorId: 'op-handoff-queue',
    features: [
      {
        id: 'sample-queue',
        labelRu: 'Sample queue',
        summaryRu: 'W2 sample requests до PO.',
        status: 'live',
        testId: 'manufacturer-handoff-feature-sample-queue',
      },
      {
        id: 'handoff',
        labelRu: 'Handoff',
        summaryRu: 'B2B PO → ERP ack → shop floor.',
        status: 'live',
        testId: 'manufacturer-handoff-feature-handoff',
        externalRef: 'Apparel Magic',
      },
      {
        id: 'orders-bridge',
        labelRu: 'Orders',
        summaryRu: 'PO цеха · brand ops · tracking.',
        status: 'live',
        testId: 'manufacturer-handoff-feature-orders-bridge',
        externalRef: 'WFX',
      },
      {
        id: 'qc-gate',
        labelRu: 'QC gate',
        summaryRu: 'AQL · dossier · brand QC tab.',
        status: 'live',
        testId: 'manufacturer-handoff-feature-qc-gate',
        externalRef: 'Inspectorio',
      },
      {
        id: 'techpack-ack',
        labelRu: 'Factory-ack',
        summaryRu: 'Tech pack приёмка цехом → POST handoff/factory-ack.',
        status: 'live',
        testId: 'manufacturer-handoff-feature-techpack-ack',
        externalRef: 'Apparel Magic',
      },
    ],
  },
  'brand-inventory-ops': {
    id: 'brand-inventory-ops',
    capabilityId: 'op-inventory-atp',
    titleRu: 'Brand · ATP',
    leadRu: 'Matrix hub → balance transfer → shop network sync.',
    pillar: 'order_production',
    role: 'brand',
    defaultFeatureId: 'overview',
    crossLinkAnchorId: 'op-inventory-atp',
    features: [
      {
        id: 'overview',
        labelRu: 'Обзор',
        summaryRu: 'Brand ledger + SKU matrix entry.',
        status: 'live',
        testId: 'brand-inventory-feature-overview',
      },
      {
        id: 'balance',
        labelRu: 'Balance',
        summaryRu: 'Stock transfer · multi-location.',
        status: 'live',
        testId: 'brand-inventory-feature-balance',
        externalRef: 'Onfinity',
      },
      {
        id: 'count',
        labelRu: 'Count',
        summaryRu: 'Physical count → shop reconcile.',
        status: 'live',
        testId: 'brand-inventory-feature-count',
        externalRef: 'Onfinity',
      },
      {
        id: 'network',
        labelRu: 'Network',
        summaryRu: 'Shop ATP · reconcile · replenishment.',
        status: 'live',
        testId: 'brand-inventory-feature-network',
      },
    ],
  },
  'brand-crm-segmentation': {
    id: 'brand-crm-segmentation',
    capabilityId: 'crm-segmentation',
    titleRu: 'BP Segmentation',
    leadRu: 'Customer groups → price tiers → showroom gates.',
    pillar: 'comms',
    role: 'brand',
    defaultFeatureId: 'segments',
    crossLinkAnchorId: 'crm-segmentation',
    features: [
      {
        id: 'segments',
        labelRu: 'Segments',
        summaryRu: 'Retail · wholesale · franchise tiers.',
        status: 'live',
        testId: 'brand-crm-segmentation-feature-segments',
        externalRef: 'Onfinity CRM',
      },
      {
        id: 'pricelist',
        labelRu: 'Pricelist',
        summaryRu: 'Group → price list versions.',
        status: 'live',
        testId: 'brand-crm-segmentation-feature-pricelist',
      },
      {
        id: 'showroom',
        labelRu: 'Showroom',
        summaryRu: 'Segment-gated buyer access.',
        status: 'live',
        testId: 'brand-crm-segmentation-feature-showroom',
        externalRef: 'NuOrder',
      },
    ],
  },
  'platform-b2b-hub': {
    id: 'platform-b2b-hub',
    capabilityId: 'sc-showroom-buy',
    titleRu: 'B2B Platform hub',
    leadRu: 'Entry: overview → marketroom → partners (столп 2).',
    pillar: 'sample_collection',
    role: 'shop',
    defaultFeatureId: 'hub',
    crossLinkAnchorId: 'sc-showroom-buy',
    features: [
      {
        id: 'hub',
        labelRu: 'Hub',
        summaryRu: 'Overview · shop/brand bridges · buy path.',
        status: 'live',
        testId: 'platform-b2b-hub-feature-hub',
        externalRef: 'JOOR',
      },
      {
        id: 'marketroom',
        labelRu: 'Marketroom',
        summaryRu: 'Bridge to full marketroom workspace.',
        status: 'live',
        testId: 'platform-b2b-hub-feature-marketroom',
        externalRef: 'NuOrder',
      },
      {
        id: 'partners',
        labelRu: 'Partners',
        summaryRu: 'Bridge to partners directory workspace.',
        status: 'live',
        testId: 'platform-b2b-hub-feature-partners',
      },
    ],
  },
  'platform-b2b-partners': {
    id: 'platform-b2b-partners',
    capabilityId: 'sc-showroom-buy',
    titleRu: 'Партнёры',
    leadRu: 'Глобальная экосистема авторизованных партнеров.',
    pillar: 'sample_collection',
    role: 'shop',
    defaultFeatureId: 'directory',
    crossLinkAnchorId: 'sc-showroom-buy',
    features: [
      {
        id: 'directory',
        labelRu: 'Directory',
        summaryRu: 'BPI brand catalog · viewRole=b2b.',
        status: 'live',
        testId: 'platform-b2b-partners-feature-directory',
        externalRef: 'JOOR',
      },
      {
        id: 'shop-roster',
        labelRu: 'Shop roster',
        summaryRu: 'Buy-side partnerships · discover · rep.',
        status: 'live',
        testId: 'platform-b2b-partners-feature-shop-roster',
        externalRef: 'RepSpark',
      },
      {
        id: 'marketroom',
        labelRu: 'Marketroom',
        summaryRu: 'Showcase · discover · buy path bridge.',
        status: 'live',
        testId: 'platform-b2b-partners-feature-marketroom',
        externalRef: 'NuOrder',
      },
    ],
  },
  'platform-b2b-marketroom': {
    id: 'platform-b2b-marketroom',
    capabilityId: 'sc-showroom-buy',
    titleRu: 'Маркетрум',
    leadRu: 'Все артикулы всех авторизованных партнёров.',
    pillar: 'sample_collection',
    role: 'shop',
    defaultFeatureId: 'showcase',
    crossLinkAnchorId: 'sc-showroom-buy',
    features: [
      {
        id: 'showcase',
        labelRu: 'Showcase',
        summaryRu: 'Единый каталог артикулов всех партнёров.',
        status: 'live',
        testId: 'platform-b2b-marketroom-feature-showcase',
        externalRef: 'JOOR',
      },
      {
        id: 'discover',
        labelRu: 'Discover',
        summaryRu: 'Collections · linesheet · brand preview.',
        status: 'live',
        testId: 'platform-b2b-marketroom-feature-discover',
        externalRef: 'NuOrder',
      },
      {
        id: 'buy-path',
        labelRu: 'Buy path',
        summaryRu: 'Matrix → checkout · working order · margin.',
        status: 'live',
        testId: 'platform-b2b-marketroom-feature-buy-path',
        externalRef: 'JOOR',
      },
    ],
  },
  'shop-inventory-ops': {
    id: 'shop-inventory-ops',
    capabilityId: 'op-inventory-atp',
    titleRu: 'Остатки · ATP',
    leadRu: 'Ledger grains + cycle count → replenish.',
    pillar: 'order_production',
    role: 'shop',
    defaultFeatureId: 'overview',
    crossLinkAnchorId: 'op-inventory-atp',
    features: [
      {
        id: 'overview',
        labelRu: 'Обзор',
        summaryRu: 'Retail inventory hub.',
        status: 'live',
        testId: 'shop-inventory-feature-overview',
      },
      {
        id: 'reconcile',
        labelRu: 'Reconcile',
        summaryRu: 'Physical count → discrepancy.',
        status: 'live',
        testId: 'shop-inventory-feature-reconcile',
        externalRef: 'Onfinity',
      },
    ],
  },
};

export function getPillarCapabilityWorkspace(
  workspaceId: string
): PillarCapabilityWorkspace | undefined {
  return PILLAR_CAPABILITY_WORKSPACES[workspaceId];
}

export function resolvePillarWorkspaceFeatureId(
  workspace: PillarCapabilityWorkspace,
  requestedId: string | null | undefined
): string {
  if (!requestedId) return workspace.defaultFeatureId;
  const found = workspace.features.find((f) => f.id === requestedId);
  if (!found || found.status === 'planned') return workspace.defaultFeatureId;
  return found.id;
}

export function getPillarWorkspaceFeature(
  workspace: PillarCapabilityWorkspace,
  featureId: string
): PillarCapabilityFeature {
  return (
    workspace.features.find((f) => f.id === featureId) ??
    workspace.features.find((f) => f.id === workspace.defaultFeatureId)!
  );
}
