/**
 * Wave YU — re-exports wave YR brand SC 1.2 mini-matrix CTA (backward compat).
 */
export {
  brandScCrossMatrixOneClickAriaLabelRu,
  WAVE_YR_BRAND_SC_MATRIX_DEDUP_FIXES as WAVE_YU_BRAND_SC_MATRIX_DEDUP_FIXES,
  WAVE_YR_BRAND_SC_MATRIX_ONE_CLICK_ARIA_SUFFIX_RU as WAVE_YU_BRAND_SC_MATRIX_ONE_CLICK_ARIA_SUFFIX_RU,
  WAVE_YR_BRAND_SC_MINI_MATRIX_HINT_TESTID as WAVE_YU_BRAND_SC_MINI_MATRIX_HINT_TESTID,
  WAVE_YR_BRAND_SC_MINI_MATRIX_LINK_TESTID as WAVE_YU_BRAND_SC_MINI_MATRIX_LINK_TESTID,
  WAVE_YR_BRAND_SC_MINI_MATRIX_STRIP_TESTID as WAVE_YU_BRAND_SC_MINI_MATRIX_STRIP_TESTID,
  WAVE_YR_BRAND_SC_OPEN_SHOP_BTN_TESTID as WAVE_YU_BRAND_SC_OPEN_SHOP_BTN_TESTID,
  WAVE_YR_BRAND_SC_OPEN_SHOP_PREFILL_HINT_TESTID as WAVE_YU_BRAND_SC_OPEN_SHOP_PREFILL_HINT_TESTID,
  WAVE_YR_BRAND_SC_OPEN_SHOP_STRIP_TESTID as WAVE_YU_BRAND_SC_OPEN_SHOP_STRIP_TESTID,
} from '@/lib/platform/wave-yr-brand-sc-matrix-cta';
