import { LEGACY_ROUTES } from '@/lib/platform-core-legacy-routes';
/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { PILLAR_CAPABILITY_FEATURE_PARAM } from '@/lib/platform/pillar-capability-workspaces';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import { platformCoreCabinetSectionHref } from '@/lib/platform-core-cabinet-workspace';
import { platformCoreCommsNotesHref } from '@/lib/platform-core-notes';
import type { SectionAuditTemplate } from './types';

export const BRAND_SECTION_AUDIT: Partial<
  Record<CoreHubPillarId, readonly SectionAuditTemplate[]>
> = {
  development: [
    {
      id: 'brand-dev-w2-hub',
      label: 'Цех разработки · артикулы',
      order: 1,
      staticScore: 7.2,
      liveScore: 7.3,
      summary: 'Hub артикулов, PG-hydrate, EMPTY27 onboarding + shop monetization peers.',
      good: [
        'PG-authoritative SS27/FW27',
        'brand-dev-w2-hub-panel + golden path strip (`brand-sample-lifecycle-golden-path-strip`)',
        'Peer: range/linesheets/showroom/factory dossier/sample queue',
        'Shop monetization + CRM peers (`brand-dev-w2-hub-co-peer-strip`, matrix/checkout/tracking)',
        'Greenfield monetization segment PG read strip RU (`brand-dev-greenfield-monetization-segment-strip`, `brand-dev-greenfield-label`)',
        'Sample state-change webhook stub (`POST /api/workshop2/samples/state-change-webhook`)',
        'UI «Создать артикул» (`brand-w2-create-article-btn`)',
        'Bulk-import SKU (`brand-w2-bulk-import-*`, core-30 e2e)',
        'Create-article wizard UI round-trip (core-37 e2e)',
        'Create-article wizard draft PG (`brand-w2-create-article-draft-storage-pg`, core-104)',
        'PG sync hint (`workshop2-core-pg-sync-hint`)',
        'e2e core-01 + core-02 smoke',
        'EMPTY27 onboarding (`brand-dev-empty-onboarding`, core-44)',
        'core-52 TZ export + composition label e2e',
        'core-53 investor brief PDF export (`brief.pdf`)',
        'Investor summary strip on hub (`brand-dev-w2-hub-investor-summary-strip`)',
        'Publish release peer strip (`brand-sc-publish-release-peer-strip`)',
        'Sample status SSE на hub (`brand-w2-sample-status-sse-live` / `brand-w2-sample-status-sse-poll`, `workshop2-hub-production-rollup`)',
        'Wave VP: S1 LS final sweep — W2 hub readPath api-only, no silent LS flip (wave-vp-s1-final-sweep.test.ts)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('brand', 'development', 'brand-dev-w2-hub', d),
    },
    {
      id: 'brand-dev-dossier',
      label: 'Досье артикула · техзадание',
      order: 2,
      staticScore: 7.8,
      liveScore: 7.9,
      summary:
        'Паспорт, persist API — phase1-dossier PG-only + diff↔attach TZ (~8.0 после wave XQ).',
      good: [
        'brand-dev-dossier-panel + context/cross strips',
        'CO monetization peer matrix/checkout/CRM (`brand-dev-dossier-co-peer-strip`)',
        'Investor summary deep-link (`brand-dev-dossier-investor-summary-link`)',
        'PUT/GET dossier PG',
        'e2e UI 4 поля general + API 3 поля passportProductionBrief (core-02)',
        'e2e material: BOM + composition wizard 1–4 + fiber constructor UI/API (core-02)',
        'e2e construction: smartRoutingSequence equipment UI + API round-trip (core-02)',
        'e2e assignment: PG chip + factory handoff gate (core-02)',
        'brand-dossier-article-chat-link',
        'Gates ТЗ link (`brand-w2-gates-summary-link`)',
        'BOM/sample badges в wayfinding',
        'Скачать пакет ТЗ (`brand-w2-tz-export-btn`) + статус gate',
        'Отправить ТЗ в чат (`brand-w2-tz-attach-chat-btn`) + e2e core-02',
        'Inline diff vs factory dossier live PG (`brand-dossier-factory-diff-*`, GET dossier-factory-diff, Wave UN)',
        'Live diff polish: loading badge + storage mode + mismatch row highlight (Wave UY)',
        'Attach TZ PDF peer on B2B order (`brand-op-attach-tz-pdf-peer-strip`, POST attach-tz-pdf, core-145 wave UY)',
        'phase1-dossier offline dual-write OFF in core (`shouldPersistPhase1DossierOfflineDualWrite`)',
        'Collection stage modules PG (`/api/brand/collection-stage-modules`, `brand-collection-stage-modules-storage-pg`)',
        'Wave SN: core без mirror stage-modules в localStorage',
        'core-52 export-tz-bundle gate/ZIP + composition panel e2e',
        'core-53 investor-readiness + investor-brief page e2e',
        'core-53 investor brief PDF export',
        'Wave XQ: offline dual-write OFF banner RU + PG fail-closed (`workshop2-phase1-dossier-core-offline-blocked-banner`, core-206)',
        'Wave XQ: factory diff panel ↔ attach TZ PO cross-strip (`brand-dossier-diff-attach-tz-po-cross-strip`, `brand-op-attach-tz-po-strip`)',
        'Wave XQ: attach TZ diff viewer back-link on B2B order (`brand-dossier-attach-tz-po-diff-viewer-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('brand', 'development', 'brand-dev-dossier', d),
    },
    {
      id: 'brand-dev-range',
      label: 'Планировщик ассортимента',
      order: 3,
      staticScore: 7.8,
      liveScore: 7.9,
      summary: 'Tier, бюджет, маржа из PG — bulk tier XG + conflict RU (~8.0 после wave XG).',
      good: [
        'brand-dev-range-panel + context strip (W2/dossier/factory/showroom/linesheets)',
        'budgetFromPg на SS27/FW27 e2e',
        'Tier SKU counts из PG',
        'Сводка маржи (`range-planner-margin-summary`)',
        'Ссылка tier → W2 (`range-planner-tier-w2-link`)',
        'Quick-create + e2e tier-w2 deep link',
        'Peer links витрина/лайншиты',
        'Редактирование маржи/бюджета (`range-planner-tier-plan-save-*`)',
        'EMPTY27 баннер (`range-planner-empty-chain-notice`)',
        'Назначение tier (`range-planner-tier-assign-panel`)',
        'Cabinet EMPTY27 plan CTA (`brand-dev-empty-range-link`, core-44)',
        'core-52 tier assign panel smoke',
        'core-53 PATCH margin core/trend/novelty + tier assign API',
        'Drag-reorder tier columns (`range-planner-tier-article-board`, core-58 e2e)',
        'Within-tier order PATCH (`tierArticleOrder`, `range-planner-tier-reorder-*`)',
        'PG overlay API + conflict banner (`/api/brand/range-planner/overlay`, `brand-range-planner-overlay-conflict-banner`, `brand-range-planner-overlay-sync-btn`)',
        'Пакетное назначение tier (`range-planner-tier-bulk-assign-btn`, PATCH assignTier+articleIds, core-112)',
        'Wave UM bulk tier POST (`/api/workshop2/range-planner/bulk-tier-assign`, core-138)',
        'Wave UM conflict resolver strip (`brand-range-planner-conflict-resolver-strip`, tier rows, core-138)',
        'Wave XG: bulk-tier-assign POST wave=xg + batch max 48 (core-196)',
        'Wave XG: conflict resolver RU labelRu on tier rows + overlay sync banner',
        'Wave XG: range planner ↔ shop matrix tier badge cross-link (core-196)',
        'Shop matrix + checkout peers (`brand-dev-range-shop-matrix-link`, `brand-dev-range-shop-checkout-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.rangePlanner}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-dev-pg-sync',
      label: 'Статус разработки · PG',
      order: 4,
      staticScore: 7.8,
      liveScore: 7.9,
      summary:
        'development-status API, readPath banner + LIVE process runtime PG (~8.0 после wave XR/XS).',
      good: [
        'API development-status',
        'Published-articles для витрины',
        'Sample queue в factory',
        'Бейдж статуса образца в DevelopmentPillarCard',
        'Позиция в очереди (`development-sample-queue-position`)',
        'workshop2-core-pg-sync-hint на W2 hub (core mode)',
        'Core readPath=api-only без LS fallback (`workshop2-pg-read-path-policy`, publishedArticlesReadPath=api)',
        'Range planner overlay PG-only write в core (без dual-write LS)',
        'Workshop2HubSlaOpsPanel compact на W2 hub (`workshop2-hub-sla-ops-panel`)',
        'PG sync peer strip (`brand-dev-pg-sync-peer-strip`: range/samples/factory/comms)',
        'Cabinet PG sync peer (`brand-dev-pg-sync-peer-strip` на DevelopmentPillarCard)',
        'core-02 столп 1 hub→W2→range→factory',
        'Прогресс % (`development-progress-pct`)',
        'Sample status → comms inbox bump (`sample_order.status_changed`)',
        'W2 hub SSE sample rollup (`brand-w2-sample-status-sse-*`)',
        'Sample state-change inbound webhook (`/api/workshop2/samples/state-change-webhook`)',
        'Wave XE: S1 LS final sweep — BFF storageMode pg on ops/wizard/prefs (core-194)',
        'Wave XE: production ops PG badge (`brand-production-ops-storage-pg`, fail-closed core)',
        'Wave XR: LIVE process runtime GET/PUT PG + storageMode badge (`live-process-runtime-storage-pg`, core-207)',
        'Wave XR: process runtime fail-closed localStorage in core (`/api/processes/*/runtime`)',
        'Wave XS: W2 hub readPath=api-only banner when PG down (`workshop2-core-hub-readpath-local-banner`, core-208)',
        'Wave XS: published-articles API list badge RU on W2 hub (`workshop2-pg-source-stats`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.productionWorkshop2}?${WORKSHOP2_COL_PARAM}=${encodeURIComponent(d.collectionId)}&article=${encodeURIComponent(d.demoArticleId)}`,
    },
    {
      id: 'brand-dev-cabinet',
      label: 'Кабинет · карточка столпа',
      order: 5,
      staticScore: 7.7,
      liveScore: 7.8,
      summary: 'DevelopmentPillarCard dashboard strips — Kanban dedup (~8.0 после wave XF).',
      good: [
        'brand-dev-cabinet-panel + context/cross strips',
        'Wave VF dashboard strips wrapper (`brand-dev-dashboard-strips`)',
        'Investor-readiness PG strip (`brand-dev-investor-readiness-*`, GET `/api/workshop2/investor-readiness`)',
        'Progress/BOM/sample queue badges',
        'e2e development-bom-ready-badge + cabinet links',
        'Create-article deep-link через W2 hub (core-37)',
        'EMPTY27 onboarding strip (`brand-dev-empty-onboarding`, core-44)',
        'Sample lifecycle + attribute schema cabinet links (`brand-dev-cabinet-sample-lifecycle-link`, `brand-dev-cabinet-attribute-schema-link`)',
        'Supplier BOM peer when PG (`brand-dev-cross-supplier-bom-link`)',
        'CO monetization peer linesheets/showroom/matrix/checkout/CRM (`brand-dev-cabinet-co-peer-strip`)',
        'Greenfield monetization segment PG read strip RU (`brand-dev-greenfield-monetization-segment-strip`, `brand-dev-greenfield-label`)',
        'Dev cabinet live SSE badge (`brand-dev-development-sse-live-badge`, `data-development-sse-live`)',
        'Kanban mini-panel GET/POST (`brand-dev-tasks-kanban-*`, `/api/brand/tasks`)',
        'core-151 wave VF brand dev dashboard e2e',
        'Wave XF: W2 hub kanban+calendar strip (`brand-dev-w2-hub-tasks-kanban-strip`, core-195)',
        'Wave XF: cabinet inline kanban без dup peer link (`brand-dev-investor-readiness-kanban-peer-link` hidden)',
        'Wave XF: greenfield monetization PG segment RU (`brand-dev-greenfield-monetization-segment-strip`)',
        'Wave XF: brand tasks API GET/POST round-trip (core-195)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.coreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-dev-cross',
      label: 'Связь · цех и поставщик',
      order: 6,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'Горизонталь к dossier цеха и supplier BOM; sample/schema peers в cabinet.',
      good: [
        'brand-dev-cross-context-strip в кабинете',
        'Sample peer: W2 plan / factory dossier read-only (platform-core-brand-sample-peer)',
        'Factory dossier + supplier BOM links с testids',
        'BOM + sample queue badges',
        'EMPTY27 onboarding в cabinet (core-44)',
        'Sample status → comms inbox bump (`sample_order.status_changed` + COMMS_INBOX_BUMP)',
        'Sample lifecycle comms peer strip (`brand-sample-lifecycle-comms-peer-strip`)',
        'Cabinet peers: sample lifecycle, attribute schema, supplier BOM',
        'PG sync peer на cabinet (`brand-dev-pg-sync-factory-dossier-link`, `brand-dev-pg-sync-schema-link`)',
        'Wave YP: merch CO spine peer RU linesheets/showroom (`brand-attribute-schema-co-spine-peer-strip`, core-231)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        factoryProductionDossierHref(d.demoArticleId, { collectionId: d.collectionId }),
    },
    {
      id: 'brand-dev-attribute-schema',
      label: 'Attribute schema · health',
      order: 8,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'PG schema + size-chart grade feed; golden path + shop CO spine peers.',
      good: [
        'brand-attribute-schema workspace',
        'Golden path strip (`brand-attribute-schema-golden-path-strip`)',
        'CO spine peer linesheets/showroom/matrix/checkout/CRM (`brand-attribute-schema-co-spine-peer-strip`)',
        'Schema↔passport peer strip (`brand-dev-schema-passport-peer-strip`, Wave VM)',
        'PG schema feed API + sync catalog',
        'PG size-chart grade PATCH + handbook scale',
        'W2 fix links на attribute gaps',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.attributeHealth}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-dev-material-passport',
      label: 'Material passport · rollup',
      order: 7,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'Rollup/certs/release + golden path + shop CO spine peers.',
      good: [
        'brand-material-passport workspace (rollup/certs/release)',
        'Golden path strip (`brand-material-passport-golden-path-strip`)',
        'CO spine peer linesheets/showroom/matrix/checkout/CRM (`brand-material-passport-co-spine-peer-strip`)',
        'Schema↔passport peer strip (`brand-dev-schema-passport-peer-strip`, Wave VM)',
        'PG rollup API + dossier composition overlay + sync',
        'PG certs patch ready + release blocked badge',
        'Certs toggle API + CSV export',
        'SC release gate check API blocks publish until certs ready (Wave UV)',
        'Wave VM: schema↔passport peer strip (`brand-dev-schema-passport-peer-strip`)',
        'Wave VM: SC check API on passport release panel (`brand-material-passport-release-sc-gate-*`)',
        'Wave VM: syndicate 409 RU banner (`brand-sc-release-gate-block-syndicate-banner`)',
        'Wave VM: release gate block на showroom one-click publish',
        'Wave YP: passport release gate peer RU checklist/showroom publish (`brand-dev-passport-release-gate-peer-strip`, core-231)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.fabricPassportRollup}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-dev-rfq-supplier',
      label: 'Centric RFQ · upstream',
      order: 9,
      staticScore: 7.2,
      liveScore: 7.3,
      summary: 'Centric import/registry/quote award PG + golden path + shop CO spine.',
      good: [
        'brand-rfq-supplier workspace',
        'Golden path strip (`brand-rfq-supplier-golden-path-strip`)',
        'CO spine peer linesheets/showroom/matrix/checkout/CRM (`brand-rfq-supplier-co-spine-peer-strip`)',
        'Centric import/registry/quote panels',
        'PG quote award API + supplier MRP cross-link',
        'Entity threads на comms tab',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.integrationsCentric}?collection=${encodeURIComponent(d.collectionId)}&${PILLAR_CAPABILITY_FEATURE_PARAM}=upstream`,
    },
    {
      id: 'brand-dev-supplier-bom',
      label: 'Supplier BOM · procurement',
      order: 10,
      staticScore: 7.2,
      liveScore: 7.3,
      summary: 'PG BOM lines seed + snapshot merge; golden path + shop CO spine peers.',
      good: [
        'brand-supplier-bom workspace',
        'Golden path strip (`brand-supplier-bom-golden-path-strip`)',
        'CO spine peer linesheets/showroom/matrix/checkout/CRM (`brand-supplier-bom-co-spine-peer-strip`)',
        'PG BOM lines API + snapshot merge + default seed',
        'SupplierBomPreview + sync BOM',
        'Procurement entity threads',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.suppliersRfq}?collection=${encodeURIComponent(d.collectionId)}&${PILLAR_CAPABILITY_FEATURE_PARAM}=bom`,
    },
  ],
  sample_collection: [
    {
      id: 'brand-sc-linesheets',
      label: 'Лайншиты · коллекция',
      order: 1,
      staticScore: 6.9,
      liveScore: 7,
      summary: 'PG read-only, PDF, batch publish + audit log + unified audit path.',
      good: [
        'linesheets-core PG',
        'CTA → матрица на каждой строке + matrix qty badge + preview qty column',
        'Context strip PDF/showroom/W2/shop matrix/checkout',
        'e2e core-02',
        'Unpublish (`brand-sc-linesheets-unpublish-*`)',
        'Empty state CTA W2/витрина',
        'Empty fallback copy (`brand-sc-linesheets-empty-copy`, EMPTY27 honest)',
        'brand-sc-linesheets-batch-publish + readiness (core-28/41)',
        'brand-sc-publish-audit-log panel (core-29/41/117)',
        'PG publish audit journal (`brand_sc_publish_audit_journal`, Wave TN)',
        'Unified audit path на полной странице (core-46)',
        'Published sync badge W2 vs showroom (core-46)',
        'PDF disabled until publish (`brand-sc-linesheet-pdf-empty-disabled`, wave VC)',
        'PDF empty hint RU (`brand-sc-linesheet-pdf-empty-hint`, EMPTY27 honest)',
        'publishedArticlesReadPath=api badge (`brand-sc-published-readpath-api`, core-only)',
        'Cover hero priority strip dossier>partner (`shop-sc-showroom-cover-hero-priority-strip`, wave VC)',
        'Retail peer strip release→matrix→checkout (`brand-sc-linesheets-retail-peer-strip`)',
        'Wave YP: linesheets retail peer RU release gate (`brand-sc-linesheets-retail-peer-strip`, core-231)',
        'Syndication API POST + shop auto-ingest (`/api/brand/linesheets/syndicate`, `brand-sc-linesheets-syndicate-btn`)',
        'Passport release gate blocks syndicate publish 409 (Wave UV)',
        'Release gate block strip на batch publish (`brand-sc-release-gate-block-strip`)',
        'Batch unpublish rollback stub (`/api/brand/linesheets/batch-unpublish-rollback`, `brand-sc-linesheets-batch-unpublish-rollback`, wave VC verify core-148)',
        'Wave WD: syndication/unpublish/rollback → PG publish audit (`linesheet.syndicated`, core-167)',
        'Wave WD: syndication panel + audit PG badge (`brand-sc-linesheets-syndicate-wd-panel`, `brand-sc-syndication-wd-audit-pg`)',
        'PG shop notification on syndication publish (Wave TF)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandLinesheetsHrefForDemo(d),
    },
    {
      id: 'brand-sc-showroom',
      label: 'Витрина бренда',
      order: 2,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'Опубликованные артикулы, превью из досье — вход для магазина.',
      good: [
        'Published-articles API',
        'Showroom core chrome',
        'Release gate в unified audit path',
        'CTA «Матрица магазина» на карточке артикула',
        'Чат артикула с витрины (`brand-sc-showroom-article-chat-link-*`)',
        'Context strip: count + цепочка (`brand-sc-unified-audit-path`)',
        'Unified audit path на полной странице (core-45)',
        'Footer CTA matrix + linesheets',
        'e2e core-01 showroom cross-role',
        'Peer checkout e2e (`brand-sc-showroom-shop-checkout-link`, core-52)',
        'Golden path strip preview→shop matrix (`brand-showroom-buy-golden-path-strip`)',
        'Retail peer strip linesheets/release/platform/matrix/checkout (`brand-sc-showroom-retail-peer-strip`)',
        'Wave YP: showroom retail peer RU (`brand-sc-showroom-retail-peer-strip`, core-231)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandShowroomHrefForDemo(d),
    },
    {
      id: 'brand-sc-publish',
      label: 'Публикация · витрина',
      order: 3,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'Связь W2 → published-articles — критично для витрины магазина.',
      good: [
        'Seed showroom SS27',
        'brand-sc-linesheets-batch-publish + publish audit (core-29/46)',
        'Кнопка «Снять с витрины» (`brand-sc-linesheets-unpublish-*`)',
        'PUT showroom published:false',
        'Workshop2HubShowroomPublishButton на W2 hub (`brand-dev-w2-hub-publish-strip`)',
        'Publish audit log на linesheets (core-29/46)',
        'Publish audit log на W2 hub (`brand-sc-publish-audit-log` в `brand-dev-w2-hub-panel`)',
        'Release golden path strip (`brand-release-golden-path-strip`)',
        'Release showroom-publish tab: bulk publish (`brand-sc-publish-button`, `brand-release-showroom-publish-panel`)',
        'Syndication push → publish strip CTA (`brand-release-syndication-push-publish-cta`)',
        'Publish release peer on W2 hub (`brand-sc-publish-release-peer-strip`)',
        'Publish peer shop matrix/checkout/platform/linesheets (`brand-sc-publish-shop-matrix-link`, `brand-sc-publish-platform-hub-link`)',
        'Syndication → shop auto-ingest + PG notification (`brand-release-syndication-push` → `/api/brand/linesheets/syndicate`)',
        'Wave UV: passport release gate POST (`/api/brand/sample-collection/release-gate/check`, 409 RU)',
        'Schema/passport peer strip на release workspace (`brand-sc-release-gate-schema-passport-peer-strip`)',
        'Wave YP: release gate schema/passport peer RU (`brand-sc-release-gate-schema-passport-peer-strip`, core-231)',
        'Publish block UI (`brand-sc-release-gate-block-*`) на linesheets + showroom-publish',
        'Wave VM: showroom publish one-click + syndicate 409 RU banners',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('brand', 'sample_collection', 'brand-sc-publish', d),
    },
    {
      id: 'brand-sc-cross-matrix',
      label: 'Cross-role · матрица магазина',
      order: 4,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'Инвест-перспектива: бренд видит путь ритейлера к заказу.',
      good: [
        'Единая цепочка в кабинете (`brand-sc-unified-audit-path`)',
        'Release gate в golden path (`brand-sc-audit-path-release-gate`)',
        'UAT cross-role strip (`brand-sc-cross-role-audit-uat-*`)',
        'Peer: matrix/checkout/showroom магазина',
        'Linesheets matrix qty badge',
        'Showroom/linesheets peer CTA',
        'e2e cabinet → shop matrix',
        'Peer checkout e2e (core-52)',
        'Cabinet retail peer platform/matrix/checkout (`brand-sc-cabinet-retail-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.shop.b2bMatrix}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-sc-cabinet',
      label: 'Кабинет · лайншит и витрина',
      order: 5,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'BrandSampleCollectionMini — counts и hub strips.',
      good: [
        'brand-sc-cabinet-panel + единая цепочка (`brand-sc-unified-audit-path`)',
        'Release gate step в audit path',
        'PG counts + published badge',
        'Error fallback с рабочими ссылками',
        'e2e core-01/06 cabinet',
        'core-02 + core-52 mini matrix + checkout deep-link e2e',
        'Published count sync badge mini↔live (`brand-sc-cabinet-published-sync`)',
        'Cabinet mini-matrix + readpath badge (`brand-sample-collection-mini-matrix`, `brand-sc-published-readpath-api`, wave VC)',
        'Cabinet retail peer platform/matrix/checkout (`brand-sc-cabinet-retail-peer-strip`)',
        'PG publish audit panel (`brand-release-publish-audit-panel`, core-117)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.coreCabinet}?pillar=sample_collection&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
  collection_order: [
    {
      id: 'brand-co-registry',
      label: 'Реестр оптовых заказов',
      order: 1,
      staticScore: 7.3,
      liveScore: 7.4,
      summary: 'Список B2B из PG + retail onboarding + export/handoff.',
      good: [
        'b2b-orders-core PG',
        'Legacy redirect B2B-00xx',
        'List chrome',
        'B2bChainPhaseBadge + фильтр коллекции',
        'Dynamic PG collections filter (`/api/workshop2/collections`, core-47)',
        'PG collections badge (`brand-co-registry-pg-collections-badge`)',
        'Экспорт CSV/JSON (`brand-co-registry-export-pg`, export-json)',
        'spineChannel в export (neutral RU)',
        'brand-co-registry-import-toolbar на core path',
        'core-32: JOOR import → export spineChannel e2e',
        'core-33 v1 operational PG-primary INT + native',
        'core-52 native B2B-DEMO in operational API',
        'core-43: checkout B2B-\\d+ в JSON export (clean PG)',
        'Context strip: заказ · в производстве · invite (без чата в strip)',
        'Канон panel/focus (`brand-co-registry-panel`, `brand-co-registry-focus-row`)',
        'SSE registry refetch при новом заказе (`registry-stream`)',
        'core-51 prebook row e2e (conditional seed)',
        'CRM invite (`brand-co-registry-invite-panel`, симметрия shop)',
        'Retail onboarding strip CRM/pricelist/showroom/matrix/checkout (`brand-co-registry-retail-onboarding-strip`)',
        'Amend queue → detail approve (`brand-co-registry-amend-detail-link`, wave TS)',
        'Multi-buyer partner filter PG query (`brand-co-registry-partner-filter`, `partnerIds` API, wave VI)',
        'PG multi-buyer badge (`brand-co-registry-pg-partner-badge`, core-153)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('brand', 'collection_order', 'brand-co-registry', d),
    },
    {
      id: 'brand-co-detail',
      label: 'Карточка заказа',
      order: 2,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'Факты PG — disclosure + comms section thread from detail chat (core-44/46).',
      good: [
        'PlatformCoreB2bOrderDetailFacts',
        'Цепочка заказа первым блоком — handoff без scroll',
        'POST confirm-order отдельно от handoff (`brand-b2b-confirm-order`)',
        'Amend approve/reject (`brand-b2b-amend-pending-panel`)',
        'PG lines table',
        'RU статусы',
        'e2e brand-b2b-factory-queue-link',
        'Panel + context strip (`brand-co-detail-panel`, `brand-co-detail-context-strip`)',
        'Shop disclosure preview strip (core-21/29/39)',
        'core-39 clean PG detail smoke',
        'core-44: disclosure → shop tracking на B2B-\\d+',
        'Order detail chat → ?pillar&section + auto-thread (core-46)',
        'Nav dedup: footer cross-links удалены',
        'brand-order-comms golden path strip + registry SoT (`brand-order-comms-golden-registry-link`)',
        'Досье до handoff (`brand-co-detail-dossier-card`)',
        'Production noise скрыт без `?pillar=order_production`',
        'core-51 prebook badge e2e (conditional seed)',
        'Retail onboarding strip на detail tab (`brand-co-registry-retail-onboarding-strip`)',
        'Golden path shop matrix + checkout (`brand-order-comms-golden-shop-matrix-link`, `brand-order-comms-golden-checkout-link`)',
        'Comms workspace detail: slim summary + registry SoT (`brand-order-comms-detail-panel`, без дубля chain/PO/lines)',
        'Brand co-approve margin PG session (`brand-co-collaborative-margin-approve-strip`, core-60)',
        'Collaborative read-only shop session link (`brand-co-collaborative-readonly-link`, wave VI)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('brand', 'collection_order', 'brand-co-detail', d),
    },
    {
      id: 'brand-co-retailers',
      label: 'Сеть ритейлеров',
      order: 3,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'Партнёры B2B — PG tier + multi-buyer + greenfield onboarding strip.',
      good: [
        'Retailers core path',
        'Panel + context strip (`brand-co-retailers-panel`)',
        'Greenfield onboarding strip CRM→showroom→matrix→checkout (`brand-co-registry-retail-onboarding-strip`)',
        'CRM segments + pricelist assign (`brand-co-retailers-crm-*-link`)',
        'Фильтр заказов через `brandB2bOrdersRegistryHref({ partner })`',
        'CTA «Заказы» + «Витрина» (`brand-co-retailers-showroom-link-*`)',
        'Карточка (`brand-co-retailer-detail-panel`, context strip)',
        'PG tier badge (`retailer-tier-badge-*`, data-tier-source=pg, core-47)',
        'Tier из order.tier + volume (`/api/brand/retailers/b2b-orders-summary`)',
        'Multi-buyer discovery из PG orders (не только shop1 preset)',
        'displayNameRu из PG summary + shopCoreBuyerLabelRu (`retailer-display-name-*`, core-52)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('brand', 'collection_order', 'brand-co-retailers', d),
    },
    {
      id: 'brand-co-chain',
      label: 'Этапы цепочки · заказ',
      order: 4,
      staticScore: 7.2,
      liveScore: 7.3,
      summary: 'shop_sent / brand_confirmed — мост к производству.',
      good: [
        'chain-status API',
        'CollectionOrderPillarCard steps (`brand-co-chain-hub-steps`)',
        'Inline confirm + handoff buttons (`brand-b2b-confirm-order`, `brand-b2b-confirm-production-handoff`)',
        'Ритейлеры peer (`brand-co-chain-retailers-link`)',
        'Карточка заказа: `brand-co-chain-card` + context strip',
        'Шаги shop_sent/brand_confirmed без production noise',
        'Два CTA: confirm-order → handoff',
        'SLA бейдж «Ожидает подтверждения»',
        'CTA передача после confirm (`collection-order-handoff-link`)',
        'SSE/poll (`brand-co-chain-sse-live-badge`)',
        'Inline «Полная цепочка» в context strip (`brand-co-chain-full-link`)',
        'Системное сообщение в чат при checkout',
        'Shop matrix + checkout + CRM peers в context strip (`brand-co-chain-shop-matrix-link`, `brand-co-chain-crm-pricelist-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('brand', 'collection_order', 'brand-co-chain', d),
    },
    {
      id: 'brand-co-cabinet',
      label: 'Кабинет · приём заказов',
      order: 5,
      staticScore: 6.9,
      liveScore: 7,
      summary: 'Pillar card + CTA на реестр/заказ + PG partner count.',
      good: [
        'CollectionOrderPillarCard brand',
        'CommsNotificationCenterStrip compact (`brand-co-cabinet-panel`)',
        'Panel + CTA groups (`brand-co-cabinet-panel`, `cta-orders`/`cta-peer`)',
        'PG partner count badge (`brand-co-cabinet-partner-count`, core-47)',
        'Сводка qty и сумма заказа',
        'Handoff + SLA + hub steps',
        'e2e collection-order-qty-summary + retailers link',
        'Shop peer picker на checkout (`shop-co-checkout-buyer-picker`, `shop-b2b-buyer-switcher`)',
        'Cross-role checkout deep-link shop1/shop2 (`brand-co-cabinet-checkout-*-link`)',
        'Multi-buyer registry filter (`brand-co-cabinet-partner-filter`, partner links)',
        'Compact retail onboarding strip CRM→checkout (`brand-co-registry-retail-onboarding-strip`)',
        'PG partner badge on cabinet (`brand-co-cabinet-pg-partner-badge`, wave VR core-161)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('brand', 'collection_order', 'brand-co-cabinet', d),
    },
    {
      id: 'brand-co-wssi-plan',
      label: 'WSSI · OTB → shop buy',
      order: 6,
      staticScore: 7.8,
      liveScore: 7.9,
      summary: 'OTB plan-sync × shop replenishment rules deduped (~8.0 после wave XV).',
      good: [
        'brand-wssi-plan workspace (otb/mix/capacity tabs)',
        'Golden path strip (`brand-wssi-golden-path-strip`)',
        'PG OTB ledger API + editable target % + sync catalog',
        'Shop matrix + showroom + checkout cross-links из golden path',
        'CO spine peer CRM/registry/handoff/tracking (`brand-co-wssi-co-peer-strip`)',
        'OTB plan-sync strip × shop replenishment rules (`brand-co-otb-replenishment-sync-strip`, `brand-co-otb-plan-sync-badge`, wave XV)',
        'Wave XV: OTB plan-sync GET PG × replenishment rules (`/api/brand/b2b/otb/plan-sync`, core-211)',
        'Wave XV: mix tab hides dup replenishment peer links (dedupe OTB strip on pcf=mix)',
        'Wave XV: replenishment-sync legacy GET carry + rules storageMode honesty',
        'Capacity → W2 supply + production ops (без дубля showroom)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.assortmentMixPlanner}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-co-crm-segmentation',
      label: 'CRM · сегменты → showroom',
      order: 7,
      staticScore: 7.8,
      liveScore: 7.9,
      summary: 'PG segments + auto linesheet visibility (~8.0 после wave XB).',
      good: [
        'brand-crm-segmentation workspace',
        'Golden path strip (`brand-crm-golden-path-strip`)',
        'PG segments fetch + PATCH net terms / first-order discount',
        'Segment reorder PATCH displayOrder (`brand-crm-segment-reorder-*`)',
        'Pricelist/showroom panels trimmed (3 CTA max)',
        'Wave XB: linesheet-visibility GET PG buyer_segments (core-191)',
        'Wave XB: auto linesheet summary badge RU (`brand-co-crm-linesheet-visibility-summary-badge`)',
        'Wave XB: shop showroom cross-link per segment (`brand-co-crm-linesheet-visibility-shop-showroom-link`)',
        'PG buyer_segments auto linesheet visibility strip (`brand-co-crm-linesheet-visibility-strip`, wave XB shop showroom cross-link)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${LEGACY_ROUTES.brand.customerGroups}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-co-agent-rep',
      label: 'Agent rep · brand oversight',
      order: 8,
      staticScore: 7.2,
      liveScore: 7.3,
      summary: 'Persisted commission ledger + territory map ↔ CRM segments ↔ shop portal.',
      good: [
        'brand-agent-rep workspace',
        'Golden path strip (`brand-agent-rep-golden-path-strip`)',
        'PG/file commission ledger seed (no demo_stub fallback)',
        'Shop portal/commission cross-links',
        'Territory peer strip rep×CRM regions (`brand-agent-rep-territory-peer-strip`)',
        'Commission dispute POST+GET (`/api/brand/b2b/commissions/dispute`, wave VI / WX PG stub)',
        'Read-only shop portal RU strip + dispute (`brand-agent-rep-shop-portal-readonly-ru-strip`, `brand-agent-rep-commission-dispute-strip`)',
        'Shop rep payout peer cross-link (`brand-agent-rep-shop-rep-payout-peer-link`, wave WS)',
      ],
      bad: [],
      fix: [],
      resolveHref: () => `${ROUTES.brand.distributor.commissions}`,
    },
    {
      id: 'brand-co-pricelist',
      label: 'Price lists · tier sync',
      order: 9,
      staticScore: 7.2,
      liveScore: 7.3,
      summary: 'Versions/tiers/shop-sync + golden path → matrix → CRM → checkout.',
      good: [
        'brand-pricelist workspace',
        'Golden path strip (`brand-pricelist-golden-path-strip`)',
        'PG pricelist versions API + editable multiplier + sync',
        'Publish → tier sync push (`brand-pricelist-publish-*`, POST /api/brand/b2b/pricelist/publish)',
        'PG tier sync push (`brand-pricelist-shop-sync-panel`)',
        'Group filter + versions table',
        'Version diff UI (`brand-pricelist-version-diff-strip`)',
        'Tier sync honesty on publish (`brand-pricelist-tier-sync-honesty-strip`, wave VR / TK verify)',
        'Checkout step (`brand-pricelist-golden-checkout-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${LEGACY_ROUTES.brand.priceLists}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-co-pack-rules',
      label: 'Pack rules · MOQ',
      order: 10,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'Rules/curve/shop-prepack + PG case-pack honesty → matrix apply.',
      good: [
        'brand-pack-rules workspace',
        'Golden path strip (`brand-pack-rules-golden-path-strip`)',
        'PG pack rules API + editable MOQ/case pack + sync',
        'Curve + shop prepack cross-links',
        'Prepack matrix honesty strip (`brand-pack-rules-prepack-matrix-honesty-strip`)',
        'Checkout step (`brand-pack-rules-golden-checkout-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.packRules}?collection=${encodeURIComponent(d.collectionId)}`,
    },
    {
      id: 'brand-co-landed-margin',
      label: 'Landed margin · brand',
      order: 11,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'Simulator/pricelist/shop-rollup + tier sync mirror ↔ shop margin.',
      good: [
        'brand-landed-margin workspace',
        'Golden path strip (`brand-landed-margin-golden-path-strip`)',
        'PG margin feed · simulator defaults + shop rollup preview',
        'Bridge panels shop rollup/pricelist',
        'Tier sync mirror strip (`brand-landed-margin-tier-sync-mirror-strip`)',
        'Publish pricelist auto-push tier → shop matrix',
        'Checkout step (`brand-landed-margin-golden-checkout-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.marginSimulator}?collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
  order_production: [
    {
      id: 'brand-op-handoff',
      label: 'Передача в производство',
      order: 1,
      staticScore: 7.4,
      liveScore: 7.5,
      summary: 'confirm-order → handoff → ERP retry на clean PG (core-34 ✓).',
      good: [
        'Handoff API',
        'e2e core-02/03',
        'Retry UI (`brand-b2b-handoff-retry`) + error alert',
        'ERP retry UI (`brand-b2b-erp-retry`) + POST API',
        'core-34: clean PG ERP retry после handoff',
        'Кнопка gated на handedOff, не status',
        'Context strip cross-role (`brand-order-handoff-context-strip`)',
        'SSE/poll badge в chain card (`brand-op-chain-*`)',
        'Strip CTA канон (`brand-op-handoff-factory-queue-link`, `brand-op-handoff-prod-orders-link`)',
        'CTA «Передача» в реестре (`brand-b2b-order-handoff-*`)',
        'Bulk handoff (`brand-b2b-bulk-handoff`, `brand-b2b-order-select-*`)',
        'Deep link `brandB2bOrderHandoffContextHref` + awaiting registry',
        'Production ops handoff tab: manufacturer QC + factory-ack cross-links (`brand-production-handoff-*`)',
        'QC gate tab: chain SSE/poll + handoff/mfr QC cross-links (`brand-production-qc-chain-*`, `brand-qc-gate-*`)',
        'QC in-tab POST record (`brand-qc-gate-inline-record-*`, PG refetch)',
        'Mfr QC in-tab mirror (`mfr-qc-gate-inline-record-*`)',
        'Chain SSE/poll badge на handoff tab (`brand-production-handoff-chain-*`)',
        'Golden path strip (`brand-production-ops-golden-path-strip`)',
        'Production ops state PG (`/api/brand/production/operations-state`, `brand-production-ops-storage-pg`)',
        'Wave SL: core без localStorage fallback (`brand-production-ops-storage-unavailable`, auto-persist PG)',
        'Очередь цеха с order context (`brand-b2b-factory-queue-link`)',
        'PO → queue link в реестре (`brand-b2b-order-po-link-*`)',
        'ERP auto-retry backoff после factory bulk ack (erpNextRetryAt + queue poll)',
        'Wave TG: ERP burst auto-retry 3× после handoff/ack failure (`runWorkshop2FactoryHandoffErpAutoRetries` burst)',
        'Wave TQ: bulk handoff Idempotency-Key (`buildWorkshop2BulkHandoffIdempotencyKey`, `brand-b2b-bulk-handoff`)',
        'Wave TQ: QC gate blocks handoff badge (`brand-production-handoff-qc-block-badge`)',
        'Inventory + order comms peer strip (`brand-op-handoff-inventory-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandB2bOrderHandoffContextHref(d.demoOrderId),
    },
    {
      id: 'brand-op-chain',
      label: 'Статус цепочки · PO',
      order: 2,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: '5 шагов chain-status; SoT strip → dossier anchor.',
      good: [
        'B2bOrderChainStatusCard (`brand-order-chain-status-card`)',
        'brand-op-chain-sse/poll badge',
        'brand-order-chain-context-strip + poll badge',
        'Cross-links чат/календарь/трекинг магазина',
        'OrderProductionPillarCard (`brand-op-chain-steps`)',
        'PO id badge + materials step badges',
        'ERP retry (`brand-b2b-erp-retry`, core-34)',
        'SSE badge только на chain card (dedup strip)',
        'SSE dedup strip на registry/cabinet (`brand-op-*-sse-dedup-strip`, `brand-op-chain-sse-dedup-badge`, Wave VQ)',
        'Dossier SoT strip (`brand-op-chain-dossier-sot-strip`, anchor #production-dossier)',
        'CO spine peer strip matrix/checkout/tracking/mfr (`brand-op-chain-co-spine-peer-strip`)',
        'Materials supplier PATCH strip (`brand-op-chain-materials-supplier-strip`, `brand-op-chain-materials-supplier-link-*`)',
        'Wave XM: po= on supplier PATCH + inventory ledger WMS cross-link (`brand-op-chain-materials-inventory-ledger-link`)',
        'Wave XM: SSE dedup hint on chain card (`brand-op-chain-materials-sse-dedup-hint`, Wave VQ polish)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandB2bOrderChainContextHref(d.demoOrderId),
    },
    {
      id: 'brand-op-dossier',
      label: 'Досье · W2 бренда',
      order: 3,
      staticScore: 6.9,
      liveScore: 7,
      summary: 'ТЗ на карточке заказа + deep-link W2 + production peers.',
      good: [
        'Карточка ТЗ на order detail (`brand-order-w2-dossier-card`, `#production-dossier`)',
        'W2 deep-link material (`brandW2ProductionTzHref`, `brand-op-w2-dossier-link`)',
        'Peer досье цеха после handoff (`brand-order-factory-dossier-link`)',
        'Бейдж фиксации + diff (`brand-order-w2-dossier-locked-badge`, `brand-op-dossier-locked-badge` live PG, `*-diff-*`)',
        'Side-by-side dossier diff на OP dossier tab (`brand-op-dossier-factory-diff-wrap`, Wave UN/VQ)',
        'cut_ticket PG verify badge (`brand-op-cut-ticket-pg-verify-badge`, Wave UG/VQ)',
        'Production peer strip: chain/handoff/QC/cut-ticket/mfr QC/shop tracking (`brand-op-dossier-production-peer-strip`)',
        'Навигация handoff/chain — в chain card',
        'Core dossier strip без чата — comms pillar',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandB2bOrderDossierContextHref(d.demoOrderId),
    },
    {
      id: 'brand-op-registry',
      label: 'Реестр · контекст заказов',
      order: 4,
      staticScore: 6.9,
      liveScore: 7,
      summary: 'Реестр OP + production peer strip (QC/handoff/tracking).',
      good: [
        'Фильтры handoff/in_production',
        'Context strip: трекинг (без чата в core)',
        'OP registry production peers (`brand-op-registry-production-peer-strip`)',
        'SSE dedup strip registry (`brand-op-registry-sse-dedup-strip`, Wave VQ)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandB2bOrdersProductionRegistryHref(d.demoOrderId),
    },
    {
      id: 'brand-op-cabinet',
      label: 'Кабинет · заказ→производство',
      order: 5,
      staticScore: 6.9,
      liveScore: 7,
      summary: 'Hub insight: chain steps + BOM + peer CTA; clean PG PO badge (core-49).',
      good: [
        'Panel (`brand-op-cabinet-panel`)',
        'SoT strip → order detail + registry (`brand-op-cabinet-sot-strip`)',
        'CTA wrapper → spine peer handoff/QC/tracking/mfr/registry (`brand-op-cabinet-spine-peer-strip`)',
        'SSE/poll badge (`brand-op-cabinet-*-badge`)',
        'SSE dedup strip cabinet (`brand-op-cabinet-sse-dedup-strip`, Wave VQ)',
        'Registry с `?order=` · materials step link',
        'PO badge → prod-orders (`brand-op-po-id-badge`)',
        'Clean PG chain steps (core-49)',
        'WMS/materials badges + BOM count badge',
        'compact-only hub',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandCoreOrderProductionCabinetHref(d.collectionId),
    },
    {
      id: 'brand-op-inventory-ops',
      label: 'Inventory · brand ledger',
      order: 6,
      staticScore: 7.2,
      liveScore: 7.3,
      summary:
        'PG ledger strip on overview/network + CO spine peers (handoff/tracking/replenishment).',
      good: [
        'brand-inventory-ops workspace',
        'Golden path strip (`brand-inventory-ops-golden-path-strip`)',
        'BrandOpInventoryLedgerStrip + GET inventory/reserve (`brand-op-inventory-ledger-wms-reserve-badge`)',
        'WMS API cross-links (`brand-op-inventory-ledger-wms-reserve-api-link`, `brand-op-inventory-ledger-wms-balances-api-link`)',
        'Supplier PATCH deep-link (`brand-op-inventory-ledger-supplier-patch-link`)',
        'PlatformCoreInventoryLedgerStrip (`brand-op-inventory-ledger-ledger`)',
        'CO spine peer handoff/tracking/replenishment/registry (`brand-op-inventory-co-peer-strip`)',
        'materials_supplied → BrandOpChainMaterialsSupplierStrip (`brand-op-chain-materials-supplier-link-patch`)',
        'Wave XM: chain card → inventory ledger WMS reserve (`brand-op-chain-materials-inventory-ledger-link`)',
        'core-202 e2e wave XM supplier link',
        'Shop reconcile/tracking cross-links',
        'Products matrix + legacy UI entry',
        'core-144 e2e wave S3 inventory ledger',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.inventory}?${PILLAR_CAPABILITY_FEATURE_PARAM}=overview&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
  comms: [
    {
      id: 'brand-cm-order-chat',
      label: 'Чат · оптовый заказ',
      order: 1,
      staticScore: 7.7,
      liveScore: 7.8,
      summary: 'Контекстный тред B2B — PG message templates S1 final (~8.0 после wave XZ).',
      good: [
        'contextType b2b_order',
        'slim messages core',
        'Entity banner',
        'Чат из реестра заказов',
        'Превью треда в реестре',
        'Universal inbox: все заказы PG в sidebar',
        'Wave TT: PG unread count per order (`*-universal-inbox-order-unread-*`, unread-summary + pgEventUnread)',
        'Wave XO: universal inbox live PG badge per order + tracking→calendar pcTask deep-link (core-204)',
        'B2B шаблоны (ship-window, qty-confirm) в slimCore',
        'core-14 e2e templates',
        'PG unread в ChatList + registry SSE bump',
        'comms-pillar-unread-badge на inbox',
        'brand-cm-order-context-strip',
        'brand-cm-order-chat-link в hub',
        'Server read receipts (PG workshop2_contextual_read_state)',
        'Read-state actor из session uid',
        'ContextualChatThread SSE live (`contextual-chat-sse-live-badge`) + poll fallback',
        'Сохранение своих шаблонов (`platform-core-b2b-message-template-save-draft`, localStorage)',
        'Order workspace notification bar + registry stream health (`brand-cm-order-registry-stream-health-strip`)',
        'Order context peer strip CO+monetization (`brand-cm-order-context-strip`, `brand-cm-order-shop-checkout-link`)',
        'Order-comms workspace chat/handoff tabs: context strip без дубля registry facts',
        'Wave XZ: B2B message templates PG POST/GET (`/api/platform-core/b2b/message-templates`, core-215)',
        'Wave XZ: templates storage badge PG/local (`platform-core-b2b-message-templates-storage-pg`)',
        'Wave XZ: built-in ship-window template chip (`platform-core-b2b-message-template-ship-window`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandMessagesB2bOrderContextHref(d.demoOrderId),
    },
    {
      id: 'brand-cm-article-chat',
      label: 'Чат · артикул W2',
      order: 2,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'Article context + investor/QC/order comms peers (W2 drawer SSE).',
      good: [
        'workshop2_article context',
        'brand-dossier-article-chat-link',
        'brand-cm-article-context-strip',
        'brand-cm-article-messages-link в W2 drawer',
        'Экспорт ТЗ рядом с чатом (`brand-w2-tz-export-btn`)',
        'Прикрепление ZIP ТЗ в тред (`brand-w2-tz-attach-chat-btn`)',
        'Ссылка на вложение в contextual chat (`contextual-chat-attachment-link`)',
        'ContextualChatThread SSE live на article context',
        'W2 drawer: usePlatformCoreCommsInboxPoll + poll badge (`workshop2-article-chat-poll-badge`)',
        'Investor summary + production QC + order comms peers (`brand-cm-article-investor-summary-link`, `brand-cm-article-production-ops-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandMessagesWorkshop2ArticleContextHref(d.collectionId, d.demoArticleId),
    },
    {
      id: 'brand-cm-calendar',
      label: 'Календарь · заказ',
      order: 3,
      staticScore: 6.9,
      liveScore: 7,
      summary: 'Слоты отгрузки, события chain — investor «план поставок» + CO spine peers.',
      good: [
        'Calendar B2B context',
        'Canonical URLs',
        'targetChatId в calendar-events API',
        'EventDialog «Чат» при клике на B2B-событие',
        'platform-core-comms-cross-nav + brand-cm-order-context-strip',
        'PG user-task create + refetch (core-23)',
        'GET user-task list strip (`brand-cm-calendar-user-tasks-strip`)',
        'Task deep-link + chat CTA (`brand-cm-calendar-user-tasks-task-*`)',
        'pcTask URL focus scroll (`brand-cm-calendar-user-tasks-strip` + `pcTask=` deep link)',
        'Task strip refetch после create (`reloadNonce`)',
        'Context peer handoff/registry/shop tracking/CRM (`brand-cm-calendar-context-peer-strip`)',
        'brand-cm-calendar-events-badge',
        'Dev tasks kanban mini-panel (`brand-dev-tasks-kanban-panel`, GET/POST `/api/brand/tasks`)',
        'core-151 wave VF calendar kanban + cabinet dashboard strips e2e',
        'Wave XF: calendar kanban strip GET/POST UI (`brand-dev-tasks-kanban-calendar-strip`, core-195)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandCalendarB2bOrderContextHref(d.demoOrderId),
    },
    {
      id: 'brand-cm-notes',
      label: 'Заметки · inbox',
      order: 3.5,
      staticScore: 7.2,
      liveScore: 7.2,
      summary:
        'Единый inbox заметок столпа «Связь»: назначение, срок, уведомление, вложение, статус.',
      good: [
        'CommsPlatformNotesPanel (`brand-cm-notes-panel`)',
        'createPlatformCoreNote + local inbox store',
        'Статусы принято / отменена (`brand-cm-notes-accept-*`, `brand-cm-notes-cancel-*`)',
        'Tab «Заметки» в CommsPillarCard (`brand-cm-notes-link`)',
        'SidebarWidget скрыт в Platform Core',
      ],
      bad: [],
      fix: ['PG repository для заметок cross-pillar'],
      resolveHref: (d) => platformCoreCommsNotesHref('brand', d),
    },
    {
      id: 'brand-cm-banner',
      label: 'Контекст-баннер · URL',
      order: 4,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'Dedupe баннеров + order workspace section-groups/CO spine peers.',
      good: [
        'CommunicationsEntityContextBanner',
        'brand-cm-banner testid',
        'Core B2B msg/cal hrefs (не syntha overlay)',
        'Policy strip off при URL и workspace',
        'core-14 banner dedupe e2e (4 роли)',
        'core-13 cross-nav',
        'Production-context banner → W2 article chat + dossier',
        'Registry SSE refetch unread',
        'Article workspace SSE inbox bump (`workshop2-article-chat-button` + inbox-stream)',
        'Order context registry stream on workspace bar (`brand-cm-order-registry-stream-health-strip`)',
        'Section-groups spine peer on order messages (`brand-cm-section-groups-spine-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => brandMessagesB2bOrderContextHref(d.demoOrderId),
    },
    {
      id: 'brand-cm-section-groups',
      label: 'Группы по разделам',
      order: 5,
      staticScore: 7.4,
      liveScore: 7.5,
      summary: 'Section-groups: clean PG four-role deep-link + spine peer on order workspace.',
      good: [
        'brand-cm-section-groups-picker UI',
        'Deep-link ?pillar=&section= (core-21 e2e)',
        'Clean PG B2B-\\d+ deep-link 4 roles (core-40)',
        'Section contextual auto-thread (core-30)',
        'Order detail / tracking chat → section deep-link (core-46)',
        'Registry SSE bump на contextual message',
        'comms-pillar-sse-live-badge на hub (core-35)',
        'Unread badge на section-group chip',
        'Section visit cursor local + POST section-read-state',
        'PG mirror в workshop2_contextual_read_state (b2b_order_section)',
        'PG-primary skip file mirror',
        'core-52 contextual POST→GET PG round-trip',
        'Audit guard comms-canon',
        'Исключение meta-section из picker',
        'Calendar user-task POST + fail-closed hint (`brand-cm-calendar-pg-required-hint`)',
        'Spine peer registry/handoff/tracking/pricelist (`brand-cm-section-groups-spine-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.coreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}&section=brand-co-registry`,
    },
    {
      id: 'brand-cm-cabinet',
      label: 'Кабинет · связь',
      order: 6,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'CommsPillarCard, PG unread + clean PG thread strip (core-40).',
      good: [
        'brand-cm-cabinet-po-inbox из реестра B2B',
        'CommsPillarCard compact-only',
        'Registry stream health + refresh (`brand-cm-cabinet-registry-stream-health-strip`)',
        'comms-pillar-unread-badge + SSE live (core-35)',
        'Clean PG order chat link (core-20/40)',
        'brand-cm-cabinet-thread-search hub',
        'brand-cm-thread-search workspace',
        'brand-cm-order/article/calendar-link hub (волны 68–70)',
        'CTA «Все треды» + unread на inbox',
        'Entity threads tab: inbox SSE/poll badge (`brand-comms-entity-threads-sse-*`)',
        'brand-comms-workspace golden path (`brand-comms-workspace-golden-path-strip`)',
        'Cabinet spine peer registry→checkout→CRM (`brand-cm-cabinet-spine-peer-strip`)',
        'Poll fallback if SSE down (`brand-cm-cabinet-poll-badge`, `comms-pillar-sse-live-badge`)',
        'S4 PG notification_events push (`/api/platform-core/notification-events`, `brand-cm-notification-pg-events-list`)',
        'PG unread-summary + prefs postgres (`/api/platform-core/comms/unread-summary`, fail-closed LS, `brand-cm-notification-pref-chain-push`, `usePlatformCoreChainStatusPushEnabled`)',
        'Wave VK S2: CommsPillarCard chain badge gated by PG `chainStatusPush` + PUT hub bump',
        'Wave UP: entity-thread-templates PG (`/api/platform-core/comms/entity-thread-templates`)',
        'Wave UP: POST calendar-events chain step + contextual-thread order/article',
        'Wave UP: compact notification strip без placeholder push-events',
        'Wave XZ: entity-thread-templates PG round-trip + storageModeLabelRu (core-215)',
        'Wave XZ: B2B + entity templates S1 final — fail-closed LS in core comms hub',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${ROUTES.brand.coreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
};
