import { ROUTES as EXTENDED_ROUTES } from '@/lib/platform-core-extended-routes';
/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreChainRoleId, CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import { waveZaAdrBacklogForSection } from '@/lib/platform/wave-za-adr-readonly-backlog';
import type { SectionAuditTemplate } from './types';

export const EMPTY_SECTION_AUDIT: Partial<
  Record<CoreChainRoleId, Partial<Record<CoreHubPillarId, readonly SectionAuditTemplate[]>>>
> = {
  shop: {
    development: [
      {
        id: 'shop-empty-dev-status',
        label: 'Прогресс разработки · read-only',
        order: 1,
        staticScore: 7.2,
        liveScore: 7.3,
        summary:
          'ShopDevelopmentBridge: шаги development-status + published badge + greenfield CRM.',
        good: [
          'usePillarSnapshot development BFF',
          'shop-development-bridge + core-31 e2e',
          'Nav peer pillar «контекст»',
          'Greenfield buyer CRM strip PG segment (`shop-development-bridge-greenfield-crm-strip`)',
          'Wave AX: CRM tier/net terms + pricelist spine (`shop-dev-bridge-crm-brand-pricelist-link`)',
          'PG assortment wishlist (`/api/shop/b2b/development/assortment-wishlist`, `shop-dev-bridge-wishlist-storage-pg`)',
          'Request sample → brand notification (`shop-dev-bridge-request-sample-*`)',
          'Wave SV: compact peer strip (`shop-dev-bridge-peer-strip`) + fail-closed wishlist client',
          'Wave UA: sample request in dossier preview dialog (`shop-dev-bridge-request-sample-preview-btn`)',
          'Wave WV: dedupe card CTAs → peer strip; wishlist PUT/remove PG polish',
          'Wave VZ: read-only bridge закрыт — preview + wishlist PG peers (core-163)',
          'Wave ZA: read-only empty cell — ADR-003 + core-242 e2e (no W2 editor/checkout)',
        ],
        bad: [],
        fix: [],
        adrBacklog: waveZaAdrBacklogForSection('shop-empty-dev-status'),
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-empty-dev-brand-w2',
        label: 'Техпак бренда',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Peer CTA → W2 hub + inline dossier preview dialog.',
        good: [
          'shop-development-bridge-brand-w2',
          'Prefetch W2 на hover',
          'Inline preview dialog (`shop-development-bridge-dossier-preview-dialog`)',
          'Preview steps + W2/checkout CTA в footer',
          'Wave AX: dossier preview + W2 golden path wired',
          'Wave UA: RU-only copy in preview dialog (без Read-only EN)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.brand.productionWorkshop2}?${WORKSHOP2_COL_PARAM}=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-empty-dev-showroom',
        label: 'Витрина · коллекция',
        order: 3,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'Showroom + matrix/checkout CTA когда readyForBuyers.',
        good: [
          'shop-development-bridge-showroom',
          'readyForBuyers badge',
          'Matrix + checkout peers при publish (`shop-development-bridge-matrix`, `shop-development-bridge-checkout`)',
          'Greenfield CRM checkout link (`shop-dev-bridge-crm-checkout-link`)',
          'Wave AX: greenfield pricelist + landed margin peers',
          'Wave VZ: publish dependency — честный readyForBuyers badge + matrix/checkout peers (core-163)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopShowroomHrefForDemo(d),
      },
      {
        id: 'shop-empty-dev-cross',
        label: 'Cross-role · peer роли',
        order: 4,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'RolePillarCrossRoleLinks + greenfield CRM monetization spine.',
        good: [
          'embedCrossRole в PlatformCoreEmptyCellPanels',
          'getCrossRolePeerDemoHref merged PG orderId',
          'Greenfield CRM strip showroom/matrix/partners/checkout (`shop-development-bridge-greenfield-crm-strip`)',
          'Wave AX: embedCrossRole + full monetization golden path',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
  },
  manufacturer: {
    sample_collection: [
      {
        id: 'mfr-empty-sc-status',
        label: 'Статус коллекции · PG',
        order: 1,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'ManufacturerSampleCollectionStatus: published/linesheet таблица + spine peers.',
        good: [
          'manufacturer-sample-collection-pg-table',
          'usePillarSnapshot sample_collection BFF',
          'Spine peer shop showroom/matrix + sample queue (`mfr-empty-sc-peer-strip`)',
          'Wave AX: mfr-empty-sc-peer-strip wired in panel',
          'Wave SK: mfr-empty-sc-publish-badge при publish бренда',
          'Wave VS: read-only publish badge + PG table без дубля «Готово для байеров»',
          'Wave ZA: read-only empty cell — ADR-003 + core-242 e2e (publish status panel)',
        ],
        bad: [],
        fix: [],
        adrBacklog: waveZaAdrBacklogForSection('mfr-empty-sc-status'),
        resolveHref: (d) =>
          `${EXTENDED_ROUTES.factory.productionCoreCabinet}?pillar=sample_collection&collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'mfr-empty-sc-brand-linesheet',
        label: 'Linesheet бренда · peer',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Peer CTA → linesheet бренда + shop monetization spine.',
        good: [
          'manufacturer-sample-collection-brand-linesheet',
          'mfr-empty-sc-brand-linesheet-link в spine strip',
          'Wave AX: linesheet link in spine strip',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => brandLinesheetsHrefForDemo(d),
      },
      {
        id: 'mfr-empty-sc-cross',
        label: 'Cross-role · peer роли',
        order: 3,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'RolePillarCrossRoleLinks + shop/brand spine strip.',
        good: [
          'RolePillarCrossRoleLinks compact',
          'mfr-empty-sc-peer-strip shop showroom/matrix',
          'Wave AX: shop showroom/matrix + sample queue spine',
          'Wave VS: ≥4 peer cross-links в mfr-empty-sc-peer-strip (core-162)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${EXTENDED_ROUTES.factory.productionCoreCabinet}?pillar=sample_collection&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    collection_order: [
      {
        id: 'mfr-empty-co-po',
        label: 'Ожидание PO · handoff',
        order: 1,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'ManufacturerPoExpectation: handoff queue + procurement + CO spine peers.',
        good: [
          'manufacturer-po-expectation',
          'usePillarSnapshot collection_order BFF',
          'CO spine brand handoff/tracking/matrix (`mfr-empty-co-peer-strip`)',
          'Wave AX: mfr-empty-co-peer-strip wired in panel',
          'Wave SK: mfr-empty-co-handoff-count-badge из PG queue',
          'Wave VS: handoff count badge read-only (не B2B checkout UI)',
          'Wave ZA: read-only empty cell — ADR-003 + core-242 e2e (handoff count panel)',
        ],
        bad: [],
        fix: [],
        adrBacklog: waveZaAdrBacklogForSection('mfr-empty-co-po'),
        resolveHref: (d) =>
          `${EXTENDED_ROUTES.factory.productionCoreCabinet}?pillar=collection_order&collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'mfr-empty-co-chain',
        label: 'Chain steps · read-only',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Chain steps shop_sent/brand_confirmed + spine cross-links.',
        good: [
          'Poll/SSE refresh',
          'mfr-empty-co-handoff-queue-link + shop tracking в spine strip',
          'Wave AX: handoff queue + shop tracking spine',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => factoryHandoffQueueHrefForDemo(d),
      },
      {
        id: 'mfr-empty-co-cross',
        label: 'Cross-role · peer роли',
        order: 3,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Peer CTA brand/shop collection_order + spine strip.',
        good: [
          'RolePillarCrossRoleLinks compact',
          'mfr-empty-co-peer-strip brand/shop handoff',
          'Wave AX: brand handoff + shop matrix peers',
          'Wave VS: ≥4 peer cross-links в mfr-empty-co-peer-strip (core-162)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${EXTENDED_ROUTES.factory.productionCoreCabinet}?pillar=collection_order&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
  },
  supplier: {
    sample_collection: [
      {
        id: 'sup-empty-sc-bom',
        label: 'BOM образца · peer',
        order: 1,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'SupplierBomPreview: nav peer + dev cabinet spine strip.',
        good: [
          'supplier-bom-preview-mini',
          'usePillarSnapshot BOM',
          'Brand BOM peer (`sup-dev-bom-brand-peer-link`)',
          'Dev cabinet spine BOM/RFQ/CRM (`sup-dev-cabinet-spine-peer-strip`)',
          'Wave AX: sup-dev-cabinet-spine-peer-strip full + compact',
          'Wave UA: linesheet PG notify strip (`sup-empty-sc-linesheet-notify-strip`, `notifySupplierLinesheetBomPreview`)',
          'Wave WW: supplier-empty-wave-ww module + core-186 e2e',
          'Wave UA: minimalChrome empty panel — без лишних peer strips',
          'Wave ZA: read-only empty cell — ADR-003 + core-242 e2e (BOM preview mini)',
        ],
        bad: [],
        fix: [],
        adrBacklog: waveZaAdrBacklogForSection('sup-empty-sc-bom'),
        resolveHref: (d) =>
          `${EXTENDED_ROUTES.factory.supplierCoreCabinet}?pillar=sample_collection&collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'sup-empty-sc-cross',
        label: 'Cross-role · peer роли',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Nav peer pillar sample_collection + dev spine strip.',
        good: [
          'RolePillarCrossRoleLinks compact',
          'sup-dev-cabinet-spine-peer-strip на empty panel',
          'Wave AX: dev cabinet spine on empty BOM panel',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${EXTENDED_ROUTES.factory.supplierCoreCabinet}?pillar=sample_collection&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    collection_order: [
      {
        id: 'sup-empty-co-forecast',
        label: 'Прогноз закупок · peer',
        order: 1,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'SupplierCollectionOrderForecast: BFF + mfr handoff peer + CO spine.',
        good: [
          'supplier-collection-order-forecast',
          'usePillarSnapshot BFF',
          'Replenishment ATP back-link (`supplier-forecast-replenishment-atp-link`)',
          'Manufacturer handoff SSE peer (`supplier-manufacturer-handoff-peer-strip`)',
          'CO spine mfr/procurement/forecast/tracking (`sup-empty-co-peer-strip`)',
          'Wave AX: sup-empty-co-peer-strip + mfr handoff SSE',
          'Wave UA: expected PO date read-only (`sup-empty-co-expected-po-date-strip`, handoffAt PG)',
          'Wave WW: `expectedHandoffAt` in supplierCollectionOrderForecast snapshot',
          'Wave ZA: read-only empty cell — ADR-003 + core-242 e2e (forecast panel)',
        ],
        bad: [],
        fix: [],
        adrBacklog: waveZaAdrBacklogForSection('sup-empty-co-forecast'),
        resolveHref: (d) =>
          `${EXTENDED_ROUTES.factory.supplierCoreCabinet}?pillar=collection_order&collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'sup-empty-co-cross',
        label: 'Cross-role · peer роли',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Handoff queue + manufacturer peer + CO spine context.',
        good: [
          'RolePillarCrossRoleLinks compact',
          'sup-empty-co-peer-strip + supplier-manufacturer-handoff-peer-strip',
          'Wave AX: procurement/forecast/tracking spine strip',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${EXTENDED_ROUTES.factory.supplierCoreCabinet}?pillar=collection_order&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
  },
};
