/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
  EXTENDED_ROUTES,
  LEGACY_ROUTES,
} from '@/lib/platform-core-readiness-routes';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import { platformCoreCabinetSectionHref } from '@/lib/platform-core-cabinet-workspace';
import type { SectionAuditTemplate } from './types';

export const MANUFACTURER_SECTION_AUDIT: Partial<
  Record<CoreHubPillarId, readonly SectionAuditTemplate[]>
> = {
  development: [
    {
      id: 'mfr-dev-dossier',
      label: 'Досье · read-only',
      order: 1,
      staticScore: 7.3,
      liveScore: 7.4,
      summary: 'ТЗ и BOM из PG — основа выпуска.',
      good: [
        'mfr-dev-dossier-panel + context strip (brand W2/queue/materials/cabinet)',
        'Export SKU strip',
        'PG dossier API read-only',
        'Article chat (`mfr-dev-dossier-article-chat-link`)',
        'core-52 export SKU meta + print btn e2e',
        'Comment-only peer strip → chat template (`mfr-dev-dossier-comment-peer-strip`)',
        'Production spine + attach TZ (`mfr-dev-dossier-production-spine-peer-strip`, `mfr-cm-article-attach-tz-peer-strip`)',
        'Sample photo DAM attach POST (`mfr-dev-sample-photo-dam-stub-strip`, wave VL `/samples/attach-photo`)',
        'Wave VZ: read-only dossier + comment peer strip закрыт (`mfr-dev-dossier-comment-peer-strip`, core-163)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        factoryProductionDossierHref(d.demoArticleId, { collectionId: d.collectionId }),
    },
    {
      id: 'mfr-dev-sample-queue',
      label: 'Очередь образцов',
      order: 2,
      staticScore: 7.8,
      liveScore: 7.9,
      summary: 'Sample queue PG — factory PATCH + hash-scroll (~8.0 после wave XC).',
      good: [
        'Sample queue card',
        'SAMPLE-DEMO в e2e',
        'Priority sort overdue→due',
        '#sample-queue hash-scroll',
        'pillarId development на карточке очереди',
        'Один CTA образцы/ack в mfr-dev-cabinet strip',
        'Dossier peer strip → handoff sample-queue tab (`dossier-sample-queue-handoff-tab-link`)',
        'Handoff/orders/QC spine peer (`mfr-dev-sample-queue-handoff-peer-strip`)',
        'DAM stub attach на очереди (`mfr-dev-sample-photo-dam-stub-strip`, wave UQ)',
        'Wave XC: factory PATCH limited fields (`/api/workshop2/factory/sample-queue/[orderId]`, core-192)',
        'Wave XC: hash-scroll to item + RU poll badge (`mfr-dev-sample-queue-poll-badge`)',
        'Wave XC: development-status mirror bump after PATCH (core-192)',
        'Wave XC: sample state-change webhook journal (`/api/workshop2/samples/state-change-webhook`)',
      ],
      bad: [],
      fix: [],
      resolveHref: () => `${EXTENDED_ROUTES.factory.production}#sample-queue`,
    },
    {
      id: 'mfr-dev-status',
      label: 'Статус коллекции · PG',
      order: 3,
      staticScore: 6.9,
      liveScore: 7,
      summary: 'development-status read + factory-scoped filter strip на cabinet.',
      good: [
        'Read-only steps',
        'Empty panels manufacturer sample_collection',
        'Wave VS: MfrEmptyPublishStatusBadge + MfrEmptyScPeerStrip в SC panel',
        'Wave VS: MfrEmptyHandoffCountBadge + MfrEmptyCoPeerStrip в CO panel (core-162)',
        'Factory scope strip (`mfr-dev-factory-scope-strip`)',
        'Development status SSE/poll на cabinet (`mfr-dev-development-*-badge`)',
        'PG mirror brand development-status (`mfr-dev-development-status-mirror-*`, wave VL/YS)',
        'Wave YS: status peer strip brand dev + sample queue (`mfr-dev-development-status-peer-strip`, core-234)',
        'Wave YS: poll/SSE badge dedupe in operator cabinet (core-234)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        factoryProductionDossierHref(d.demoArticleId, { collectionId: d.collectionId }),
    },
    {
      id: 'mfr-dev-cabinet',
      label: 'Кабинет · досье/образцы',
      order: 4,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'DevelopmentPillarCard manufacturer + factory scope + handoff peers.',
      good: [
        'mfr-dev-cabinet-panel + context strip',
        'ТЗ бренда · досье · образцы',
        'Factory scope strip on hub (`mfr-dev-factory-scope-strip`)',
        'Sample queue handoff spine peer (`mfr-dev-sample-queue-handoff-peer-strip`)',
        'e2e core-01 manufacturer development pillar',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        `${EXTENDED_ROUTES.factory.productionCoreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
    },
  ],
  order_production: [
    {
      id: 'mfr-op-handoff-queue',
      label: 'Очередь передачи',
      order: 1,
      staticScore: 7.2,
      liveScore: 7.3,
      summary: 'Входящие PO после бренда — shop-floor bundle + CO spine peer.',
      good: [
        'Handoff queue PG',
        'e2e core-02',
        'Golden CTA',
        'bulk-acknowledge API + panel (`mfr-op-handoff-queue-panel`)',
        'B2bChainPhaseBadge на строках очереди',
        'RU статусы PO (`factoryHandoffPoStatusLabelRu`)',
        'Registry link + row CTA (`mfr-op-handoff-queue-registry-link`, `mfr-op-handoff-queue-orders-link-*`)',
        'Shop-floor bundle per PG row (`mfr-op-handoff-shop-floor-bundle-*`, core-42)',
        'Poll refresh registry tick + refresh button',
        'ERP alert banner (`mfr-op-handoff-queue-erp-alert`)',
        'Canonical handoff href с order context',
        'Row chat → section auto-thread (`mfr-op-handoff-queue-chat-link-*`, core-48)',
        'Navigate to registry после bulk ack (`factory-handoff-bulk-acknowledge` → `/factory/production/orders?order=`, core-03)',
        'Bulk ERP retry для attention rows (`factory-handoff-bulk-erp-retry`, bulk-retry-erp API)',
        'core-55 clean PG factory ERP retry e2e (handoff + registry)',
        'Factory-ack tab (`manufacturer-handoff-feature-techpack-ack`) → POST handoff/factory-ack',
        'Handoff queue SSE + poll fallback (`mfr-op-handoff-queue-sse-*`)',
        'Golden path strip (`manufacturer-handoff-queue-golden-path-strip`)',
        'QC gate tab chain SSE/poll (`mfr-qc-gate-chain-*`) + brand QC peer link',
        'Registry SoT strip panel vs orders (`mfr-op-handoff-queue-registry-sot-strip`)',
        'Failed PO ERP filter на очереди (`mfr-op-handoff-failed-po-filter`, wave VD)',
        'CO spine peer brand/tracking/prod-orders/techpack/cut-ticket/comms (`mfr-op-handoff-queue-co-spine-peer-strip`)',
        'Wave VZ: bulk-ack vs registry — осознанный дубль; SoT strip (`mfr-op-handoff-queue-registry-sot-strip`, wave VH/VQ)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref(
          'manufacturer',
          'order_production',
          'mfr-op-handoff-queue',
          d
        ),
    },
    {
      id: 'mfr-op-production-orders',
      label: 'Производственные заказы',
      order: 2,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'Реестр серий цеха; clean PG focus row (core-49).',
      good: [
        'production-orders core PG',
        'scroll-to-row + focus-row testid',
        'ERP alert banner + retry CTA',
        'hub link → factoryCoreOrderProductionCabinetHref',
        'Copy: panel=ack, registry=MES/ERP',
        'Bulk accept + MES strip + per-row CTA',
        'Context strip при ?order=',
        'e2e MES FW27 (`core-11`)',
        'Clean PG focus row (`factory-production-orders-focus-row`, core-49)',
        'core-06 EMPTY27 empty-state e2e (no MES SS27)',
        'EMPTY27 честный skip MES в core-06',
        'Bulk ERP retry alert (`factory-production-orders-bulk-erp-retry`, bulk-retry-erp API)',
        'core-55 clean PG ERP alert на focus row (`factory-production-orders-erp-alert`)',
        'Golden path strip orders→handoff→tracking (`manufacturer-production-ops-golden-path-strip`)',
        'Attach TZ strip на orders/wip/cut-ticket (`mfr-op-production-attach-tz-*`)',
        'WIP timeline PG API + cabinet strip (`/api/workshop2/manufacturer/production-timeline`, `mfr-op-production-timeline-strip`)',
        'Gantt/WIP production_orders timeline PG (`/api/workshop2/manufacturer/production-orders-timeline`, `mfr-op-wip-gantt-*`, wave WJ handoff SoT)',
        'Floor tablet WIP PATCH PG wip_status (`/api/workshop2/manufacturer/production-orders/[poId]/wip-status`, `mfr-op-wip-floor-*`, wave WO)',
        'ERP failed filter + bulk retry (`mfr-op-handoff-erp-failed-filter`, `mfr-op-handoff-erp-bulk-retry-btn`)',
        'ERP retry dashboard cabinet (`mfr-op-erp-retry-dashboard-*`, wave VD, core-149)',
        'Handoff/sample/QC spine peer (`mfr-op-production-orders-handoff-peer-strip`)',
        'Bulk-ack дубль с handoff panel — осознанный: panel=быстро, orders=MES/ERP; SoT strip (`mfr-op-handoff-queue-registry-sot-strip`, wave VH)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref(
          'manufacturer',
          'order_production',
          'mfr-op-production-orders',
          d
        ),
    },
    {
      id: 'mfr-op-dossier',
      label: 'Досье · техзадание',
      order: 3,
      staticScore: 7.8,
      liveScore: 7.9,
      summary: 'TZ export-print route + PO TZ PDF peer deduped (~8.0 после wave XU).',
      good: [
        'factory-dossier-core-chrome + `?pillar=order_production`',
        'CO spine peer queue/brand-handoff/tracking/cut-ticket/procurement (`mfr-op-dossier-co-spine-peer-strip`)',
        'Version badge из chain-status (`mfr-op-dossier-version-badge`)',
        'Печать ТЗ (`mfr-op-dossier-print-btn`)',
        'Shop-floor bundle download (`mfr-op-shop-floor-bundle-btn`, core-36)',
        'Handoff queue shop-floor link для B2B-\\d+ (core-42)',
        'Канон href: `factoryProductionDossierContextHref`',
        'Peer: shop tracking, order chat',
        'Core dossier strip: golden path без inline чата',
        'export-tz-bundle ZIP + tz-handoff-summary.pdf (jsPDF)',
        'Sample queue visible from OP dossier (`mfr-op-dossier-sample-queue-link`)',
        'TZ export + print strip (`mfr-op-dossier-export-print-*`, core-141 wave UQ, core-145 wave UY e2e)',
        'Wave XU: export-print route + RU labels deduped print CTA (`mfr-op-dossier-export-print-strip`, core-210)',
        'Wave XU: PO TZ PDF peer strip cross-link (`mfr-op-po-tz-pdf-peer-strip`, POST attach-tz-pdf)',
        'Wave XU: attach TZ PDF PO peer strip on dossier (`mfr-op-dossier-attach-tz-pdf-po-peer-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('manufacturer', 'order_production', 'mfr-op-dossier', d),
    },
    {
      id: 'mfr-op-materials',
      label: 'Закупка · поставщик',
      order: 4,
      staticScore: 6.9,
      liveScore: 7,
      summary: 'BOM×PO + CO spine peer (brand handoff, cut ticket, techpack) на procurement.',
      good: [
        'CO spine peer prod-orders/handoff/dossier/tracking/brand/cut-ticket (`mfr-op-materials-co-spine-peer-strip`)',
        'BOM×PO peer strip procurement-only (`mfr-op-materials-bom-po-peer-strip`)',
        'BOM×PO table (`materials-procurement-bom-table`)',
        'materials_supplied badge (`mfr-op-materials-supplied-badge`)',
        'SSE/poll chain-status на procurement (`mfr-op-materials-*`, `PlatformCoreChainStatusRefreshBadge`)',
        'Multi-article nav (`mfr-op-procurement-article-wizard`)',
        'Peer: prod-orders, dossier, shop tracking',
        'Разделение write: confirm только при role=supplier',
        'WMS reserve strip на procurement (`mfr-op-materials-wms-reserve-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('manufacturer', 'order_production', 'mfr-op-materials', d),
    },
    {
      id: 'mfr-op-cabinet',
      label: 'Кабинет · выпуск',
      order: 5,
      staticScore: 7.1,
      liveScore: 7.2,
      summary:
        'Hub insight: filtered chain steps + queue snippet + unified PO inbox peer in comms.',
      good: [
        'Panel (`mfr-op-cabinet-panel`)',
        'CTA groups production/comms',
        'SSE/poll badge (`mfr-op-cabinet-*-badge`)',
        'WMS badge compact + SSE (`mfr-op-cabinet-wms-reserve-badge`, data-reserve-sse-live)',
        'Queue snippet + materials step link',
        'Unified PO inbox in comms pillar (`mfr-cm-unified-po-inbox-strip`)',
        'compact-only hub',
        'Cabinet spine peer queue/brand-handoff/tracking/cut-ticket/materials/comms (`mfr-op-cabinet-spine-peer-strip`)',
        'ERP retry dashboard (`mfr-op-erp-retry-dashboard-*`, wave VD, core-149)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('manufacturer', 'order_production', 'mfr-op-cabinet', d),
    },
  ],
  comms: [
    {
      id: 'mfr-cm-order',
      label: 'Чат · заказ',
      order: 1,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'Координация с брендом/магазином по PO; unified inbox strip.',
      good: [
        'factory messages slim',
        'e2e core-01',
        'Чат из очереди PO (`mfr-op-queue-chat-*`)',
        'Чат из prod-orders (`factory-production-order-chat-*`)',
        'mfr-cm-order-context-strip',
        'Order context peer handoff/QC/brand/tracking/cut-ticket (`mfr-cm-order-handoff-link`, `mfr-cm-order-entities-link`)',
        'mfr-cm-order-chat-link + supplier link в hub',
        'comms-pillar-inbox-all (manufacturer)',
        'core-14 factory messages dedupe e2e',
        'Golden path strip inbox→handoff→tracking (`manufacturer-comms-workspace-golden-path-strip`)',
        'Attach TZ из production ops (`mfr-op-production-attach-tz-strip`, entities tab)',
        'Unified PO inbox strip (`mfr-cm-unified-po-inbox-strip`)',
        'Handoff PO push notification_events (`notifyManufacturerHandoffQueuePoInbox`, wave WY)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('manufacturer', 'comms', 'mfr-cm-order', d),
    },
    {
      id: 'mfr-cm-article',
      label: 'Чат · артикул',
      order: 2,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'Уточнения по ТЗ и образцам; article context strip + attach TZ на messages.',
      good: [
        'workshop2 article context',
        'factory-dossier-article-chat-link',
        'Article messages peer panel (`mfr-cm-article-messages-peer-panel`)',
        'mfr-cm-article-context-strip',
        'mfr-cm-article-chat-link в hub',
        'Шаблоны article-tz / article-sample',
        'core-14 article+order dedupe e2e',
        'Attach TZ peer strip (`mfr-cm-article-attach-tz-peer-strip`, `mfr-cm-article-brand-w2-peer-link`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('manufacturer', 'comms', 'mfr-cm-article', d),
    },
    {
      id: 'mfr-cm-calendar',
      label: 'Календарь · производство',
      order: 3,
      staticScore: 7.2,
      liveScore: 7.3,
      summary: 'Этапы производства + user tasks + CO spine peer + Gantt bridge.',
      good: [
        'role=manufacturer layers',
        'mfr-cm-calendar-context-strip',
        'CO spine peer handoff/brand/shop/QC/cut-ticket/techpack/comms/Gantt (`mfr-cm-calendar-context-peer-strip`)',
        'mfr-cm-calendar-link + events count в hub',
        'href layers=tasks,orders,production',
        'User tasks merged в calendar-events API',
        'GET user-task strip (`mfr-cm-calendar-user-tasks-strip`)',
        'pcTask URL focus scroll (`mfr-cm-calendar-user-tasks-strip` + `pcTask=` deep link)',
        'pcTask auto-create PG (`PlatformCorePcTaskAutoEnsure`, wave WY)',
        'Gantt bridge + attach TZ (`mfr-cm-calendar-gantt-*`, `mfr-cm-calendar-gantt-attach-tz-btn`)',
        'Gantt bridge WIP timeline (`mfr-cm-calendar-gantt-bridge-wip`, `mfr-op-wip-gantt-*`, wave WY)',
        'Attach TZ BW cross-link (`mfr-cm-calendar-attach-tz-bw-peer-strip`, wave WY)',
        'core-22 unified PO inbox',
        'Handoff queue PO в collection calendar (`b2b-po-queue-*`, core-43)',
        'Mfr calendar create task → auto-thread (core-44)',
      ],
      bad: [],
      fix: [],
      resolveHref: () =>
        `${EXTENDED_ROUTES.factory.productionCalendar}?role=manufacturer&layers=tasks,orders,production`,
    },
    {
      id: 'mfr-cm-cabinet',
      label: 'Кабинет · связь',
      order: 4,
      staticScore: 7.3,
      liveScore: 7.4,
      summary: 'CommsPillarCard manufacturer, unified PO inbox + poll fallback.',
      good: [
        'mfr-cm-cabinet-po-inbox из handoff queue',
        'Unified PO inbox strip (`mfr-cm-unified-po-inbox-strip`, all PO link)',
        'Clean PG mfr-op-handoff-queue section-group (core-40)',
        'mfr-cm-cabinet-thread-search',
        'mfr-cm-thread-search workspace',
        'mfr-cm-banner canonical calendar',
        'mfr-cm-* hub links (волны 68–70)',
        'Ссылка на тред поставщика',
        'Очередь передачи в hub card',
        'SSE/poll fallback (`mfr-cm-cabinet-poll-badge`)',
        'Cabinet spine peer handoff/tracking/materials/cut-ticket/entities (`mfr-cm-cabinet-spine-peer-strip`)',
        'Wave UP: entity-thread-templates + contextual-thread POST + chain calendar POST',
        'Wave UP: compact notification strip RU cleanup (core-140)',
        'Wave VK S2: PG comms prefs (`mfr-cm-notification-pref-chain-push`, `usePlatformCoreChainStatusPushEnabled`, PUT hub bump)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('manufacturer', 'comms', 'mfr-cm-cabinet', d),
    },
  ],
};
