/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { PILLAR_CAPABILITY_FEATURE_PARAM } from '@/lib/platform/pillar-capability-workspaces';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import { platformCoreCabinetSectionHref } from '@/lib/platform-core-cabinet-workspace';
import type { SectionAuditTemplate } from './types';

export const SHOP_SECTION_AUDIT: Partial<Record<CoreHubPillarId, readonly SectionAuditTemplate[]>> =
  {
    development: [
      {
        id: 'shop-dev-bridge',
        label: 'Мост разработки · read-only',
        order: 1,
        staticScore: 7.2,
        liveScore: 7.3,
        summary:
          'ShopDevelopmentBridge: прогресс бренда, dossier preview, PG wishlist, sample request → brand notification.',
        good: [
          'shop-development-bridge + core-31/core-107 e2e',
          'usePillarSnapshot development BFF',
          'Compact peer strip (`shop-dev-bridge-peer-strip`)',
          'Dossier preview dialog (`shop-development-bridge-dossier-preview-dialog`)',
          'PG assortment wishlist (`/api/shop/b2b/development/assortment-wishlist`, `shop-dev-bridge-wishlist-storage-pg`)',
          'Request sample → brand notification (`/api/shop/b2b/development/request-sample`)',
          'Greenfield CRM strip (`shop-development-bridge-greenfield-crm-strip`)',
          'Wave VN: CRM strip replenishment peer (`shop-dev-bridge-crm-replenishment-link`)',
          'Wave SV: client fail-closed LS + peer replenishment link',
          'Wave VZ: read-only bridge — осознанно; dossier preview + sample request peers (core-163)',
          'Wave WV: dedupe card CTAs; dossier preview sample → brand notification (core-185)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=development&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    sample_collection: [
      {
        id: 'shop-sc-showroom',
        label: 'Витрина коллекции',
        order: 1,
        staticScore: 7.8,
        liveScore: 7.9,
        summary: 'Published-articles + empty onboarding → partners/matrix (~8.0 после wave XH).',
        good: [
          'PG articles',
          'Shop empty onboarding (`shop-sc-showroom-empty-onboarding`, core-38)',
          'core-06 hero e2e',
          'Чат по артикулу (`shop-sc-showroom-article-chat-link-*`)',
          'Context strip matrix/checkout/registry/partners',
          'Orders CTA → collection registry (`shopB2bOrdersCollectionRegistryHref`)',
          'Footer matrix + checkout CTA',
          'core-06 SS27 hero + partners-link e2e',
          'core-52 eligible badge + matrix CTA on article card',
          'Cross-role audit path (shop showroom context strip)',
          '3D stream tab (`shop-showroom-feature-3d-stream`, `b2b-3d-stream-panel`)',
          'Cover hero dossier-first (`shop-showroom-cover-hero`)',
          'Inline size + qty (`shop-sc-showroom-inline-size-*`, `shop-sc-showroom-inline-qty-*`)',
          'Golden path strip B2B spine (`shop-showroom-buy-golden-path-strip`)',
          'Monetization peer strip linesheet/partners/replenishment (`shop-sc-showroom-monetization-peer-strip`)',
          'B2B peer strip platform/marketroom/partners/checkout (`shop-sc-showroom-b2b-peer-strip`)',
          'Auto-ingest после syndication бренда (`/api/shop/b2b/showroom/auto-ingest`, `shop-sc-showroom-auto-ingest-notice`)',
          'PG notification на publish лайншита (`shop-sc-showroom-syndication-notification`)',
          'Wave TL: eligible-for-matrix filter API (`/api/shop/b2b/showroom/eligible-for-matrix`, `shop-sc-showroom-eligible-filter-*`)',
          'Wave TL: partner logo PG vs dossier fallback (`shop-sc-showroom-partner-logo-source-*`)',
          'Wave VC: cover hero priority strip dossier>partner (`shop-sc-showroom-cover-hero-priority-strip`)',
          'Wave XH: partner logo PG read + dossier fallback badge RU (`shop-sc-showroom-partner-logo-source-*`)',
          'Wave XH: eligible filter counts + hint-on-toggle (`shop-sc-showroom-eligible-filter-counts`)',
          'Wave XH: hero priority strip deduped when dossier wins (wave VC alignment)',
          'Wave UW: partnerships/invite PG journal (`/api/shop/b2b/partnerships/invite`, `shop_b2b_partnership_invite_journal`)',
          'Wave UW: EMPTY27 onboarding strip (`shop-sc-empty27-onboarding-*`)',
          'Wave TL: quick-add carries partial cart qty (`carryQty`, core-116)',
          'Wave WA: showroom qty/size carry + draft validation hints (`carrySize`, core-164)',
          'Wave WA: eligible filter counts + loading (`shop-sc-showroom-eligible-filter-loading`)',
          'Wave YP: monetization partners href с ?collection= + RU peer labels (`shop-sc-showroom-monetization-peer-strip`, core-231)',
          'Wave YP: B2B peer strip RU platform/marketroom/partners (`shop-sc-showroom-b2b-peer-strip`, core-231)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopShowroomHrefForDemo(d),
      },
      {
        id: 'shop-sc-partners',
        label: 'Каталог партнёров',
        order: 2,
        staticScore: 7.7,
        liveScore: 7.8,
        summary: 'Партнёрства PG — invite journal + eligible matrix (~8.0 после wave XA).',
        good: [
          'partnerships API',
          'Guard подбора партнёров (core)',
          'Бейджи коллекций на карточке партнёра',
          'Golden path strip (`shop-sc-cabinet-golden-path`) — без дубля context strip',
          'Shop partners workspace golden path (`shop-b2b-partners-golden-path-strip`)',
          'Wave XA: partnerships/invite POST PG + journal GET (core-190)',
          'Wave XA: UAT golden path RU + no dup cabinet strip (`shop-b2b-partners-uat-golden-path-hint`)',
          'Wave XA: eligible-for-matrix cross-link (`shop-sc-partners-showroom-eligible-for-matrix-link`)',
          'Wave UW: partners UAT golden path hint RU (`shop-b2b-partners-uat-golden-path-hint`)',
          'Wave UW: invite via `/api/shop/b2b/partnerships/invite` + journal (`shop-sc-partners-invite-panel-*`)',
          'CTA витрина/матрица per connected brand',
          'e2e partners collections + showroom/matrix',
          'Profile: invite panel + чат (`shop-sc-partners-invite-*`)',
          'Бейдж PG на connected row (`shop-sc-partners-source-pg-*`)',
          'Live PG collections на profile (`shop-sc-partners-live-pg-collection-*`)',
          'Greenfield buyer: profile rows без empty API (`shop-sc-partners-panel`)',
          'B2B peer strip platform/marketroom/matrix/checkout (`shop-sc-partners-b2b-peer-strip`)',
          'Wave YP: partners B2B peer RU + discover resolveHref с collection (core-231)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bPartnersDiscover}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-sc-matrix-entry',
        label: 'Переход · матрица',
        order: 3,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'Витрина → матрица — вертикаль столпа.',
        good: [
          'CTA матрица на showroom (`shop-sc-matrix-entry-link-*`)',
          'Quick-add → matrix scroll (`shop-sc-showroom-matrix-quick-add-*`, core-52)',
          'Entry panel + strip при `?article=` (`shop-sc-matrix-entry-*`)',
          'MOQ + cart qty на витрине',
          'Quick add + deep link `?article=`',
          'Scroll к артикулу в CoreWholesaleMatrix',
          'Back link витрина + checkout из entry strip',
          'Inline size + qty (`shop-sc-showroom-inline-size-*`, `shop-sc-showroom-inline-qty-*`)',
          'Published badge + tracking on entry strip (`shop-sc-matrix-entry-published-*`, `shop-sc-matrix-entry-tracking-link`)',
          'CO peer strip platform/collaborative/ATP (`shop-sc-matrix-entry-co-peer-strip`)',
          'Wave YP: matrix entry platform B2B peer RU (`shop-sc-matrix-entry-co-peer-strip`, core-231)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          platformCoreCabinetSectionHref('shop', 'collection_order', 'shop-co-matrix', d),
      },
      {
        id: 'shop-sc-cabinet',
        label: 'Кабинет · витрина',
        order: 4,
        staticScore: 7,
        liveScore: 7.1,
        summary: 'ShopShowroomMini + honest full-showroom CTA.',
        good: [
          'shop-sc-cabinet-panel + golden path strip',
          'Partner logo PG + hero strip',
          'Empty state при 0 published',
          'e2e EMPTY27 + core-02 partner row',
          'core-38 SS27 cabinet partner + matrix CTA e2e',
          'Golden path UAT (`shop-sc-cabinet-golden-path`)',
          'Published sync badge (`shop-sc-cabinet-published-sync`)',
          '3D panel hub + CTA (`shop-sc-cabinet-3d-panel`, `shop-sc-3d-stream-cta`)',
          'Honest mini→full strip (`shop-sc-cabinet-full-showroom-honest-strip`)',
          'B2B peer strip platform/marketroom/checkout (`shop-sc-cabinet-b2b-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=sample_collection&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    collection_order: [
      {
        id: 'shop-co-matrix',
        label: 'Матрица оптового заказа',
        order: 1,
        staticScore: 8.0,
        liveScore: 8.0,
        summary: 'Matrix draft autosave PG + unified CO golden path 8.0 (wave XT/YK/YV).',
        good: [
          'PG matrix rows',
          'Panel + context strip (`shop-co-matrix-panel`)',
          'Канон testids `shop-co-matrix-*` + legacy',
          'e2e matrix→checkout→новый B2B order',
          'Matrix spine peer strip collaborative/replenishment/tracking (`shop-co-matrix-spine-peer-strip`)',
          'Inspector/prepack peer strip brand pack rules + pricelist (`shop-co-matrix-inspector-prepack-peer-strip`)',
          'core-15 clean PG checkout без B2B-DEMO pin',
          'GET/upsert cart lines PG + cookie session (workshop2-cart-bridge, P0)',
          'Matrix draft autosave PG (`/api/shop/b2b/matrix/draft`, hydrate PG fallback, `shop-co-matrix-draft-storage-pg`, core-105 wave ST)',
          'Size run validation API GET/POST + MOQ (`/api/shop/b2b/matrix/size-run-validate`, `shop-co-matrix-size-run-hint`, wave ST)',
          'Без JOOR/NuOrder на core',
          'Сводная матрица сезона (`shop-co-season-matrix-strip`)',
          'Golden path strip B2B spine (`shop-co-golden-path-strip`, legacy `shop-wholesale-matrix-golden-path-strip` retired)',
          'Wave XT: draft PUT conflict 409 + validationHintsRu (`/api/shop/b2b/matrix/draft`, core-209)',
          'Wave XT: matrix draft storage PG badge + validation hint UI (`shop-co-matrix-draft-validation-hint`)',
          'Wave XT: checkout draft-autosave-fail cross-link → matrix (`shop-co-checkout-draft-autosave-matrix-link`)',
          'Wave YK: unified CO golden path strip RU (`shop-co-golden-path-strip`, core-226)',
          'Wave YK: matrix spine peers deduped — collaborative/working-order/rules only',
          'Wave YV: audit §6 8.0 final — matrix golden path + spine peers (core-237)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          platformCoreCabinetSectionHref('shop', 'collection_order', 'shop-co-matrix', d),
      },
      {
        id: 'shop-co-checkout',
        label: 'Checkout · отправка бренду',
        order: 2,
        staticScore: 8.0,
        liveScore: 8.0,
        summary:
          'Checkout monetization + matrix draft autosave fail-closed — CO golden path 8.0 (wave XT/YV).',
        good: [
          'POST create order',
          'resolveHref → `/shop/b2b/checkout` (не matrix)',
          'Panel + context strip (`shop-co-checkout-panel`)',
          'Buyer label + канон testids `shop-co-checkout-*`',
          'Честный бейдж резерва',
          'ShopCoCheckoutInventoryReserveBadge (`shop-co-checkout-inventory-hold`, data-reserve-honest, data-reserve-phase=pre-handoff)',
          'Live WMS ATP без claim резерва (`shop-co-checkout-inventory-badge`, wave VE RU copy)',
          'WMS wave links: пополнение + трекинг (`shop-co-checkout-inventory-s3-link`, `shop-co-checkout-wms-tracking-link`)',
          'Статус submitted + системное сообщение в чат заказа при checkout',
          'Multi-tenant buyer (`shop-b2b-buyer-switcher`, cookie `shop_b2b_buyer_id`)',
          'Inline peer picker на checkout (`shop-co-checkout-buyer-picker`)',
          'Buyer из `activeOrganizationId` + `x-w2-organization-id` (org→shop1/shop2 map)',
          'Org приоритетнее cookie при onboarding',
          'Расширенный org map: shop1/shop2, org-shop-002, retail_spb_*',
          'Session uid → buyer (`shop-001`/`shop-002`)',
          'Production JWT guard на checkout (`guardShopB2bCheckoutRoute`, `WORKSHOP2_B2B_CHECKOUT_REQUIRE_JWT`)',
          'Working order tabs: PlatformCoreWmsReserveStrip (`shop-working-order-reserve-copy`)',
          'Checkout monetization peer CRM/collaborative/comms (`shop-co-checkout-monetization-peer-strip`)',
          'Greenfield readiness gate shop2 (`shop-co-checkout-greenfield-readiness-strip`)',
          'Post-checkout registry focus shop2 (`shopGreenfieldPostCheckoutRegistryHref`)',
          'Checkout POST greenfield onboarding (`/api/shop/b2b/greenfield/onboarding`)',
          'Accept-invite partner session PG (`b2b-accept-invite-storage-pg`)',
          'Registry post-checkout link (`shop-co-checkout-registry-link`)',
          'Payment intent strip YuKassa/Stripe env-gated (`shop-co-checkout-payment-intent-strip`, wave VE)',
          'Honest RU badge: не подключено / ключи / оплата готова (`shop-co-checkout-payment-intent-badge-not-connected`, `badge-configured`, `badge-intent-ready`, `badge-stub`, `badge-live`)',
          'BFF GET/POST `/api/shop/b2b/checkout/payment-intent` → integrations/yukassa|stripe create-payment',
          'Wave XT: draft autosave fail hint RU + matrix back-link (`shop-co-checkout-draft-autosave-fail-hint`, core-209)',
          'Wave YK: golden path context strip (`shop-co-checkout-context-strip`) + monetization peers без registry/tracking dup',
          'Wave YV: audit §6 8.0 — XT draft autosave fail-closed + checkout golden path (core-237)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          platformCoreCabinetSectionHref('shop', 'collection_order', 'shop-co-checkout', d),
      },
      {
        id: 'shop-co-registry',
        label: 'Реестр оптовых заказов',
        order: 3,
        staticScore: 8.0,
        liveScore: 8.0,
        summary: 'Greenfield shop2 full registry PG + CO golden path 8.0 (wave XX/YK/YV).',
        good: [
          'orders-core',
          'B2bChainPhaseBadge',
          'withShopB2bCoreLegacyGuard',
          'Экспорт CSV (`shop-co-registry-export-csv`)',
          'Context strip столп 3 (`shop-co-registry-context-strip`: matrix/заказ/tracking)',
          'Канон panel/focus (`shop-co-registry-panel`, `shop-co-registry-focus-row`)',
          'Превью треда (`shop-b2b-order-chat-preview-*`)',
          'SSE registry refetch при checkout/submit',
          'Onboarding empty (`shop-co-registry-empty-onboarding`)',
          'Buyer CRM onboarding strip (`shop-co-registry-buyer-crm-onboarding`, PG segment/terms)',
          'Empty greenfield monetization spine (`shop-co-registry-empty-greenfield-monetization-strip`)',
          'Empty greenfield PG onboarding strip (`shop-co-registry-greenfield-onboarding-strip`)',
          'Greenfield pricelist CTA (`shop-co-registry-empty-greenfield-brand-pricelist-link`)',
          'Post-checkout focus strip (`shop-co-registry-greenfield-focus-strip`)',
          'Greenfield onboarding PG (`/api/shop/b2b/greenfield/onboarding`, `shop-co-registry-greenfield-onboarding-pg`)',
          'Matrix seed link (`shop-co-registry-greenfield-focus-matrix-seed-link`)',
          'Checkout + brand pricelist CTA (`shop-co-registry-onboarding-checkout`, `shop-co-registry-onboarding-brand-pricelist`)',
          'Brand PATCH status mirror badge on registry row (`shop-co-registry-brand-status-mirror-badge`, wave TS)',
          'Wave VN: shop2 CO cabinet greenfield registry (`shop-co-greenfield-registry-*`)',
          'Wave XX: shop2 full registry PG buyer/pricelist/matrix seed (`shop-co-greenfield-registry-buyer-pg`, core-213)',
          'Wave XX: EMPTY27 registry monetization + onboarding pricelist strip (`shop-co-registry-greenfield-onboarding-strip`)',
          'Wave XX: dev bridge CRM replenishment/matrix links (`shop-development-bridge-greenfield-crm-strip`, core-213)',
          'Wave VN: CO cabinet BY pricelist + replenishment empty peers (`shop-co-cabinet-greenfield-empty-peer-strip`, `shop-co-cabinet-brand-pricelist-link`)',
          'Wave VN: dev bridge CRM replenishment/matrix (`shop-dev-bridge-crm-replenishment-link`)',
          'Wave VN: EMPTY27 buyer profile honesty (`shop-sc-cabinet-buyer-profile-no-segment`, `shop-sc-empty27-onboarding-memory`)',
          'Wave YM: EMPTY27 PG buyer profile read/write + seed CTA (`shop-sc-empty27-onboarding-seed-profile`, POST buyer-crm-profile)',
          'Invite panel на partners discover (`shop-sc-partners-invite-panel-*`)',
          'OP/CO registry spine peer tracking/margin/inventory (`shop-op-registry-spine-peer-strip`)',
          'Wave YK: registry golden path strip (`shop-co-registry-context-strip`, core-226)',
          'Wave YV: audit §6 8.0 — registry context strip + greenfield PG (core-237)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          platformCoreCabinetSectionHref('shop', 'collection_order', 'shop-co-registry', d),
      },
      {
        id: 'shop-co-detail',
        label: 'Карточка заказа',
        order: 4,
        staticScore: 8.0,
        liveScore: 8.0,
        summary: 'Факты PG, ETA peek + unified CO golden path cross-links 8.0 (wave YK/YV).',
        good: [
          'shop-order-detail-core',
          'Трекинг link на PO card',
          'Panel + context strip (`shop-co-detail-panel`, `shop-co-detail-context-strip`)',
          'Cross-links столп 3 (`shop-co-detail-cross-links`)',
          'Amend card до handoff (`shop-co-detail-amend-card`) + повтор в матрице',
          'Structured amend API (`shop-b2b-amend-request-submit`)',
          'Brand operational status mirror from v1 PATCH (`shop-co-detail-brand-operational-status`, wave TS)',
          'ETA peek strip после confirm (`shop-co-detail-eta-peek-strip`, tracking API)',
          'B2B invoice PDF (`schet-offerta.pdf?format=pdf`, jsPDF pipeline)',
          'CO spine peer matrix→replenishment (`shop-co-detail-context-strip`)',
          'Wave YK: detail golden path + peer strip collaborative/chat (`shop-co-detail-peer-strip`, core-226)',
          'Wave YV: audit §6 8.0 — detail context + collaborative/chat peers (core-237)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          platformCoreCabinetSectionHref('shop', 'collection_order', 'shop-co-detail', d),
      },
      {
        id: 'shop-co-buyer-tracking',
        label: 'Трекинг покупателя · PO',
        order: 5,
        staticScore: 8.0,
        liveScore: 8.0,
        summary: 'Buyer tracking chain + CO golden path tracking step 8.0 (wave YK/YV).',
        good: [
          'shopB2bTrackingOrderHref / #shop-co-buyer-tracking',
          'ShopProductionVisibility none/milestones/full (core-16 e2e)',
          'Brand disclosure preview strip (core-21/29/44)',
          'core-19 clean PG buyer-tracking после handoff',
          'core-44: brand disclosure link → tracking chain steps на B2B-\\d+',
          'chain-status-batch buyerView + PG order testids',
          'Tracking chat link ?pillar&section=shop-co-buyer-tracking (core-46)',
          'Legacy ?pillar=order_production redirect',
          'Materials/PO strips по visibility policy',
          'e2e core-01/06: shop-co primary testids',
          'SSE chain status на tracking panel',
          'Batch delivery ack (`shop-co-buyer-delivery-batch-ack`)',
          'delivery_received chain step + ack badges',
          'Reserve push via chain SSE (`shop-co-tracking-reserve-*`, data-reserve-sse-live)',
          'Materials push PG + SSE (`shop-co-tracking-materials-push-*`, data-materials-sse-live, data-materials-push-bump, core-103/core-154)',
          'Chain-status mirror on tracking row (`shop-co-tracking-chain-status-mirror-*`, data-chain-sse-live, wave VJ)',
          'PG logistics ТТН cross-role (`brand-co-logistics-tracking`, `shop-co-tracking-shipment-*`, core-56)',
          'Factory ack peer mirror (`shop-co-chain-peer-po-synced`, core-56)',
          'PO status SSE second-actor live (`shop-co-chain-peer-po-pending`, core-57)',
          'Brand confirm → shop mirror live без reload (core-57)',
          'OP tracking spine peer brand handoff/inventory/marketroom (`shop-op-tracking-spine-peer-strip`)',
          'Wave YK: buyer tracking in CO golden path chain (`shop-co-golden-path-tracking-link`, core-226)',
          'Wave YV: audit §6 8.0 — chain peer PO mirror + tracking golden path (core-237)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopB2bTrackingOrderHref(d.demoOrderId),
      },
      {
        id: 'shop-co-cabinet',
        label: 'Кабинет · формирование заказа',
        order: 6,
        staticScore: 8.0,
        liveScore: 8.0,
        summary: 'CO cabinet tracking embed + greenfield registry 8.0 (wave XX/XY/YK/YV).',
        good: [
          'Pillar card steps',
          'Panel + CTA groups (`shop-co-cabinet-panel`)',
          'Checkout из hub (`shop-co-cabinet-checkout-link`)',
          'Amend CTA (`shop-co-cabinet-amend-link`) до confirm бренда',
          'Post-confirm bulk amend (`shop-co-cabinet-working-order-amend-link`)',
          'Трекинг read (`shop-co-cabinet-tracking-link`)',
          'Cart qty badge (`shop-collection-order-cart-qty-badge`)',
          'Compact CO spine peer matrix→pricelist→ATP (`shop-co-cabinet-co-spine-peer-strip`)',
          'После confirm бренда: chain peek + operational status (`shop-co-cabinet-chain-peek`)',
          'Tracking embed: PlatformCoreB2bOrderDetailFacts + chain mini (`shop-co-cabinet-tracking-embed*`)',
          'Embed nav tracking↔calendar (`shop-co-cabinet-tracking-embed-nav`)',
          'Зеркало статуса бренда + шаги выпуска без столпа OP',
          'Wave VN: shop2 greenfield registry strip in hub (`shop-co-greenfield-registry-strip`)',
          'Wave VN: empty CO BY pricelist CTA (`shop-co-cabinet-brand-pricelist-link` on greenfield empty peer)',
          'Wave XX: shop2 CO cabinet greenfield buyer PG + pricelist badges (`shop-co-greenfield-registry-buyer-pg`, core-213)',
          'Wave XY: tracking embed in CO cabinet — no dup OP pillar links (`shop-co-cabinet-tracking-embed*`, core-214)',
          'Wave XY: OP pillar redirect → CO embed anchor `#shop-co-buyer-tracking` (dedupe tracking/calendar hub links)',
          'Wave XY: chain-status SSE mirror on embed (`shop-co-cabinet-tracking-embed-chain-mirror-*`)',
          'Wave YK: CO cabinet golden path + spine peers deduped (`shop-co-golden-path-strip`, core-226)',
          'Wave YV: audit §6 8.0 — cabinet embed + compact spine peers (core-237)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=collection_order&collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-co-replenishment',
        label: 'Replenishment workspace',
        order: 7,
        staticScore: 8.0,
        liveScore: 8.0,
        summary: 'ATP/reorder WMS feed + CO golden path dedup 8.0 (wave WG/YK/YV).',
        good: [
          'SmartReplenishment + B2bOrderUrlContextBanner',
          'Golden path strip (`shop-co-golden-path-strip`; legacy `shop-replenishment-golden-path-strip` feature-local only)',
          'PillarCapabilityWorkspaceChrome (alerts · stock-atp · rules — live tabs)',
          'Stock·ATP table + saved filter slices RU (`shop-replenishment-feature-stock-atp`, `shop-replenishment-slice-*`)',
          'Filter slices sidebar PG (`shop-replenishment-filter-slices-sidebar`, `shop-replenishment-slice-storage-pg`)',
          'Filter slices API GET/POST (`/api/shop/b2b/replenishment/filter-slices`, fail-closed LS in core)',
          'PG saved slice persist (`/api/shop/b2b/replenishment/stock-slice`, `shop-replenishment-slice-storage-pg`)',
          'WMS ATP feed API stub (`/api/shop/b2b/replenishment/wms-atp-feed`, `shop-replenishment-wms-atp-badge`, wave WG)',
          'Replenishment→matrix auto-lines strip (`shop-replenishment-matrix-auto-lines-strip`, `shop-replenishment-matrix-auto-lines-link`, wave WG)',
          'Intake allocate CTA (`shop-replenishment-intake-allocate-run`) → POST /api/b2b/intake/allocate',
          'Rules save+allocate one-click (`shop-replenishment-rules-save-allocate-run`)',
          'Supplier forecast ↔ replenishment cross-spine (`shop-replenishment-supplier-forecast-link`, `supplier-forecast-replenishment-atp-link`)',
          'Rule presets PG API (`/api/shop/b2b/replenishment/rules`, storageMode pg/file)',
          'Brand OTB plan-sync strip (`brand-co-otb-plan-sync-badge`, wave XV)',
          'Rules panel buyer-scoped save (`shop-replenishment-rules-save`)',
          'PillarCapabilityCrossLinksStrip',
          'Shop inventory workspace (`shop-inventory-ops`)',
          'B2bPriorityWorkflowPanel: Replenishment в analytics-shop group',
          'Golden path checkout step + CO spine peer (`shop-replenishment-golden-checkout-link`, `shop-replenishment-co-spine-peer-strip`)',
          'Replenishment→matrix lines API (`/api/shop/b2b/replenishment/matrix-lines`, `shop-replenishment-matrix-lines-hint`)',
          'Replenishment→matrix apply POST (`/api/shop/b2b/replenishment/matrix-lines/apply`, `shop-replenishment-matrix-lines-apply`)',
          'WMS ATP feed merge (`shop-replenishment-stock-atp-source-pg+wms`)',
          'Wave YK: replenishment CO golden path + peer strip dedup checkout (`shop-co-golden-path-strip`, core-226)',
          'Wave YV: feature golden path trimmed — alerts/stock-atp/rules only; CO spine strip canonical (core-237)',
          'Wave YV: audit §6 8.0 — WG WMS ATP + replenishment peers (core-237)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bReplenishment}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-co-agent-rep',
        label: 'Agent / sales rep',
        order: 8,
        staticScore: 6.7,
        liveScore: 6.9,
        scoreAliasOf: 'shop-co-checkout',
        summary:
          'Rep portal · commission ledger PG write · matrix · checkout (alias → checkout for hub §6).',
        good: [
          'shop-agent-rep workspace (portal/commission/matrix)',
          'Golden path strip (`shop-agent-rep-golden-path-strip`)',
          'Checkout + tracking monetization links in golden path',
          'Commission preview/payout API + PG ledger fetch',
          'Wave TE: commission ledger write API (`/api/shop/b2b/rep/commission-ledger`, `shop-agent-rep-commission-ledger-ru-strip`)',
          'Wave VB: commissions payout POST (`/api/shop/b2b/commissions/payout`, `shop-agent-rep-workspace-honesty-strip-ru`)',
          'Wave WS: section RU strip + PG sync queue fail-closed (`shop-agent-rep-section-ru-strip`, `shouldUseShopRepOfflineDraftsFileMemoryFallback`)',
          'Wave WS: commission payout ledger write stub (`/api/shop/b2b/commissions/payout`)',
          'Wave WS: rep → brand commission dispute peer (`shop-agent-rep-brand-commission-dispute-link`)',
          'Wave VB: offline drafts sync queue badge (`shop-agent-rep-offline-drafts-sync-queue-badge`)',
          'Wave TE: rep drafts sync PG verify + fail-closed LS (`shop-agent-rep-offline-drafts-storage-pg`)',
          'Brand ledger cross-link',
          'Offline draft API PG (`/api/shop/b2b/rep/offline-drafts`, `shop-agent-rep-offline-drafts-storage-mode`)',
          'Wave SL: rep drafts без mirror в localStorage в core',
          'Brand CRM + collaborative peer strip (`shop-agent-rep-brand-co-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: () => ROUTES.shop.b2bSalesRepPortal,
      },
      {
        id: 'shop-co-landed-margin',
        label: 'Landed margin · shop',
        order: 9,
        staticScore: 7.1,
        liveScore: 7.2,
        scoreAliasOf: 'shop-co-replenishment',
        summary:
          'Hub/rollup/pricelist + tier sync honesty → brand shop sync (alias → replenishment for hub §6).',
        good: [
          'shop-landed-margin workspace',
          'Golden path strip (`shop-landed-margin-golden-path-strip`)',
          'PG margin feed API + B2B order rollup + sync',
          'PG tier sync read on pricelist tab',
          'Tier sync honesty strip hub/rollup/pricelist (`shop-landed-margin-tier-sync-honesty-strip`)',
          'Brand pricelist publish honesty mirror (`brand-pricelist-tier-sync-honesty-strip`, wave VR)',
          'Tier sync honesty strip pending→brand push (`shop-landed-margin-tier-sync-honesty-strip`)',
          'CO spine peer matrix/checkout/replenishment/comms (`shop-co-landed-margin-spine-peer-strip`)',
          'Margin-analysis host page (`shop-landed-margin-hub-panel`, `/shop/b2b/margin-analysis`)',
          'Hub tools: calculator/report/landed cost',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bMarginAnalysis}?collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-co-collaborative-order',
        label: 'Collaborative order · session',
        order: 10,
        staticScore: 8.0,
        liveScore: 8.0,
        summary:
          'Real-time WS session + brand co-approve PG · CO golden path dedup 8.0 (wave WM/YV).',
        good: [
          'shop-collaborative-order workspace',
          'Golden path strip (`shop-co-golden-path-strip` + feature `shop-collaborative-order-golden-path-strip`)',
          'Working order step in golden path (`shop-collaborative-golden-working-order-link`)',
          'Extended peer strip matrix + versions (`shop-collaborative-matrix-peer-link`, `shop-collaborative-working-order-link`)',
          'Session cross-links (`shop-collaborative-session-cross-links`, matrix/working-order/brand portal)',
          'Extended peer strip working order/replenishment (`shop-collaborative-order-extended-peer-strip`)',
          'Participants + approval chain panels (RU status)',
          'PG approval workflow API (`/api/shop/b2b/collaborative/approvals`)',
          'Session poll + SSE stream (`useShopCollaborativeSessionLive`, `ShopCollaborativeSessionLiveBadges`)',
          'Live badge RU (`shop-collaborative-session-sse-badge`, `shop-collaborative-session-poll-badge`)',
          'Session PG badge (`shop-collaborative-session-storage-pg`)',
          'Brand co-approve margin PG (`/api/brand/b2b/collaborative/approve`, `brand-co-collaborative-margin-approve-btn`)',
          'Shop margin step brand-only (`shop-collaborative-approval-brand-only-margin`)',
          'Advance buttons (`shop-collaborative-approval-advance-*`)',
          'Brand order chat/handoff bridges на approvals/comms',
          'Extended peer checkout link (`shop-collaborative-checkout-link`)',
          'Wave WM e2e core-176',
          'Wave YV: CO golden path + feature strip session/approvals/comms only (core-237)',
          'Wave YV: audit §6 8.0 — WM collaborative session cross-links (core-237)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bCollaborativeOrder}?collection=${encodeURIComponent(d.collectionId)}&${PILLAR_CAPABILITY_FEATURE_PARAM}=session`,
      },
      {
        id: 'shop-co-working-order',
        label: 'Working order · versions',
        order: 11,
        staticScore: 8.0,
        liveScore: 8.0,
        summary: 'Versions/bulk/handoff + version diff merge 8.0 (wave TP/XL/YV).',
        good: [
          'shop-working-order workspace',
          'Golden path strip (`shop-co-golden-path-strip` + feature `shop-working-order-golden-path-strip`)',
          'Native order honest strip (`shop-working-order-native-order-honest-strip`)',
          'Tracking via shopB2bTrackingOrderHref in CO golden path',
          'PlatformCoreWmsReserveStrip на tabs',
          'Spine panel INT-* imported orders',
          'Version diff API (`GET /api/shop/b2b/working-order/diff?orderId=`, Wave TP core-118, XL polish core-201)',
          'Golden path matrix link (`shop-co-golden-path-matrix-link`, Wave XL/YV)',
          'Legacy version-diff path (`/api/shop/b2b/working-order/.../version-diff`, wave SP)',
          'Version diff summary strip (`shop-working-order-version-diff-summary`)',
          'Version diff line preview (`shop-working-order-version-diff-lines`)',
          'Merge→matrix POST (`/api/shop/b2b/working-order/.../merge-to-matrix`, `shop-working-order-merge-to-matrix-btn`)',
          'Partial merge matrix deep-link (`shop-working-order-merge-matrix-link`, partialMerge=1)',
          'CO spine peer ATP/collaborative/brand chat (`shop-working-order-co-spine-peer-strip`)',
          'Wave YV: working-order feature strip versions/bulk/handoff only; CO spine canonical (core-237)',
          'Wave YV: audit §6 8.0 — XL version diff + merge→matrix (core-237)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.b2bWorkingOrder}?collection=${encodeURIComponent(d.collectionId)}&${PILLAR_CAPABILITY_FEATURE_PARAM}=versions`,
      },
    ],
    order_production: [
      {
        id: 'shop-op-tracking',
        label: 'Трекинг цепочки',
        order: 1,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Alias shop-co tracking + OP spine peer on order-comms workspace.',
        good: [
          '5 steps + materials done/pending badges',
          'Канон testids `shop-co-tracking-*` (legacy shop-op-* audit-only, core-45)',
          'shop-co-tracking-sse/poll badge',
          'e2e core-01/06: shop-co primary testids (helper)',
          'Reserve badge честный + WMS e2e',
          'Выпуск + registry с `?order=` в strip/rows',
          'B2bChainPhaseBadge + CSV export',
          'Tracking→calendar/chat/production CTA',
          'Per-row calendar deep-link (`shop-co-tracking-row-calendar-link-*`, wave VH)',
          'platform-core-chain-step-* на шагах',
          'Batch delivery ack panel (`shop-co-buyer-delivery-batch-ack`)',
          'shop-order-comms golden path (`shop-order-comms-golden-path-strip`)',
          'Working order + replenishment on context strip (`shop-co-tracking-working-order-link`, `shop-co-tracking-replenishment-link`)',
          'OP tracking spine peer (`shop-op-tracking-spine-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopB2bTrackingOrderHref(d.demoOrderId),
      },
      {
        id: 'shop-op-order-status',
        label: 'Карточка · статус PO',
        order: 2,
        staticScore: 7.1,
        liveScore: 7.2,
        scoreAliasOf: 'shop-co-detail',
        summary: 'PO card + OP order-status spine peer (registry/handoff/inventory).',
        good: [
          'Chain card: steps + SSE + materials badge',
          'Order-status spine peer (`shop-op-order-status-spine-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopB2bOrderProductionContextHref(d.demoOrderId),
      },
      {
        id: 'shop-op-registry',
        label: 'Реестр · контекст',
        order: 3,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'Список PG заказов + OP spine peer (alias CO registry).',
        good: [
          'Фильтр in_production + focus row',
          'Registry spine peer tracking/margin/inventory (`shop-op-registry-spine-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopB2bOrdersProductionRegistryHref(d.demoOrderId),
      },
      {
        id: 'shop-op-cabinet',
        label: 'Кабинет · после отправки',
        order: 4,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'Shop OP hub: ETA peek + unified cabinet spine peer (handoff/margin/inventory).',
        good: [
          'Panel (`shop-co-cabinet-panel`, audit alias `shop-op-cabinet-panel`)',
          'shop-co-tracking-context-strip: заказ · реестр · календарь · чат',
          'PO/ETA peek в hub (`shop-op-cabinet-eta-peek-strip`, tracking API + PO badge)',
          'Cabinet spine peer handoff/tracking/calendar/margin/inventory (`shop-op-cabinet-spine-peer-strip`)',
          'Registry с `?order=`',
          'SSE/poll badge (`shop-op-cabinet-*-badge`)',
          'compact-only hub',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=order_production&collection=${encodeURIComponent(d.collectionId)}`,
      },
      {
        id: 'shop-op-inventory-ops',
        label: 'Inventory · overview',
        order: 5,
        staticScore: 7.2,
        liveScore: 7.3,
        summary: 'PG ledger strip on overview + reconcile tab + golden path.',
        good: [
          'shop-inventory-ops workspace',
          'Golden path strip (`shop-inventory-ops-golden-path-strip`)',
          'PlatformCoreInventoryLedgerStrip (`shop-inventory-ledger-strip`)',
          'Reconcile panel + InventoryPageContent',
          'Brand inventory cross-link',
          'OP spine peer replenishment/tracking/matrix (`shop-op-inventory-spine-peer-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.inventory}?${PILLAR_CAPABILITY_FEATURE_PARAM}=overview&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
    comms: [
      {
        id: 'shop-cm-order-chat',
        label: 'Чат · заказ',
        order: 1,
        staticScore: 7.3,
        liveScore: 7.4,
        summary: 'Связь с брендом по B2B заказу; order-comms context strip + registry stream.',
        good: [
          'threads API',
          'contextual chat= URL',
          'Universal inbox: все заказы PG в sidebar',
          'Wave SK: PlatformCoreCommsUniversalInboxStrip на /shop/messages',
          'Wave TT: PG unread count per order в universal inbox (`*-universal-inbox-order-unread-*`, threads + pgEventUnread)',
          'Wave XO: unread-summary batch на strip + order-specific badge + tracking→calendar pcTask row',
          'B2B шаблоны в slimCore',
          'Article-chat витрина/матрица (`shop-showroom-article-chat-link-*`, `shop-b2b-matrix-article-chat-*`)',
          'shopMessagesWorkshop2ArticleContextHref',
          'PG unread + registry SSE bump в shop messages',
          'shop-cm-order-context-strip на order-comms chat/calendar tabs',
          'shop-cm-order-chat-link в hub',
          'Server read receipts (shop-buyer actor)',
          'Core: чат на карточке заказа, не в реестре',
          'Hub collection_order compact: CommsNotificationCenterStrip (`shop-co-cabinet-panel`)',
          'Order workspace registry stream (`shop-cm-order-registry-stream-health-strip`)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopMessagesB2bOrderContextHref(d.demoOrderId),
      },
      {
        id: 'shop-cm-calendar-order',
        label: 'Календарь · заказ',
        order: 2,
        staticScore: 7,
        liveScore: 7.1,
        summary: 'Окна отгрузки, клик → чат; PG user tasks + monetization + brand CRM peers.',
        good: [
          'externalEventsOnly → chat',
          'Hub compact: notification center на collection_order + full comms pillar',
          'Статус одной строкой в hub comms card',
          'shop-cm-calendar-link в hub',
          'Context peer strip tracking/chat/replenishment/checkout/brand CRM (`shop-cm-calendar-context-peer-strip`)',
          'PG user tasks strip + refetch on create (`shop-cm-calendar-user-tasks`)',
          'pcTask URL focus scroll (`shop-cm-calendar-user-tasks-strip` + `pcTask=` deep link)',
          'Role-correct order chat href (shop/brand/mfr/supplier)',
          'Calendar event → tracking CTA (`shop-cm-calendar-tracking-deep-link-*`, `shop-cm-notification-tracking-link`)',
          'Wave SN: shop-cm-calendar-event-tracking-strip + row deep-link; chain→PG calendar task',
          'Wave SU: calendar user-task + notification event deep-link → tracking card',
          'Wave VJ: tracking chain-status mirror badge + materials_supplied push bump; calendar event strip all roles (core-154)',
          'Wave XY: calendar event tracking deep-link strip (`shop-cm-calendar-event-tracking-strip`, core-214)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) => shopCalendarB2bOrderContextHref(d.demoOrderId),
      },
      {
        id: 'shop-cm-calendar-logistics',
        label: 'Календарь · закупки',
        order: 3,
        staticScore: 6.9,
        liveScore: 7,
        scoreAliasOf: 'shop-cm-calendar-order',
        summary: 'Слой logistics на том же экране — окна поставки и materials_supplied.',
        good: [
          'layers=orders,logistics',
          'materials_supplied → b2b-materials-* event',
          'Alias scoring — скрыт из разворота hub (scoreAliasOf)',
        ],
        bad: [],
        fix: [],
        resolveHref: () => `${ROUTES.shop.b2bCalendar}?layers=orders,logistics`,
      },
      {
        id: 'shop-cm-cabinet',
        label: 'Кабинет · связь',
        order: 4,
        staticScore: 7.1,
        liveScore: 7.2,
        summary: 'CommsPillarCard shop, clean PG section-groups + poll fallback.',
        good: [
          'shop-cm-cabinet-po-inbox из buyer registry',
          'Registry stream health strip (`shop-cm-cabinet-registry-stream-health-strip`)',
          'CommsPillarCard',
          'Clean PG buyer-tracking section-group (core-40)',
          'shop-cm-cabinet-thread-search',
          'shop-cm-thread-search workspace',
          'shop-cm-banner dedupe',
          'shop-cm-* hub links (волны 68–70)',
          'CommsNotificationCenterStrip compact/full (`shop-cm-notification-center*`)',
          'S4 PG notification_events (`/api/platform-core/notification-events`, `shop-cm-notification-pg-events-list`)',
          'PG unread-summary API (`/api/platform-core/comms/unread-summary`)',
          'Comms prefs PG all roles (`/api/platform-core/comms/notification-prefs`, storageMode postgres, fail-closed LS, `*-cm-notification-pref-chain-push`, `usePlatformCoreChainStatusPushEnabled`)',
          'Wave VK S2: PUT hub bump (`bumpPlatformCoreCommsNotificationPrefs`) + prefs SSE poll refetch strip',
          'SSE/poll fallback (`shop-cm-cabinet-poll-badge`, `comms-pillar-sse-live-badge`)',
          'CO spine peer registry/matrix/checkout (`shop-cm-cabinet-spine-peer-strip`)',
          'Wave UP: entity-thread-templates PG + POST calendar-events chain hook',
          'Wave UP: contextual-thread POST order/article + compact strip без placeholder',
          'Wave XZ: entity-thread-templates PG API + shop matrix published badge RU (core-215)',
        ],
        bad: [],
        fix: [],
        resolveHref: (d) =>
          `${ROUTES.shop.coreCabinet}?pillar=comms&collection=${encodeURIComponent(d.collectionId)}`,
      },
    ],
  };
