/**
 * @generated split from platform-core-readiness-sections.ts — do not edit monolith; edit role file.
 */
import type { CoreHubPillarId } from '@/lib/platform-core-hub-matrix';
import {
  brandLinesheetsHrefForDemo,
  brandShowroomHrefForDemo,
  factoryHandoffQueueHrefForDemo,
  factoryMaterialsHrefForDemo,
  factoryMaterialsProcurementHrefForDemo,
  platformCoreRolePillarHref,
  shopShowroomHrefForDemo,
} from '@/lib/platform-core-hub-matrix';
import {
  ROUTES,
  brandB2bOrderChainContextHref,
  brandB2bOrderDossierContextHref,
  brandB2bOrderHandoffContextHref,
  brandB2bOrderHref,
  brandB2bOrdersAwaitingHandoffRegistryHref,
  brandB2bOrdersProductionRegistryHref,
  brandCoreOrderProductionCabinetHref,
  brandCalendarB2bOrderContextHref,
  brandMessagesB2bOrderContextHref,
  brandMessagesWorkshop2ArticleContextHref,
  brandW2ProductionTzHref,
  factoryMessagesB2bOrderContextHref,
  factoryMessagesWorkshop2ArticleContextHref,
  factoryCoreOrderProductionCabinetHref,
  factorySupplierCoreOrderProductionCabinetHref,
  factoryProductionDossierContextHref,
  factoryProductionDossierHref,
  factoryProductionOrdersOrderContextHref,
  factorySupplierMessagesB2bOrderContextHref,
  factorySupplierMessagesWorkshop2ArticleContextHref,
  factorySupplierRfqInboxHref,
  shopB2bOrderHref,
  shopB2bOrderProductionContextHref,
  shopB2bOrdersProductionRegistryHref,
  shopB2bTrackingOrderHref,
  shopCalendarB2bOrderContextHref,
  shopMessagesB2bOrderContextHref,
} from '@/lib/routes';
import { WORKSHOP2_COL_PARAM, workshop2ArticleHref } from '@/lib/production/workshop2-url';
import { platformCoreCabinetSectionHref } from '@/lib/platform-core-cabinet-workspace';
import type { SectionAuditTemplate } from './types';

export const SUPPLIER_SECTION_AUDIT: Partial<
  Record<CoreHubPillarId, readonly SectionAuditTemplate[]>
> = {
  development: [
    {
      id: 'sup-dev-bom',
      label: 'BOM · спецификация',
      order: 1,
      staticScore: 7.1,
      liveScore: 7.2,
      summary: 'Материалы из dossier PG — основа RFQ-free core.',
      good: [
        'SupplierBomPreview',
        'UoM в preview',
        'Drawer expand',
        'Brand BOM peer (`sup-dev-bom-brand-peer-link`)',
        'Dev BOM chain peer on procurement (`sup-op-bom-po-chain-peer-strip`)',
        'Mfr dev peer strip brand W2/dossier/comms (`sup-dev-bom-mfr-dev-peer-strip`)',
        'Brand BOM PG feed strip (`sup-dev-bom-brand-feed-strip`, POST supplier-bom API)',
        'Brand dev peers passport/schema/RFQ (`sup-dev-bom-brand-dev-peer-strip`)',
        'Wave YP: sup-dev BOM brand-dev peer RU labels (`sup-dev-bom-brand-dev-peer-strip`, core-231)',
        'BOM workspace brand push + WMS (`sup-op-procurement-brand-push-strip`, `sup-op-procurement-bom-wms-reserve-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('supplier', 'development', 'sup-dev-bom', d),
    },
    {
      id: 'sup-dev-materials',
      label: 'Материалы · разработка',
      order: 2,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'view=development — workspace столпа; honest price journal + CO spine peers.',
      good: [
        'materials-core development',
        'List chrome',
        'Sidebar nav: Каталог материалов (`materials-catalog-core`, `/factory/production/catalog`)',
        'Wave SX: sidebar testid `supplier-sidebar-materials-catalog-nav` (не дубль cabinet)',
        'Dev cabinet catalog peer (`sup-dev-cabinet-catalog-link`)',
        'materials-price-journal из dossier_events',
        'materials-price-history fallback из unitCostNet',
        'Honest empty journal strip + RFQ/BOM/comms peers (`sup-dev-materials-price-journal-honest-strip`)',
        'Forecast/replenishment/tracking spine (`sup-dev-materials-co-peer-strip`)',
        'Wave UF: price delta alerts GET + strip (`sup-dev-price-delta-alert-strip`, `/api/workshop2/supplier/price-delta-alerts`)',
        'Wave UF: compare suppliers P2 stub RU (`sup-dev-compare-suppliers-p2-strip`)',
        'Wave VG: compare P2 wired in dev cabinet + peer links materials/catalog/RFQ',
        'Wave VG: quote card RU polish + compare cross-link (`sup-dev-rfq-quote-card-compare-link`)',
        'Wave VG: cabinet catalog nav peers materials + RFQ (`supplier-core-material-catalog-*-peer`)',
        'Wave VG: core-152 e2e + wave-vg-supplier-compare-quote unit',
        'Wave WK: pillar nav catalog inside development aside (`supplier-dev-pillar-material-catalog-nav`)',
        'Wave WK: catalog PG read strip on cabinet page (`supplier-material-catalog-pg-read-strip`)',
        'Wave WK: price delta RU via wave-wk + wired in dev cabinet',
        'Wave WK: compare P2 Centric badge polish + core-174 e2e',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('supplier', 'development', 'sup-dev-materials', d),
    },
    {
      id: 'sup-dev-comms-peer',
      label: 'Чат · уточнение цены',
      order: 3,
      staticScore: 6.9,
      liveScore: 7,
      summary: 'Alias sup-cm-article + procurement CO spine on workspace.',
      good: [
        'RFQ→[] в core',
        'sup-cm-article-chat-link unified',
        'Шаблон article-price-quote',
        'SLA response strip on RFQ (`sup-dev-sla-response-strip`)',
        'Procurement CO spine forecast/tracking/supply (`sup-op-procurement-co-peer-strip`)',
        'Wave UF: RFQ SLA timer on inbox (`sup-dev-rfq-sla-timer-strip`)',
        'Wave UF: quote card panel (`sup-dev-rfq-quote-card-panel`)',
        'Wave VG: quote card amount line RU + compare link on RFQ inbox',
        'Wave UF: core-132 e2e RFQ SLA + price delta',
        'Wave XD: rfq-sla-anchor GET API + inline thread SLA badge (core-193)',
        'Wave XD: quote card inbox link deduped off messages?feature=rfq (core-193)',
        'Осознанный alias nav столп 1↔5 (development/comms peer — не дубль cabinet, wave VH)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('supplier', 'development', 'sup-dev-comms-peer', d),
    },
    {
      id: 'sup-dev-cabinet',
      label: 'Кабинет · BOM образца',
      order: 4,
      staticScore: 7.8,
      liveScore: 7.9,
      summary: 'Alt-material PG approve/reject + brand notification (~8.0 после wave XW).',
      good: [
        'Только BOM без пустого RFQ',
        'Primary → materials',
        'materials-bom-fill-rate',
        'materials-bom-weighted-fill-rate',
        'materials-alt-materials из substitutes',
        'Alt materials PG approval GET/POST (`/api/workshop2/supplier/alt-material-approval`)',
        'materials-alt-submit/approve/reject + RU статусы',
        'BOM cabinet strip (`sup-dev-bom-alt-material-approval-strip`)',
        'core-53 materials-bom-fill-rate e2e',
        'core-118 wave TR alt-material approval e2e',
        'Dev cabinet spine peer BOM/RFQ/CRM (`sup-dev-cabinet-spine-peer-strip`)',
        'Wave XW: alt-material PG approve + brand notification-events (`/api/workshop2/supplier/alt-material-approval`, core-212)',
        'Wave XW: brand BOM strip ↔ supplier cabinet cross-links (`brand-dev-bom-alt-material-approval-strip`, `sup-dev-bom-alt-material-approval-strip`)',
        'Wave XW: materials workspace alt-materials nav + RU note (`materials-alt-materials-nav`, core-212)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('supplier', 'development', 'sup-dev-cabinet', d),
    },
  ],
  order_production: [
    {
      id: 'sup-op-procurement',
      label: 'Закупка · PATCH',
      order: 1,
      staticScore: 8.0,
      liveScore: 8.0,
      summary: 'Honest procurement chain RU — YJ/YI/WP/WI closure + wave YU §6 8.0 (core-236).',
      good: [
        'PATCH API',
        'e2e core-02',
        'Confirm gated on PO queue',
        'Канон panel (`sup-op-procurement-panel`)',
        'RU статус PO + handoff poll refresh',
        'Success strip → tracking/chat',
        'Context strip + tracking cross-role',
        'bulk-confirm API (все BOM строки)',
        'role=supplier canonical href + cabinet back',
        'Multi-article wizard + confirmAllArticles API',
        'Brand chat → section auto-thread (`sup-op-procurement-brand-chat-link`, core-48)',
        'Brand notify strip после confirm (`sup-op-procurement-brand-push-strip`)',
        'Push materials_supplied → brand PG notification (`recordPlatformCoreChainNotificationEvents`)',
        'WMS reserve strip на procurement (`sup-op-procurement-wms-reserve-strip`)',
        'B2B inventory reserve PATCH CTA (`sup-op-procurement-b2b-inventory-reserve-btn`)',
        'PATCH inventory/reserve после materials confirm (`/api/workshop2/b2b/orders/{id}/inventory-reserve`)',
        'Partial ship + backorder (`sup-op-partial-ship-confirm-strip`, PG `partial_ship_qty`/`backorder_flag`, bulk-confirm idempotency)',
        'Golden path strip (`supplier-procurement-golden-path-strip`)',
        'Forecast/supply spine peer (`sup-op-procurement-forecast-peer-strip`)',
        'CO spine peer mfr handoff/forecast/tracking/supply (`sup-op-procurement-co-peer-strip`)',
        'Brand inventory ledger peer после PATCH (`sup-op-procurement-brand-inventory-ledger-peer-strip`)',
        'Procurement chain steps RU (`sup-op-procurement-chain-steps`, wave WP)',
        'Wave YJ: honest chain strip reserve/partial/bulk/WMS webhook (`data-procurement-honest-chain`, wave-yj-sup-op-procurement-chain)',
        'Wave YJ: comms tail hrefs carry po= (`buildSupOpCommsTailHref`, `data-comms-tail-po`)',
        'Wave WI: partial ship/backorder + bulk-confirm idempotency (core-172)',
        'Wave WP: BOM×PO progress + brand inventory ledger peer (core-179)',
        'Wave YI: e2e registry WI/WP/YJ specs (core-224)',
        'Wave YU: §6 audit 8.0 bump + chain completeness spot e2e (core-236, wave-yu-sup-op-80-bump)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('supplier', 'order_production', 'sup-op-procurement', d),
    },
    {
      id: 'sup-op-bom-po',
      label: 'BOM × PO · прогресс',
      order: 2,
      staticScore: 8.0,
      liveScore: 8.0,
      summary: 'BOM×PO progress без cap — WP chain peer + wave YU closure.',
      good: [
        'supplier-procurement-bom-progress',
        'sup-op-bom-po-progress на workspace',
        'Bulk-confirm progress в BOM×PO card (`sup-op-bulk-confirm-progress-strip`, dedup hint)',
        'PO qty из queue',
        'bomPct без cap 40%',
        'PO bundle PDF (`po-bundle.pdf`, sup-op-bom-po-bundle-pdf)',
        'Chain spine peer handoff/forecast/tracking (`sup-op-bom-po-chain-peer-strip`)',
        'Wave WP: procurement chain steps + brand push on PATCH (core-179)',
        'Wave YU: BOM×PO section 8.0 chain peer completeness (core-236)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('supplier', 'order_production', 'sup-op-bom-po', d),
    },
    {
      id: 'sup-op-chain',
      label: 'Этап · materials_supplied',
      order: 3,
      staticScore: 8.0,
      liveScore: 8.0,
      summary: 'WMS + materials chain steps — YJ honest sub-steps + wave YU closure.',
      good: [
        'sup-op-chain-steps + workspace mirror',
        'sup-op-chain-sse/poll badge workspace',
        'WMS reserve в chainSteps + badge (`sup-op-cabinet-wms-reserve-badge`, core-43)',
        'Чат бренду на шаге (`sup-op-chain-workspace-brand-chat-link`, section context)',
        'materials badges на procurement workspace',
        'chain-status SSE bump на materials confirm (materials_supplied step)',
        'PATCH inventory/reserve → PO payload + inventory_reserved step (S3)',
        'Brand notify strip + order chat deep-link (`sup-op-procurement-brand-push-*`)',
        'Workspace peer forecast/tracking/supply (`sup-op-chain-workspace-peer-strip`)',
        'Wave YJ: chain-status SSE bump on materials confirm + honest chain attr',
        'Wave YU: chain workspace mirror 8.0 (core-236)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('supplier', 'order_production', 'sup-op-chain', d),
    },
    {
      id: 'sup-op-handoff-read',
      label: 'Очередь передачи · read',
      order: 4,
      staticScore: 8.0,
      liveScore: 8.0,
      summary: 'PO context до закупки — handoff read spine + wave YU closure.',
      good: [
        'Handoff queue fetch + refresh на chain poll',
        'order= в procurement href',
        'PO deep-link (`sup-op-handoff-read-po-link`)',
        'Strip (`sup-op-handoff-read-strip`) + счётчик (`sup-op-handoff-read-queue-count`)',
        'CTA очередь (`sup-op-handoff-read-queue-link`)',
        'Peer strip manufacturer SSE (`supplier-manufacturer-handoff-peer-strip`)',
        'Spine peer mfr queue/forecast/tracking (`sup-op-handoff-read-spine-peer-strip`)',
        'Wave YU: handoff read queue po= deep-link chain (core-236)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('supplier', 'order_production', 'sup-op-handoff-read', d),
    },
    {
      id: 'sup-op-cabinet',
      label: 'Кабинет · закупка',
      order: 5,
      staticScore: 8.0,
      liveScore: 8.0,
      summary: 'SupplierProcurementPillarCard — unified spine nav + wave YU 8.0.',
      good: [
        'Panel (`sup-op-cabinet-panel`)',
        'Unified spine nav (`sup-op-cabinet-spine-nav-strip`)',
        'CTA groups production/comms',
        'Tracking peer link всегда (`sup-op-cabinet-tracking-link`)',
        'SSE/poll badge (`sup-op-cabinet-*-badge`)',
        'WMS reserve badge compact + SSE (`sup-op-cabinet-wms-reserve-badge`, data-reserve-sse-live)',
        'BOM + chain + handoff в одной карточке',
        'Multi-article wizard на procurement workspace',
        'Manufacturer read-only article tabs (`mfr-op-procurement-article-wizard`)',
        'Wave YU: cabinet spine nav + WMS badge SSE completeness (core-236)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('supplier', 'order_production', 'sup-op-cabinet', d),
    },
  ],
  comms: [
    {
      id: 'sup-cm-order',
      label: 'Чат · заказ',
      order: 1,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'Связь с брендом/цехом; CRM peer strip.',
      good: [
        'supplier role messages',
        'Redirect /factory/supplier→core',
        'Universal inbox merge',
        'Wave SK: PlatformCoreCommsUniversalInboxStrip на supplier messages + rfq-inbox',
        'sup-cm-order-context-strip',
        'sup-cm-order-chat-link в hub',
        'core-14 supplier messages dedupe e2e',
        'Quote templates via slimCore + custom save (shared with brand B2B bar)',
        'Entities tab: inbox SSE/poll + manufacturer handoff peer (`supplier-comms-entity-*`)',
        'CRM peer strip (`sup-cm-crm-peer-strip`)',
        'Order context spine procurement→tracking (`sup-cm-order-context-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => platformCoreCabinetSectionHref('supplier', 'comms', 'sup-cm-order', d),
    },
    {
      id: 'sup-cm-article',
      label: 'Чат · артикул',
      order: 2,
      staticScore: 6.9,
      liveScore: 7,
      summary: 'Уточнение материалов по артикулу.',
      good: [
        'Article context `/factory/supplier/messages`',
        'sup-cm-article-context-strip',
        'sup-cm-article-chat-link в hub + BOM workspace',
        'Шаблон article-price-quote',
        'supplier-procurement-*-article-chat',
        'Quote card UI on comms pillar (`sup-cm-article-quote-honest-strip`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => platformCoreCabinetSectionHref('supplier', 'comms', 'sup-cm-article', d),
    },
    {
      id: 'sup-cm-rfq-inbox',
      label: 'RFQ inbox · отдельный маршрут',
      order: 3,
      staticScore: 7.7,
      liveScore: 7.8,
      summary: 'Dedicated rfq-inbox — SLA timer + quote RU (~8.0 после wave XD).',
      good: [
        'supplier-rfq-inbox-core',
        'factorySupplierRfqInboxHref',
        'supplier-procurement-rfq-inbox-link',
        'Wave SK: entity thread rfq contextHref → rfq-inbox',
        'Wave SX: comms nav `rfq-inbox-core` → `/factory/supplier/rfq-inbox` (не messages?feature=rfq)',
        'Wave SX: sidebar testid `supplier-sidebar-rfq-inbox-nav`',
        'Wave UF: SLA timer + quote card on RFQ inbox (`sup-dev-rfq-sla-timer-strip`, `sup-dev-rfq-quote-card-panel`)',
        'Wave UF: supplier-rfq-inbox-panel + core-132 e2e',
        'Wave VO: quote peer → rfq-inbox (`sup-cm-article-quote-rfq-inbox-link`, `sup-cm-cabinet-rfq-inbox-peer-link`)',
        'Wave XD: rfq-sla-anchor GET + SLA strip/quote card RU on inbox (core-193)',
        'Wave XD: entity thread inline SLA badge (`sup-dev-rfq-sla-timer-thread-badge-*`)',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) =>
        platformCoreCabinetSectionHref('supplier', 'comms', 'sup-cm-rfq-inbox', d),
    },
    {
      id: 'sup-cm-calendar',
      label: 'Календарь · логистика',
      order: 4,
      staticScore: 7.2,
      liveScore: 7.3,
      summary: 'Logistics layer + ETA/map overlay + delivery confirm + procurement spine peers.',
      good: [
        'role=supplier calendar',
        'sup-cm-calendar-context-strip + procurement role=supplier',
        'Context peer procurement/forecast/mfr handoff/tracking (`sup-cm-calendar-context-peer-strip`)',
        'Logistics peer strip (`sup-cm-calendar-logistics-peer-strip`)',
        'ETA/map overlay stub на delivery window (`sup-cm-logistics-eta-strip`, `sup-cm-logistics-eta-map-stub`)',
        'Wave VO: RU ETA/map overlay + logistics peer strip без EN placeholders',
        'Wave VO: core-159 e2e logistics ETA/map + calendar peer',
        'PG user tasks strip + refetch (`sup-cm-calendar-user-tasks`)',
        'sup-cm-calendar-link в hub',
        'Canonical `/factory/calendar` (не production ACL)',
        'sup-cm-delivery-confirm-btn + POST delivery-confirm',
      ],
      bad: [],
      fix: [],
      resolveHref: () => `${ROUTES.factory.calendar}?role=supplier&layers=tasks,orders,logistics`,
    },
    {
      id: 'sup-cm-cabinet',
      label: 'Кабинет · связь',
      order: 4,
      staticScore: 7,
      liveScore: 7.1,
      summary: 'CommsPillarCard supplier, clean PG procurement section-group (core-40).',
      good: [
        'sup-cm-cabinet-po-inbox parity',
        'Clean PG sup-op-procurement section-group (core-40)',
        'sup-cm-cabinet-thread-search',
        'sup-cm-thread-search workspace',
        'sup-cm-banner + inbox parity',
        'sup-cm-* hub links (волны 68–70)',
        'Brand push strip (`sup-cm-cabinet-brand-push-strip`) + chat/entities/supply links',
        'Insight card',
        'Core redirect preserve hash',
        'comms-pillar-inbox-all supplier',
        'CommsPillarCard compact-only',
        'Очередь передачи в hub card',
        'Cabinet spine peer procurement→brand chat (`sup-cm-cabinet-spine-peer-strip`)',
        'Wave VK S2: PG comms prefs (`sup-cm-notification-pref-chain-push`, `usePlatformCoreChainStatusPushEnabled`, PUT hub bump)',
        'Wave VO: CommsPillarCard chain-status poll (не comms SSE) + compact dot badge',
        'Wave VO: RU cleanup comms strips (CRM peer, brand push, logistics peer)',
        'Wave VO: wave-vo-sup-logistics-eta.test.ts + core-159 e2e',
      ],
      bad: [],
      fix: [],
      resolveHref: (d) => platformCoreCabinetSectionHref('supplier', 'comms', 'sup-cm-cabinet', d),
    },
  ],
};
