/**
 * Карта декомпозиции Workshop2Phase1DossierPanel (волна 45+).
 * Контракт для onboarding и jest — без смены UX.
 */
export const WORKSHOP2_PHASE1_DOSSIER_PANEL_DECOMPOSITION_MANIFEST = {
  orchestrator: 'Workshop2Phase1DossierPanel.tsx',
  shell: [
    'workshop2-phase1-dossier-panel-body-shell.tsx',
    'workshop2-phase1-dossier-panel-post-main-trail.tsx',
    'workshop2-phase1-dossier-panel-footer-actions.tsx',
    'use-workshop2-phase1-dossier-panel-main-layout-zone.tsx',
    'use-workshop2-phase1-dossier-panel-tail-zone.tsx',
    'workshop2-phase1-dossier-panel-tail-bundles.ts',
  ],
  sectionBodies: [
    'workshop2-phase1-dossier-panel-section-body.tsx',
    'workshop2-phase1-dossier-panel-section-body-general.tsx',
    'workshop2-phase1-dossier-panel-section-body-construction.tsx',
    'workshop2-phase1-dossier-panel-section-body-assignment.tsx',
    'workshop2-phase1-dossier-panel-material-section-body.tsx',
    'use-workshop2-phase1-dossier-attr-comments-controller.ts',
    'use-workshop2-phase1-dossier-sketch-workspace-state.ts',
    'use-workshop2-phase1-dossier-final-tz-wizard-controller.ts',
    'use-workshop2-phase1-dossier-tz-signoff-zone.ts',
    'use-workshop2-phase1-dossier-active-section-rows.ts',
    'use-workshop2-phase1-dossier-material-bom-zone.ts',
    'use-workshop2-phase1-dossier-handbook-control-zone.ts',
    'use-workshop2-phase1-dossier-section-rows-orchestration.ts',
    'use-workshop2-phase1-dossier-passport-hub-zone.ts',
    'use-workshop2-phase1-dossier-send-handoff-zone.ts',
    'use-workshop2-phase1-dossier-handbook-warnings-zone.ts',
    'workshop2-phase1-dossier-handbook-warnings.ts',
    'use-workshop2-phase1-dossier-section-readiness-zone.ts',
    'workshop2-phase1-dossier-section-readiness.ts',
    'use-workshop2-phase1-dossier-tz-gates-zone.ts',
    'workshop2-phase1-dossier-tz-gates.ts',
    'use-workshop2-phase1-dossier-passport-partitions-zone.ts',
    'workshop2-phase1-dossier-passport-partitions.ts',
    'use-workshop2-phase1-dossier-final-tz-export-zone.ts',
    'workshop2-phase1-dossier-final-tz-export.ts',
    'use-workshop2-phase1-dossier-visuals-catalog-zone.ts',
    'workshop2-phase1-dossier-visuals-catalog.ts',
    'workshop2-phase1-dossier-handbook-check-state.ts',
    'use-workshop2-phase1-dossier-tz-sample-readiness-zone.ts',
    'workshop2-phase1-dossier-tz-sample-readiness.ts',
    'use-workshop2-phase1-dossier-tz-notify-actions-zone.ts',
    'use-workshop2-phase1-dossier-route-urls-zone.ts',
    'use-workshop2-phase1-dossier-handbook-check-report-zone.ts',
    'use-workshop2-phase1-dossier-w2-metrics-flush-context-zone.ts',
    'use-workshop2-phase1-dossier-journal-commit-zone.ts',
    'use-workshop2-phase1-dossier-continue-step-zone.ts',
    'use-workshop2-phase1-dossier-sketch-pin-library-zone.ts',
    'use-workshop2-phase1-dossier-handbook-mutations-zone.ts',
    'use-workshop2-phase1-dossier-mat-catalog-derived-zone.ts',
    'use-workshop2-phase1-dossier-material-sketch-nav-zone.ts',
    'use-workshop2-phase1-dossier-panel-shell-zone.tsx',
    'use-workshop2-phase1-dossier-section-body-zone.tsx',
    'use-workshop2-phase1-dossier-section-body-input-zone.ts',
    'use-workshop2-phase1-dossier-body-shell-props-zone.ts',
    'use-workshop2-phase1-dossier-post-main-trail-props-zone.ts',
  ],
  navigation: [
    'use-workshop2-phase1-dossier-jump-anchors.ts',
    'use-workshop2-phase1-dossier-tz-active-section-zone.ts',
    'use-workshop2-phase1-dossier-tz-minimal-defer-zone.ts',
    'use-workshop2-phase1-dossier-view-nav-zone.ts',
    'use-workshop2-phase1-dossier-save-draft-zone.ts',
    'workshop2-phase1-dossier-panel-tz-dense-nav.tsx',
    'use-workshop2-phase1-dossier-tz-focus-and-hash-scroll-effects.ts',
    'use-workshop2-phase1-dossier-nav-sections-zone.ts',
    'workshop2-phase1-dossier-nav-sections.ts',
  ],
  lifecycle: [
    'Workshop2Phase1DossierPanelRollbackBanner.tsx',
    'use-workshop2-phase1-dossier-factory-pin-toast.ts',
  ],
  persist: [
    'use-workshop2-phase1-dossier-core-state.ts',
    'use-workshop2-phase1-dossier-persist.ts',
    'use-workshop2-phase1-dossier-hydrate-from-storage.ts',
    'workshop2-phase1-dossier-panel-dossier-mutations.ts',
  ],
} as const;

export type Workshop2Phase1DossierPanelDecompositionZone =
  keyof typeof WORKSHOP2_PHASE1_DOSSIER_PANEL_DECOMPOSITION_MANIFEST;
