import { defineConfig, devices } from '@playwright/test';

/** Импорт src/lib в e2e (golden path) — те же флаги, что у dev:core. */
if (!process.env.NEXT_PUBLIC_PLATFORM_CORE_MODE) {
  process.env.NEXT_PUBLIC_PLATFORM_CORE_MODE = '1';
}

const CORE_PORT = process.env.PLAYWRIGHT_CORE_PORT ?? '3001';
const CORE_BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? `http://127.0.0.1:${CORE_PORT}`;

export default defineConfig({
  testDir: './e2e',
  testMatch: [
    '**/core-01-platform-smoke.spec.ts',
    '**/core-02-demo-golden-path.spec.ts',
    '**/core-03-interactive-handoff.spec.ts',
    '**/core-04-legacy-redirects.spec.ts',
    '**/core-05-readiness-slimcore.spec.ts',
    '**/core-06-collections-fw-empty.spec.ts',
    '**/core-07-pg-interactive-bootstrap.spec.ts',
    '**/core-08-section-audit-smoke.spec.ts',
    '**/core-09-chain-status-sse.spec.ts',
    '**/core-10-no-bootstrap-honesty.spec.ts',
    '**/core-11-mes-release-stages.spec.ts',
    '**/core-12-bulk-accept-registry.spec.ts',
    '**/core-13-comms-cross-nav.spec.ts',
    '**/core-14-comms-banner-dedupe.spec.ts',
    '**/core-15-clean-pg-registry.spec.ts',
    '**/core-16-shop-production-visibility.spec.ts',
    '**/core-17-pg-primary-mode.spec.ts',
    '**/core-18-clean-pg-spine-golden-path.spec.ts',
    '**/core-19-clean-pg-spine-full-chain.spec.ts',
    '**/core-20-clean-pg-comms-spine.spec.ts',
    '**/core-21-comms-section-groups.spec.ts',
    '**/core-22-empty-checkout-mfr-po-inbox.spec.ts',
    '**/core-23-calendar-create-task-thread.spec.ts',
    '**/core-24-clean-pg-14-cell-matrix.spec.ts',
    '**/core-25-comms-notifications-supplier-quote.spec.ts',
    '**/core-26-brand-export-fw27-audit-path.spec.ts',
    '**/core-27-pg-hub-wms-confirm.spec.ts',
    '**/core-28-hub-chain-linesheet-batch.spec.ts',
    '**/core-29-publish-audit-disclosure-import.spec.ts',
    '**/core-30-bulk-section-export.spec.ts',
    '**/core-31-supplier-comms-peer-insight.spec.ts',
    '**/core-32-joor-import-registry-export.spec.ts',
    '**/core-33-operational-list-pg-primary.spec.ts',
    '**/core-34-clean-pg-erp-retry.spec.ts',
    '**/core-35-comms-sse-unread-bump.spec.ts',
    '**/core-36-supplier-delivery-confirm.spec.ts',
    '**/core-37-brand-create-article-wizard.spec.ts',
    '**/core-38-shop-showroom-empty-onboarding.spec.ts',
    '**/core-39-clean-pg-section-deep.spec.ts',
    '**/core-40-clean-pg-comms-four-roles.spec.ts',
    '**/core-41-batch-publish-audit-roundtrip.spec.ts',
    '**/core-42-clean-pg-mfr-handoff-shop-floor.spec.ts',
    '**/core-43-clean-pg-po-calendar-export-wms.spec.ts',
    '**/core-44-brand-dev-disclosure-mfr-calendar.spec.ts',
    '**/core-45-brand-showroom-unified-clean-pg-tracking.spec.ts',
    '**/core-46-linesheet-audit-order-comms-thread.spec.ts',
    '**/core-47-pg-collections-retailers-tier.spec.ts',
    '**/core-48-mfr-sup-interaction-comms-thread.spec.ts',
    '**/core-49-brand-op-minimums-clean-pg.spec.ts',
    '**/core-51-prebook-registry.spec.ts',
    '**/core-52-p0-wave-gaps.spec.ts',
    '**/core-53-p0-tz-margin-investor.spec.ts',
    '**/core-54-dual-session-wave-a.spec.ts',
    '**/core-55-manufacturer-erp-clean-pg.spec.ts',
    '**/core-56-logistics-cross-role-tracking.spec.ts',
    '**/core-57-po-status-sse-second-actor.spec.ts',
    '**/core-58-range-planner-tier-drag.spec.ts',
    '**/core-59-erp-retry-ux.spec.ts',
    '**/core-60-wave-c-empty-pdf-comms.spec.ts',
    '**/core-61-wms-reserve-redis.spec.ts',
    '**/core-62-wave-d-dossier-prefs.spec.ts',
    '**/core-63-wave-d-persist-typecheck.spec.ts',
    '**/core-64-wave-d-investor-attr.spec.ts',
    '**/core-65-wave-d-sketch-tz-hooks.spec.ts',
    '**/core-66-wave-d-tz-signoff-tasks.spec.ts',
    '**/core-67-wave-d-material-handbook-hooks.spec.ts',
    '**/core-68-wave-d-section-rows-orchestration.spec.ts',
    '**/core-69-wave-e-tech-debt-passport.spec.ts',
    '**/core-70-wave-f-send-handoff-dev-chrome.spec.ts',
    '**/core-71-wave-g-handbook-nav-split.spec.ts',
    '**/core-72-wave-h-section-readiness-flow.spec.ts',
    '**/core-73-wave-i-tz-gates-roles.spec.ts',
    '**/core-74-wave-j-passport-export.spec.ts',
    '**/core-75-wave-k-visuals-nav.spec.ts',
    '**/core-76-wave-l-tz-sample-readiness.spec.ts',
    '**/core-77-wave-m-tz-notify-cabinet.spec.ts',
    '**/core-78-wave-n-route-urls-tsc.spec.ts',
    '**/core-79-wave-o-handbook-metrics.spec.ts',
    '**/core-80-wave-p-journal-types.spec.ts',
    '**/core-81-wave-q-continue-runway-types.spec.ts',
    '**/core-82-wave-r-sketch-pin-library.spec.ts',
    '**/core-83-wave-s-handbook-mutations.spec.ts',
    '**/core-84-wave-t-mat-shell-zones.spec.ts',
    '**/core-85-wave-u-tz-nav-zones.spec.ts',
    '**/core-86-wave-v-section-layout-zones.spec.ts',
    '**/core-87-wave-w-props-bundles.spec.ts',
    '**/core-88-wave-x-panel-tail.spec.ts',
    '**/core-89-wave-y-section-body-flat.spec.ts',
    '**/core-90-pillar-workspace-pcf.spec.ts',
    '**/core-91-hub-layout-viewports.spec.ts',
    '**/core-92-cabinet-layout-viewports.spec.ts',
    '**/core-93-shop-matrix-smoke.spec.ts',
    '**/core-94-wave-sk-universal-inbox.spec.ts',
    '**/core-95-wave-sl-pg-storage.spec.ts',
    '**/core-96-wave-sn-comms-calendar.spec.ts',
    '**/core-106-wave-su-co-tracking-embed.spec.ts',
    '**/core-97-wave-so-greenfield-matrix.spec.ts',
    '**/core-98-wave-sm-pg-storage.spec.ts',
    '**/core-100-wave-sp-collaborative-working-order.spec.ts',
    '**/core-101-wave-sq-sup-inventory-push.spec.ts',
    '**/core-103-wave-sr-templates-tracking-push.spec.ts',
    '**/core-109-wave-sx-supplier-nav.spec.ts',
    '**/core-110-wave-batch-apis.spec.ts',
    '**/core-112-range-planner-overlay-bulk.spec.ts',
    '**/core-114-wave-tf-linesheet-syndication.spec.ts',
    '**/core-110-wave-sw-comms-prefs-pg.spec.ts',
    '**/core-111-wave-sz-mfr-wip-gantt.spec.ts',
    '**/core-104-wave-ss-wizard-draft-pg.spec.ts',
    '**/core-105-wave-st-matrix-autosave.spec.ts',
    '**/core-107-wave-sv-shop-dev-bridge.spec.ts',
    '**/core-113-wave-tb-replenishment-filter-slices.spec.ts',
    '**/core-114-wave-te-tf-th-batch.spec.ts',
    '**/core-115-wave-tk-tl-tm-batch.spec.ts',
    '**/core-115-wave-tk-pricelist-tier-sync.spec.ts',
    '**/core-116-wave-tl-showroom-eligible-matrix.spec.ts',
    '**/core-117-wave-tn-publish-audit-pg.spec.ts',
    '**/core-118-wave-tp-working-order-merge.spec.ts',
    '**/core-118-wave-tp-working-order-version-diff.spec.ts',
    '**/core-201-wave-xl-working-order.spec.ts',
    '**/core-119-wave-tq-qc-handoff-gate.spec.ts',
    '**/core-120-wave-tr-alt-material-approval.spec.ts',
    '**/core-121-wave-ts-operational-status-mirror.spec.ts',
    '**/core-122-wave-tt-universal-inbox-unread.spec.ts',
    '**/core-204-wave-xo-unread.spec.ts',
    '**/core-123-wave-tv-replenishment-atp-greenfield.spec.ts',
    '**/core-124-wave-tw-chain-pillar-sse.spec.ts',
    '**/core-154-wave-vj-shop-tracking.spec.ts',
    '**/core-125-wave-tx-supplier-op.spec.ts',
    '**/core-126-wave-ty-brand-dev.spec.ts',
    '**/core-127-wave-tz-mfr-dev-op.spec.ts',
    '**/core-128-wave-ua-empty-pillars.spec.ts',
    '**/core-129-wave-uc-brand-co.spec.ts',
    '**/core-130-wave-ud-collaborative-session.spec.ts',
    '**/core-131-wave-ue-brand-sc-matrix.spec.ts',
    '**/core-132-wave-uf-supplier-rfq-sla.spec.ts',
    '**/core-133-wave-ug-brand-op-ledger.spec.ts',
    '**/core-134-wave-uh-comms-threads.spec.ts',
    '**/core-135-wave-ui-shop-checkout.spec.ts',
    '**/core-136-wave-uk-push-prefs.spec.ts',
    '**/core-137-wave-ul-mfr-comms.spec.ts',
    '**/core-138-wave-um-range-planner.spec.ts',
    '**/core-139-wave-un-dossier-diff.spec.ts',
    '**/core-140-wave-up-comms-entity-calendar.spec.ts',
    '**/core-141-wave-uq-mfr-dev-comms.spec.ts',
    '**/core-142-wave-uv-release-gate.spec.ts',
    '**/core-143-wave-uw-partners-invite.spec.ts',
    '**/core-144-wave-ux-inventory-ledger.spec.ts',
    '**/core-145-wave-uy-dossier-tz-export.spec.ts',
    '**/core-146-wave-va-dev-webhook-tasks.spec.ts',
    '**/core-147-wave-vb-rep-commission.spec.ts',
    '**/core-182-wave-ws-rep-payout.spec.ts',
    '**/core-187-wave-wx-commission.spec.ts',
    '**/core-148-wave-vc-brand-sc.spec.ts',
    '**/core-167-wave-wd-syndication.spec.ts',
    '**/core-149-wave-vd-mfr-erp-dashboard.spec.ts',
    '**/core-150-wave-ve-checkout-payment.spec.ts',
    '**/core-151-wave-vf-brand-dev-dashboard.spec.ts',
    '**/core-168-wave-we-investor.spec.ts',
    '**/core-152-wave-vg-supplier-dev.spec.ts',
    '**/core-153-wave-vi-brand-co-rep.spec.ts',
    '**/core-155-wave-vk-push-prefs-pg.spec.ts',
    '**/core-160-wave-vq-brand-op.spec.ts',
    '**/core-161-wave-vr-brand-co-otb.spec.ts',
    '**/core-159-wave-vo-sup-logistics.spec.ts',
    '**/core-157-wave-vm-release-gate-e2e.spec.ts',
    '**/core-169-wave-wf-thread-templates.spec.ts',
    '**/core-173-wave-wj-gantt-wip.spec.ts',
    '**/core-174-wave-wk-material-catalog.spec.ts',
    '**/core-170-wave-wg-replenishment.spec.ts',
    '**/core-162-wave-vs-mfr-empty-pillars.spec.ts',
    '**/core-165-wave-wb-brand-bom-alt.spec.ts',
    '**/core-164-wave-wa-matrix-qty-carry.spec.ts',
    '**/core-166-wave-wc-pctask-deeplinks.spec.ts',
    '**/core-175-wave-wl-brand-amend.spec.ts',
    '**/core-177-wave-wn-tier-sync.spec.ts',
    '**/core-176-wave-wm-collaborative.spec.ts',
    '**/core-158-wave-vn-greenfield-shop2.spec.ts',
    '**/core-156-wave-vl-mfr-dev-dam.spec.ts',
    '**/core-163-wave-vz-audit-closure.spec.ts',
    '**/core-171-wave-wh-size-run.spec.ts',
    '**/core-172-wave-wi-partial-ship.spec.ts',
    '**/core-178-wave-wo-wip-tablet.spec.ts',
    '**/core-179-wave-wp-bom-po.spec.ts',
    '**/core-183-wave-wt-w2-sse.spec.ts',
    '**/core-184-wave-wu-material-request.spec.ts',
    '**/core-188-wave-wy-mfr-comms.spec.ts',
    '**/core-185-wave-wv-dev-bridge.spec.ts',
    '**/core-180-wave-wq-release-gate.spec.ts',
    '**/core-181-wave-wr-s1-ls-purge.spec.ts',
    '**/core-186-wave-ww-sup-empty.spec.ts',
    '**/core-189-wave-wz-ru-dedup.spec.ts',
    '**/core-190-wave-xa-partners-invite.spec.ts',
    '**/core-191-wave-xb-crm-segments.spec.ts',
    '**/core-192-wave-xc-sample-patch.spec.ts',
    '**/core-193-wave-xd-rfq-sla.spec.ts',
    '**/core-194-wave-xe-s1-sweep.spec.ts',
    '**/core-195-wave-xf-tasks-kanban.spec.ts',
    '**/core-196-wave-xg-range-planner.spec.ts',
    '**/core-197-wave-xh-showroom-logo.spec.ts',
    '**/core-202-wave-xm-supplier-link.spec.ts',
    '**/core-203-wave-xn-dossier-comments.spec.ts',
    '**/core-198-wave-xi-prod-ops.spec.ts',
    '**/core-199-wave-xj-stage-modules.spec.ts',
    '**/core-200-wave-xk-accept-invite.spec.ts',
    '**/core-205-wave-xp-audit-8.spec.ts',
    '**/core-206-wave-xq-dossier-core.spec.ts',
    '**/core-207-wave-xr-process-runtime.spec.ts',
    '**/core-208-wave-xs-readpath.spec.ts',
    '**/core-209-wave-xt-matrix-autosave.spec.ts',
    '**/core-210-wave-xu-tz-print.spec.ts',
    '**/core-211-wave-xv-otb-sync.spec.ts',
    '**/core-212-wave-xw-alt-material.spec.ts',
    '**/core-213-wave-xx-greenfield.spec.ts',
    '**/core-214-wave-xy-tracking-embed.spec.ts',
    '**/core-215-wave-xz-templates.spec.ts',
    '**/core-216-wave-ya-mfr-dossier.spec.ts',
    '**/core-217-wave-yb-inventory-overlay.spec.ts',
    '**/core-218-wave-yc-subcontractor.spec.ts',
    '**/core-219-wave-yd-sku-wizard.spec.ts',
    '**/core-220-wave-ye-audit-final.spec.ts',
    '**/core-221-wave-yf-compact.spec.ts',
    '**/core-222-wave-yg-partner-count.spec.ts',
    '**/core-223-wave-yh-wms-reserve.spec.ts',
    '**/core-225-wave-yj-sup-op.spec.ts',
    '**/core-226-wave-yk-shop-co.spec.ts',
    '**/core-224-wave-yi-e2e-smoke-registry.spec.ts',
    '**/core-227-wave-yl-dossier-diff.spec.ts',
    '**/core-228-wave-ym-empty27.spec.ts',
    '**/core-229-wave-yn-contextual-thread.spec.ts',
    '**/core-230-wave-yo-sup-comms.spec.ts',
    '**/core-231-wave-yp-cross-links.spec.ts',
    '**/core-232-wave-yq-hub-matrix-5x4.spec.ts',
    '**/core-232-wave-yq-checkout.spec.ts',
    '**/core-233-wave-yr-cell-dashboard.spec.ts',
    '**/core-233-wave-yr-matrix-cta.spec.ts',
    '**/core-234-wave-ys-planner-sync.spec.ts',
    '**/core-234-wave-ys-dev-status.spec.ts',
    '**/core-235-wave-yt-noise.spec.ts',
    '**/core-235-wave-yt-notifications.spec.ts',
    '**/core-236-wave-yu-sup-op-80.spec.ts',
    '**/core-237-wave-yv-shop-co-80.spec.ts',
    '**/core-238-wave-yw-battle-ready.spec.ts',
    '**/core-239-wave-yx-dead-ends.spec.ts',
    '**/core-240-wave-yu-mini-matrix.spec.ts',
    '**/core-240-wave-yy-hub-live-smoke.spec.ts',
    '**/core-241-wave-yz-scores.spec.ts',
    '**/core-242-wave-za-adr.spec.ts',
    '**/core-244-wave-zc-shop-co-80.spec.ts',
    '**/core-245-wave-zd-links.spec.ts',
    '**/core-246-wave-ze-ru.spec.ts',
    '**/core-247-wave-zf-planner.spec.ts',
    '**/core-248-wave-yv-mfr-empty.spec.ts',
    '**/core-248-wave-yt-notifications.spec.ts',
    '**/core-249-wave-5-golden-cross-role-embedded.spec.ts',
    '**/core-249-extended-roles-golden.spec.ts',
  ],
  timeout: 120_000,
  fullyParallel: false,
  retries: 1,
  workers: 1,
  reporter: [['list']],
  use: {
    baseURL: CORE_BASE_URL,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], viewport: { width: 1280, height: 900 } },
    },
  ],
  webServer: process.env.PLAYWRIGHT_SKIP_WEBSERVER
    ? undefined
    : {
        command: 'bash scripts/start-dev-core-e2e.sh',
        url: `${CORE_BASE_URL}/platform`,
        reuseExistingServer: true,
        timeout: 180_000,
        stdout: 'pipe',
        stderr: 'pipe',
      },
});
