/**
 * Закрытые пункты планировщика (e2e / PG-primary волна 2026-06).
 * Авто-status `done` — устойчиво к повторному analyze и смене slug id.
 */
/** Версия закрытой e2e-волны; bump при изменении auto-done registry. */
export const PLATFORM_CORE_PLANNER_CLOSED_WAVE_GENERATION = 75;

export const PLATFORM_CORE_PLANNER_AUTO_DONE_PATTERNS: readonly RegExp[] = [
  /нет e2e mes.*empty27/i,
  /prebook row e2e/i,
  /prebook.*e2e.*seed/i,
  /prebook badge e2e/i,
  /реестр оптовых заказов:.*prebook/i,
  /карточка заказа:.*prebook/i,
  /нет pg-primary store/i,
  /pg-primary.*native b2b/i,
  /b2b operational orders.*mockb2borders/i,
  /json snapshot.*mockb2borders/i,
  /e2e на чистой pg/i,
  /e2e опирается на core:prep/i,
  /e2e без seed/i,
  /матрица оптового заказа: e2e без seed/i,
  /brand-sample-collection-mini-matrix/i,
  /deep-link checkout e2e/i,
  /mini-карточка без e2e.*matrix/i,
  /shop-showroom-mini-partner/i,
  /shop-showroom-empty-state/i,
  /нет e2e hero\/partner.*showroom mini/i,
  /partner badge.*showroom/i,
  /eligible badge.*showroom/i,
  /contextual.*in-memory.*json/i,
  /contextual chat.*pg primary/i,
  /e2e supplier messages/i,
  /supplier messages banner dedupe/i,
  /e2e factory messages/i,
  /чат · заказ:.*dedupe/i,
  /чат · артикул:.*dedupe/i,
  /нет e2e на дедуп/i,
  /investor pdf export/i,
  /investor brief pdf/i,
  /brief\.pdf api/i,
  /investor-summary.*svg/i,
  /margin range planner.*tier/i,
  /цех разработки.*tz pdf export/i,
  /досье артикула.*pdf export composition/i,
  /pdf\/svg export.*e2e/i,
  /e2e tier assign после create/i,
  /quick-create.*tier assign/i,
  /витрина коллекции:.*partner badge/i,
  /нет e2e hero/i,
  /производственные заказы:.*empty27/i,
  /empty27.*skip mes/i,
  /empty27.*честный skip mes/i,
  /native b2b orders.*pg/i,
  /banner dedupe/i,
  /order= dedupe/i,
  /dedupe strict/i,
  /dedupe assert/i,
  /нет e2e assert.*дубля баннера/i,
  /нет e2e.*дедуп/i,
  /сквозного e2e в одной бд/i,
  /pdf export composition label/i,
  /margin range planner.*нет e2e/i,
  /patch margin.*core\/trend\/novelty/i,
  /tier assign/i,
  /quick-create.*range tier assign/i,
  /factory dossier export meta/i,
  /export meta/i,
  /e2e dossier portal sku/i,
  /e2e export tz/i,
  /end-to-end flow в одной бд/i,
  /закрыто: core-/i,
  /\(закрыто:/i,
  /contextual post→get/i,
  /erp auto-retry backoff после bulk handoff/i,
  /core-(0[0-9]|[1-5][0-9])|core-5[0-8]|core-57|core-58/i,
  /weighted bom completeness/i,
  /materials-bom-weighted-fill-rate/i,
  /fill-rate без весов по критичности/i,
  /кабинет · bom образца:.*fill-rate без весов/i,
  /navigate to registry после bulk ack/i,
  /очередь передачи:.*navigate to registry/i,
  /bulk erp retry для всех attention/i,
  /производственные заказы:.*bulk erp retry/i,
  /seed b2b для shop2/i,
  /shop2 без seed-заказов/i,
  /auto-retry erp с backoff/i,
  /partner display names/i,
  /display names частично preset/i,
  /sse\/poll badge materials_supplied/i,
  /закупка · patch:.*inventory reserve/i,
  /push при смене reserve status/i,
  /pre-orders отдельный маршрут/i,
  /реестр оптовых заказов:.*pre-orders/i,
  /карточка заказа:.*pre-orders/i,
  /свести sse badge к одному месту/i,
  /sender.*current user/i,
  /contextual sender fallback/i,
  /участник.*contextual/i,
  /contextual chat.*real-time/i,
  /contextual chat без real-time/i,
  /contextual chat sse/i,
  /contextual-chat-sse-live-badge/i,
  /multi-article wizard/i,
  /materials_supplied.*sse push/i,
  /этап · materials_supplied.*sse/i,
  /inventory reserve post-handoff/i,
  /inventory reserve \(волна d\)/i,
  /empty linesheet fallback/i,
  /shop peer picker/i,
  /shop-co-checkout-buyer-picker/i,
  /multi-buyer checkout/i,
  /invoice pdf.*jspdf/i,
  /invoice pdf.*schet-offerta/i,
  /b2b invoice.*pdf pipeline/i,
  /invoice-stub.*не production pdf/i,
  /invoice pdf — stub/i,
  /убрать legacy pre-orders из golden cta/i,
  /hub gadget.*единое/i,
  /role-pillar-section-links/i,
  /разделы столпа.*hub/i,
  /development.*два strip/i,
  /brand-dev-cross-context/i,
  /showroom.*golden.*path/i,
  /pre-order.*coremode/i,
  /каталог pre-order/i,
  /placeholder.*тред/i,
  /comms hub.*empty/i,
  /tracking.*без чата/i,
  /op hub.*чат.*comms/i,
  /supplier.*compact.*spine/i,
  /empty pdf edge cases/i,
  /лайншиты.*empty pdf/i,
  /uat linesheet.*showroom diff/i,
  /дубль.*showroom.*linesheets/i,
  /op-pillar.*календарь/i,
  /календарь.*order_production/i,
  /tracking.*calendar link/i,
  /дубль.*calendar-context/i,
  /сохранение своих шаблонов/i,
  /quote templates/i,
  /checkout.*jwt/i,
  /production jwt middleware/i,
  /production jwt guard/i,
  /po bundle pdf/i,
  /publish audit log на w2 hub/i,
  /uat linesheet.*showroom diff/i,
  /preview qty.*linesheet/i,
  /preview qty в linesheet/i,
  /досье · техзадание: pdf bundle/i,
  /pdf bundle \(сейчас plain-text\)/i,
  /tz-handoff-summary\.pdf/i,
  /batch acknowledge delivery/i,
  /cross-role showroom.*matrix/i,
  /uat cross-role showroom/i,
  /inline qty preview modal/i,
  /preview qty modal/i,
  /shop-co-buyer-delivery-batch-ack/i,
  /синхрон counts mini\/page/i,
  /uat cabinet.*full pages/i,
  /ux noise reduction/i,
  /дубль mini vs полная/i,
  /дубль с linesheets/i,
  /brand crm invite/i,
  /brand-co-registry-invite/i,
  /shop-op-registry.*дубль/i,
  /uat cabinet.*showroom golden/i,
  /crm\/invite flow/i,
  /partners-invite-panel/i,
  /shop-co-registry-partners-link/i,
  /uat brand peer.*shop checkout/i,
  /cross-role-audit-uat-checkout/i,
  /сводная матрица сезона/i,
  /shop-co-season-matrix/i,
  /showroom quick-add.*matrix scroll/i,
  /seed b2b.*shop2/i,
  /shop-co-tracking-reserve/i,
  /audit log не на w2 hub/i,
  /нет inline preview matrix/i,
  /нет read-only matrix peek modal/i,
  /uat cross-role showroom.*matrix/i,
  /uat partners.*showroom golden/i,
  /acknowledge delivery batch/i,
  /api процессов.*postgres/i,
  /comms workspace.*strip/i,
  /order\/article strip/i,
  /comms.*auto-thread/i,
  /registry.*hubgadget/i,
  /registry context strip/i,
  /handoff strip.*чат/i,
  /дубль чата.*chain/i,
  /empty.*onboarding.*compact/i,
  /brand-dev-empty.*4 cta/i,
  /дубль.*comms.*banner/i,
  /showroom.*footer.*cta/i,
  /linesheets.*context strip/i,
  /w2-hub.*linesheets.*дубль/i,
  /dev session banner.*golden/i,
  /td-noise-session-banner/i,
  /storage stale.*platform core/i,
  /shop-co-matrix-context-strip/i,
  /matrix header.*showroom/i,
  /checkout.*hubgadget/i,
  /shop golden path.*matrix/i,
  /order detail.*footer.*chat/i,
  /shop-co-detail-footer-chat/i,
  /factory calendar.*chat.*strip/i,
  /factory-calendar-chat-link/i,
  /op-cabinet-sse.*compact/i,
  /дубль sse.*hub/i,
  /factory-production-orders-chat/i,
  /sup-op-procurement.*chat/i,
  /tracking.*chat.*row/i,
  /shop-co-tracking-chat/i,
  /mfr-op-materials-chat/i,
  /procurement context strip.*hubgadget/i,
  /placeholder.*тред/i,
  /comms.*placeholder.*thread/i,
  /placeholders: !coreMode/i,
  /synthetic placeholder/i,
  /calendar-pg-required-hint/i,
  /platformCoreWorkspace.*production-context/i,
  /publish-audit.*w2 hub/i,
  /журнал публикаций.*hub/i,
  /invite.*golden.*strip/i,
  /registry-invite.*context-strip/i,
  /retail header.*cabinet/i,
  /b2c header.*platform core/i,
  /ассортимент.*loyalty.*header/i,
  /golden strip.*кабинет.*дубль/i,
  /role-cabinet-golden-path/i,
  /integrations import.*registry.*core/i,
  /omitStep.*golden.*strip/i,
  /comms compact.*cta.*дубль/i,
  /pre-orders.*redirect.*b2b/i,
  /pre-orders side-path.*redirect/i,
  /redirect.*pre-orders.*b2b-orders/i,
  /order detail.*footer cross/i,
  /shop-co-detail-cross-links/i,
  /calendar.*memory.*создан/i,
  /calendar tasks memory-only/i,
  /создание слота.*postgresql/i,
  /platformCoreTaskCreateEnabled/i,
  /cross-role только.*comms/i,
  /listchrome.*comms.*cross-role/i,
  /role cabinet.*без cross-role/i,
  /дубль showroom.*linesheets/i,
  /omitStep.*linesheets/i,
  /pre-orders panel.*redirect/i,
  /mini.*golden.*strip.*compact/i,
  /linesheets.*batch.*w2/i,
  /publish.*w2 hub/i,
  /cabinet.*cta.*goldenPath/i,
  /order production.*compact.*goldenPath/i,
  /brand-op-cabinet-cta-strip.*goldenPath/i,
  /showroom.*mode.*label/i,
  /linesheets.*mode.*label/i,
  /collection-chip.*slim/i,
  /erpNextRetryAt.*auto-retry/i,
  /erp auto-retry hint/i,
  /дубль.*badge.*compact.*hub/i,
  /op-cabinet.*wms.*compact/i,
  /order detail.*context strip.*chain card/i,
  /brand-co-chain-context-strip/i,
  /registry.*chat.*strip/i,
  /brand-op-registry-chat-link/i,
  /дубль.*materials.*badge.*chain/i,
  /chain card.*slim.*core/i,
  /registry.*row.*chat.*core/i,
  /b2b-order-chat.*coreMode/i,
  /thread preview.*registry.*core/i,
  /tracking.*compactHeaderBadges/i,
  /чат.*реестр.*карточка/i,
  /sup-op-chain-workspace.*core/i,
  /materials.*chain workspace.*core/i,
  /tracking.*production-link.*coreSlim/i,
  /tracking.*sse.*coreSlim/i,
  /order detail context strips.*удал/i,
  /registry empty.*коротк/i,
  /shop.*amend.*card.*core/i,
  /дубль.*amend.*chain/i,
  /po card.*коротк/i,
  /chain.*production.*link.*coreSlim/i,
  /order detail.*amend.*скрыт/i,
  /mfr-op-cabinet-chat.*coreSlim/i,
  /handoff-queue-chat.*core/i,
  /materials-procurement-chat.*core/i,
  /dossier.*chat.*core.*golden/i,
  /fw27.*banner.*коротк/i,
  /order chat context strip.*удал/i,
  /nav unify.*волна 31/i,
  /shop partners.*syntha-cores/i,
  /archiveExcept.*withCoreClusterId/i,
  /единая витрина.*матрица.*pim/i,
  /тройной showroom/i,
  /linesheets.*заказы b2b/i,
  /партнёры.*core.*onboarding/i,
  /sidebar.*столп.*hub/i,
  /shop b2b.*трекинг/i,
  /brand b2b.*оптовые заказы/i,
  /nav unify.*волна 32/i,
  /shop partners.*discover.*apply/i,
  /manufacturer.*handoff.*dossier/i,
  /supplier.*procurement.*flat/i,
  /ритейлеры.*b2b/i,
  /hub pillar.*sidebar/i,
  /ui-mirror.*peer.*chain/i,
  /chain-peer-mirror/i,
  /tracking.*calendar.*order=/i,
  /shop-co-tracking-calendar-link/i,
  /brand-co-chain-peer-mirror/i,
  /calendar tasks.*pg.*restart/i,
  /listPlatformCoreUserCalendarTasks.*postgres/i,
  /auxiliaryStores.*calendarTasks/i,
  /wave a.*calendar.*kanban.*pg/i,
  /волна 34/i,
  /development-status-stream/i,
  /brand-dev-development-sse-live-badge/i,
  /bumpPlatformCoreDevelopmentStatus/i,
  /push при смене статуса образца/i,
  /волна 35/i,
  /shop-sc-partners-request-access/i,
  /shop-sc-partners-connect-demo/i,
  /shop_b2b_partnerships/i,
  /partnership.*onboarding.*pg/i,
  /profile.*connected.*partnership/i,
  /волна 36/i,
  /core-54-dual-session/i,
  /dual-session wave a/i,
  /shop-co-registry-tracking-link/i,
  /brand-tasks-kanban-pg/i,
  /brand confirm.*shop.*peer mirror/i,
  /calendar.*restart.*pg/i,
  /волна 37/i,
  /core-55-manufacturer-erp/i,
  /manufacturer erp retry clean-pg/i,
  /clean-pg.*factory.*erp retry/i,
  /factory-handoff-row-B2B-/i,
  /волна 38/i,
  /core-56-logistics/i,
  /logistics cross-role tracking/i,
  /brand-co-logistics-tracking/i,
  /shop-co-tracking-shipment/i,
  /shop-co-chain-peer-po-synced/i,
  /волна 39/i,
  /core-57-po-status/i,
  /po status sse.*second-actor/i,
  /shop-co-chain-peer-po-pending/i,
  /shop-co-chain-peer-status-summary/i,
  /platform-core-placeholder-shop/i,
  /волна 40/i,
  /core-58-range-planner/i,
  /range-planner-tier-article-board/i,
  /range-planner-tier-move-/i,
  /drag-reorder.*tier/i,
  /планировщик ассортимента.*drag/i,
  /волна 41/i,
  /core-59-erp-retry/i,
  /brand-b2b-erp-pending-hint/i,
  /mfr-op-handoff-queue-erp-backoff-hint/i,
  /factory-production-orders-erp-backoff-hint/i,
  /erp ux.*backoff/i,
  /волна 42/i,
  /core-60-wave-c/i,
  /brand-sc-linesheets-empty-pdf-hint/i,
  /shop-cm-notification-center-compact/i,
  /empty27 linesheets pdf/i,
  /rfq.*только чат/i,
  /rfq вне platform core/i,
  /platform-core-placeholder-brand-analytics/i,
  /волна 43/i,
  /core-61-wms-reserve/i,
  /platform-core-wms-reserve-copy/i,
  /comms-inbox-stream/i,
  /platform-core-comms-inbox-hub/i,
  /realtimeHubs.*comms-inbox/i,
  /sup-op-cabinet-wms-reserve-badge.*PG/i,
  /волна 44/i,
  /core-62-wave-d/i,
  /workshop2-phase1-dossier-panel-decomposition-manifest/i,
  /shop-cm-notification-prefs/i,
  /platform-core-comms-notification-prefs/i,
  /Workshop2Phase1DossierPanelRollbackBanner/i,
  /волна 45/i,
  /core-63-wave-d/i,
  /use-workshop2-phase1-dossier-core-state/i,
  /typecheck:platform-core/i,
  /brand-op-bom-preview-badge.*материалы/i,
  /волна 46/i,
  /core-64-wave-d/i,
  /use-workshop2-phase1-dossier-attr-comments-controller/i,
  /workshop2-investor-summary-page/i,
  /investor-summary read-only/i,
  /investor demo banner.*platform core/i,
  /Workshop2InvestorDemoHubBanner.*isPlatformCoreMode/i,
  /волна 47/i,
  /core-65-wave-d/i,
  /use-workshop2-phase1-dossier-sketch-workspace-state/i,
  /use-workshop2-phase1-dossier-final-tz-wizard-controller/i,
  /typecheck:ci.*platform-core/i,
  /tsconfig\.ci.*__tests__/i,
  /волна 48/i,
  /core-66-wave-d/i,
  /use-workshop2-phase1-dossier-tz-signoff-zone/i,
  /brand-tasks-core-calendar-strip/i,
  /tsconfig\.typecheck.*_archive/i,
  /волна 49/i,
  /core-67-wave-d/i,
  /use-workshop2-phase1-dossier-material-bom-zone/i,
  /use-workshop2-phase1-dossier-handbook-control-zone/i,
  /use-workshop2-phase1-dossier-active-section-rows/i,
  /material BOM hub.*control points/i,
  /декомпозиция.*section rows/i,
  /волна 50/i,
  /core-68-wave-d/i,
  /use-workshop2-phase1-dossier-section-rows-orchestration/i,
  /renderPhaseRow bundle/i,
  /platform-core-planner.*techDebt/i,
  /B2bChainPhaseBadge.*tracking/i,
  /волна 51/i,
  /core-69-wave-e/i,
  /use-workshop2-phase1-dossier-passport-hub-zone/i,
  /platform-core-tech-debt-closure/i,
  /Brand tasks Kanban.*localStorage.*закрыто/i,
  /Auxiliary stores без PG.*закрыто/i,
  /Create-article wizard.*закрыто/i,
  /placeholder-data.*закрыто.*demo badge/i,
  /CROSS_ROLE_FLOWS.*закрыто/i,
  /EMPTY27.*BrandDevEmptyChainOnboarding/i,
  /typecheck:w2.*platform-core gate/i,
  /typecheck:order-subset.*gate/i,
  /Tasks Kanban в localStorage.*закрыто/i,
  /волна 52/i,
  /core-70-wave-f/i,
  /use-workshop2-phase1-dossier-send-handoff-zone/i,
  /DevOnlyChrome.*isPlatformCoreGoldenPath/i,
  /Дубли demo-id.*закрыто/i,
  /Dev-баннеры.*golden path suppress/i,
  /CommsPillarThreadStrip.*analyze:code-scan/i,
  /comms-hub-inbox-rows\.test.*noise/i,
  /волна 53/i,
  /core-71-wave-g/i,
  /use-workshop2-phase1-dossier-handbook-warnings-zone/i,
  /workshop2-phase1-dossier-handbook-warnings/i,
  /platform-core-hub-matrix-role-pillar-hrefs/i,
  /b2b-workspace-matrix-tabs/i,
  /materials-core.*SupplierBomLineInput/i,
  /волна 54/i,
  /core-72-wave-h/i,
  /use-workshop2-phase1-dossier-section-readiness-zone/i,
  /workshop2-phase1-dossier-section-readiness/i,
  /b2b-workspace-matrix-flow/i,
  /materials-core.*materialName.*trim/i,
  /волна 55/i,
  /core-73-wave-i/i,
  /use-workshop2-phase1-dossier-tz-gates-zone/i,
  /workshop2-phase1-dossier-tz-gates/i,
  /b2b-workspace-matrix-roles/i,
  /role-hub-matrix.*закрыто/i,
  /волна 56/i,
  /core-74-wave-j/i,
  /use-workshop2-phase1-dossier-passport-partitions-zone/i,
  /workshop2-phase1-dossier-passport-partitions/i,
  /use-workshop2-phase1-dossier-final-tz-export-zone/i,
  /workshop2-phase1-dossier-final-tz-export/i,
  /волна 57/i,
  /core-75-wave-k/i,
  /use-workshop2-phase1-dossier-visuals-catalog-zone/i,
  /workshop2-phase1-dossier-visuals-catalog/i,
  /use-workshop2-phase1-dossier-nav-sections-zone/i,
  /workshop2-phase1-dossier-handbook-check-state/i,
  /dossier-panel.*закрыто.*99/i,
  /волна 58/i,
  /core-76-wave-l/i,
  /use-workshop2-phase1-dossier-tz-sample-readiness-zone/i,
  /workshop2-phase1-dossier-tz-sample-readiness/i,
  /HubSidebarHeaderProps/i,
  /волна 59/i,
  /core-77-wave-m/i,
  /use-workshop2-phase1-dossier-tz-notify-actions-zone/i,
  /CabinetHubTitleRowProps/i,
  /HubSidebar.*sidebarClusters/i,
  /волна 60/i,
  /core-78-wave-n/i,
  /use-workshop2-phase1-dossier-route-urls-zone/i,
  /ROUTES\.client\.sewingPatterns/i,
  /full tsc.*sewing-patterns.*shop.*messages/i,
  /волна 61/i,
  /core-79-wave-o/i,
  /use-workshop2-phase1-dossier-handbook-check-report-zone/i,
  /use-workshop2-phase1-dossier-w2-metrics-flush-context-zone/i,
  /distributor.*orders.*paramsPromise/i,
  /ShopSidebar.*ariaLabel/i,
  /волна 62/i,
  /core-80-wave-p/i,
  /use-workshop2-phase1-dossier-journal-commit-zone/i,
  /ProductScrollSwitcherSection.*heroUrl/i,
  /normalizeAuthRoles.*FastApiSessionProfile/i,
  /волна 63/i,
];

export function isPlatformCorePlannerAutoDoneTitle(title: string): boolean {
  const t = title.trim();
  if (!t) return false;
  return PLATFORM_CORE_PLANNER_AUTO_DONE_PATTERNS.some((re) => re.test(t));
}

/** Закрытая e2e-волна — не показывать в очереди planner (даже как «Готово»). */
export function isPlatformCorePlannerClosedWaveTitle(title: string): boolean {
  return isPlatformCorePlannerAutoDoneTitle(title);
}
