import type { CoreChainRoleId, CoreHubPillarId } from '@/lib/platform-core-hub-matrix';

/** Записи от агентов / Cursor — дополняйте массив ниже. */
export type PlatformCorePlannerAgentItem = {
  id: string;
  kind?: 'improve' | 'add' | 'stage' | 'existing';
  priority?: 'P0' | 'P1' | 'P2';
  title: string;
  roleId?: CoreChainRoleId;
  pillarId?: CoreHubPillarId;
  href?: string;
  status?: 'open' | 'in_progress' | 'done';
};

/**
 * Скан Platform Core / workshop2 spine (2026-06): блокеры сквозной цепочки в одной БД.
 * Evidence — пути в монорепо `_ai-share/synth-1-full`.
 */
export const PLATFORM_CORE_PLANNER_AGENT_ITEMS: PlatformCorePlannerAgentItem[] = [
  {
    id: 'agent-comms-chat-memory',
    kind: 'improve',
    priority: 'P2',
    title: 'Чат contextual: PG primary (закрыто: core-52 POST→GET round-trip)',
    roleId: 'brand',
    pillarId: 'comms',
    href: '/brand/messages',
    status: 'done',
  },
  {
    id: 'agent-comms-sender-hardcoded',
    kind: 'improve',
    priority: 'P1',
    title: "Contextual sender fallback «Участник» (workshop2-contextual-message-sender, не Current User)",
    roleId: 'brand',
    pillarId: 'comms',
    href: '/brand/messages',
    status: 'done',
  },
  {
    id: 'agent-comms-no-realtime',
    kind: 'add',
    priority: 'P1',
    title: 'Contextual chat SSE + poll fallback (`/api/messages/contextual/stream`, contextual-chat-sse-live-badge)',
    roleId: 'brand',
    pillarId: 'comms',
    href: '/brand/messages',
    status: 'done',
  },
  {
    id: 'agent-brand-tasks-localstorage',
    kind: 'improve',
    priority: 'P1',
    title: 'Tasks Kanban в localStorage (brand_tasks_kanban_v1), не API/PG (закрыто: PG API)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/tasks',
    status: 'done',
  },
  {
    id: 'agent-b2b-orders-json-snapshot',
    kind: 'improve',
    priority: 'P2',
    title: 'B2B operational orders: PG-primary (закрыто: core-33/52)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
  {
    id: 'agent-b2b-invoice-pdf-stub',
    kind: 'improve',
    priority: 'P1',
    title: 'Invoice PDF — jsPDF schet-offerta.pdf API (закрыто: core-52)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
  {
    id: 'agent-b2b-orders-no-pg',
    kind: 'add',
    priority: 'P2',
    title: 'Native B2B orders PG SoT (закрыто: workshop2_b2b_orders + core-33/52)',
    roleId: 'brand',
    pillarId: 'collection_order',
    href: '/brand/b2b-orders',
    status: 'done',
  },
  {
    id: 'agent-spine-no-single-pg-e2e',
    kind: 'add',
    priority: 'P2',
    title: 'E2E в одной БД (закрыто: core-15/52 contextual PG)',
    pillarId: 'development',
    href: '/',
    status: 'done',
  },
  {
    id: 'agent-dossier-file-legacy',
    kind: 'improve',
    priority: 'P1',
    title:
      'phase1-dossier PG-only banner + fail-closed file fallback (workshop2-core-dossier-file-persist-banner)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/production/workshop2',
    status: 'done',
  },
  {
    id: 'agent-no-pg-json-fallback',
    kind: 'improve',
    priority: 'P1',
    title:
      'Без PG — dossier file persist banner + WORKSHOP2_PG_ONLY block (не prod-ready)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/production/workshop2',
    status: 'done',
  },
  {
    id: 'agent-brand-sc-linesheet-diff',
    kind: 'improve',
    priority: 'P1',
    title: 'Лайншиты · коллекция: UAT linesheet→showroom diff panel',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/linesheets',
    status: 'done',
  },
  {
    id: 'agent-brand-sc-preview-qty',
    kind: 'improve',
    priority: 'P1',
    title: 'Витрина бренда: Preview qty в linesheet (brand-sc-linesheets-preview-qty-*)',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/linesheets',
    status: 'done',
  },
  {
    id: 'agent-mfr-tz-pdf-bundle',
    kind: 'improve',
    priority: 'P1',
    title: 'Досье · техзадание: PDF bundle tz-handoff-summary.pdf в export-tz-bundle',
    roleId: 'manufacturer',
    pillarId: 'order_production',
    href: '/factory/production/dossier',
    status: 'done',
  },
  {
    id: 'agent-brand-create-article-wizard',
    kind: 'add',
    priority: 'P1',
    title: 'Wizard создания артикула: нет сквозного core-path (EMPTY27 / hub onboarding)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/production/workshop2',
    status: 'done',
  },
  {
    id: 'agent-comms-b2b-saved-templates',
    kind: 'improve',
    priority: 'P1',
    title: 'Чат · оптовый заказ: сохранение своих шаблонов (localStorage + slimCore bar)',
    roleId: 'brand',
    pillarId: 'comms',
    href: '/brand/messages',
    status: 'done',
  },
  {
    id: 'agent-supplier-quote-templates',
    kind: 'improve',
    priority: 'P1',
    title: 'Чат · заказ: Quote templates (shared slimCore templates + custom save)',
    roleId: 'supplier',
    pillarId: 'comms',
    href: '/supplier/messages',
    status: 'done',
  },
  {
    id: 'agent-shop-checkout-jwt',
    kind: 'improve',
    priority: 'P1',
    title: 'Checkout · отправка бренду: Production JWT guard на cart checkout API',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/checkout',
    status: 'done',
  },
  {
    id: 'agent-supplier-po-bundle-pdf',
    kind: 'improve',
    priority: 'P1',
    title: 'BOM × PO · прогресс: PO bundle PDF (po-bundle.pdf API)',
    roleId: 'supplier',
    pillarId: 'order_production',
    href: '/factory/production/materials',
    status: 'done',
  },
  {
    id: 'agent-brand-w2-publish-audit',
    kind: 'improve',
    priority: 'P1',
    title: 'Публикация · витрина: Publish audit log на W2 hub',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/production/workshop2',
    status: 'done',
  },
  {
    id: 'agent-brand-cross-role-uat',
    kind: 'improve',
    priority: 'P1',
    title: 'Витрина бренда: UAT cross-role showroom→matrix via audit path',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/showroom',
    status: 'done',
  },
  {
    id: 'agent-brand-matrix-qty-preview',
    kind: 'improve',
    priority: 'P1',
    title: 'Cross-role · матрица: Inline qty preview modal (brand-sc-matrix-qty-preview-dialog)',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/showroom',
    status: 'done',
  },
  {
    id: 'agent-shop-batch-delivery-ack',
    kind: 'improve',
    priority: 'P1',
    title: 'Трекинг покупателя · PO: Batch acknowledge delivery (shop-co-buyer-delivery-batch-ack)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
  {
    id: 'agent-brand-cabinet-count-sync',
    kind: 'improve',
    priority: 'P1',
    title: 'Кабинет · лайншит и витрина: Синхрон counts mini/page (brand-sc-cabinet-published-sync)',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/core-cabinet',
    status: 'done',
  },
  {
    id: 'agent-brand-cabinet-golden-path',
    kind: 'improve',
    priority: 'P1',
    title: 'Кабинет · лайншит и витрина: UAT cabinet → full pages (brand-sc-cabinet-golden-path)',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/core-cabinet',
    status: 'done',
  },
  {
    id: 'agent-shop-cabinet-count-sync',
    kind: 'improve',
    priority: 'P1',
    title: 'Кабинет · витрина: Синхрон counts mini/page (shop-sc-cabinet-published-sync)',
    roleId: 'shop',
    pillarId: 'sample_collection',
    href: '/shop/core-cabinet',
    status: 'done',
  },
  {
    id: 'agent-shop-cabinet-golden-path',
    kind: 'improve',
    priority: 'P1',
    title: 'Каталог партнёров: UAT partners→showroom golden path (shop-sc-cabinet-golden-path)',
    roleId: 'shop',
    pillarId: 'sample_collection',
    href: '/shop/b2b/partners/discover',
    status: 'done',
  },
  {
    id: 'agent-shop-crm-invite',
    kind: 'improve',
    priority: 'P1',
    title: 'Реестр оптовых заказов: CRM/invite flow (shop-co-registry-partners-link + invite panel)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/partners/discover',
    status: 'done',
  },
  {
    id: 'agent-brand-cross-role-checkout-uat',
    kind: 'improve',
    priority: 'P1',
    title: 'Cross-role · матрица: UAT brand peer → shop checkout e2e (core-52)',
    roleId: 'brand',
    pillarId: 'sample_collection',
    href: '/brand/showroom',
    status: 'done',
  },
  {
    id: 'agent-shop-season-matrix',
    kind: 'improve',
    priority: 'P1',
    title: 'Матрица оптового заказа: Сводная матрица сезона (shop-co-season-matrix-strip)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/matrix',
    status: 'done',
  },
  {
    id: 'agent-shop-reserve-push',
    kind: 'improve',
    priority: 'P1',
    title: 'Push при смене reserve status (chain SSE + shop-co-tracking-reserve-*)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
  {
    id: 'agent-shop-showroom-quick-add-uat',
    kind: 'improve',
    priority: 'P1',
    title: 'Переход · матрица: UAT showroom quick-add → matrix scroll (core-52)',
    roleId: 'shop',
    pillarId: 'sample_collection',
    href: '/shop/b2b/showroom',
    status: 'done',
  },
  {
    id: 'agent-shop2-b2b-seed',
    kind: 'improve',
    priority: 'P1',
    title: 'Seed B2B для shop2 (B2B-DEMO-SHOP2-SS27, db:seed:workshop2-b2b-demo-order)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
  {
    id: 'agent-orchestrator-scan-wiring',
    kind: 'improve',
    priority: 'P0',
    title: 'Backend orchestrator: tech_debt, architecture_guard, code_quality, ui_improvement, order_anomaly',
    roleId: 'brand',
    pillarId: 'development',
    href: '/platform',
    status: 'done',
  },
  {
    id: 'agent-stack-routing-domain',
    kind: 'improve',
    priority: 'P1',
    title: 'pick_agent_for_task: workshop2, linesheet, procurement, factory-ack keywords',
    roleId: 'brand',
    pillarId: 'development',
    status: 'done',
  },
  {
    id: 'agent-dev-pillar-entity-label',
    kind: 'improve',
    priority: 'P1',
    title: 'Hub entity «Разработка · артикулы» без сезона коллекции (сезон — в столпе 2)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/core?pillar=development',
    status: 'done',
  },
  {
    id: 'agent-orchestrator-pg-order-context',
    kind: 'add',
    priority: 'P1',
    title: 'POST /api/v1/ai/task: enrich_platform_context (collectionId, articleId, orderId, pillar, role)',
    roleId: 'brand',
    pillarId: 'development',
    status: 'done',
  },
  {
    id: 'agent-planner-autorun-cli',
    kind: 'add',
    priority: 'P2',
    title: 'CLI npm run planner:agent:loop — run-agents → poll session → complete',
    roleId: 'brand',
    pillarId: 'development',
    status: 'done',
  },
  {
    id: 'agent-syntha-subagents-pillar2-4',
    kind: 'add',
    priority: 'P1',
    title: 'Cursor subagents syntha-sample-collection + syntha-factory-production',
    roleId: 'brand',
    pillarId: 'sample_collection',
    status: 'done',
  },
  {
    id: 'agent-orchestrator-ai-feature-scan',
    kind: 'improve',
    priority: 'P1',
    title: 'Orchestrator: ai_module_curator + feature_suggestion scan agents',
    roleId: 'brand',
    pillarId: 'development',
    status: 'done',
  },
  {
    id: 'agent-section-id-routing-hints',
    kind: 'improve',
    priority: 'P1',
    title: 'section_agent_hints + pick_agent: SECTION_AUDIT section_id → agent_id',
    roleId: 'brand',
    pillarId: 'development',
    status: 'done',
  },
  {
    id: 'agent-routing-eval-pack',
    kind: 'add',
    priority: 'P1',
    title: 'Eval: tests/eval/agent_routing_cases.json + pytest routing/classify (no LLM)',
    roleId: 'shop',
    pillarId: 'collection_order',
    status: 'done',
  },
  {
    id: 'agent-ollama-eval-pack',
    kind: 'add',
    priority: 'P2',
    title: 'Eval: tests/eval/test_agent_ollama_eval.py + npm run agent:eval:ollama (risk/quota/anomaly)',
    roleId: 'shop',
    pillarId: 'collection_order',
    status: 'done',
  },
  {
    id: 'agent-syntha-comms-subagent',
    kind: 'add',
    priority: 'P2',
    title: 'Cursor subagent syntha-comms (pillar 5 JWT/users/order chat)',
    roleId: 'brand',
    pillarId: 'comms',
    href: '/brand/messages',
    status: 'done',
  },
  {
    id: 'agent-hub-routing-api',
    kind: 'improve',
    priority: 'P1',
    title: 'GET /agents/routing: section_id, task, hub_matrix, preferred_agent, cursor_subagent',
    roleId: 'brand',
    pillarId: 'development',
    status: 'done',
  },
  {
    id: 'agent-dispatch-subagent-hints',
    kind: 'improve',
    priority: 'P1',
    title: 'Planner dispatch: pillarId → syntha subagent + backend agent hint в prompt',
    roleId: 'brand',
    pillarId: 'development',
    status: 'done',
  },
  {
    id: 'agent-brand-co-registry-anomaly',
    kind: 'improve',
    priority: 'P1',
    title: 'brand-co-registry: POST /api/v1/ai/task с order_anomaly + orderId из PG registry',
    roleId: 'brand',
    pillarId: 'collection_order',
    href: '/brand/b2b/orders/registry',
    status: 'done',
  },
  {
    id: 'agent-shop-co-registry-anomaly',
    kind: 'improve',
    priority: 'P1',
    title: 'shop-co-registry: AI strip → order_anomaly + orders из PG registry',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/orders',
    status: 'done',
  },
  {
    id: 'agent-shop-co-matrix-quota-ui',
    kind: 'improve',
    priority: 'P1',
    title: 'shop-co-matrix: квота ассортимента — UI hook → quota agent (matrix sizes)',
    roleId: 'shop',
    pillarId: 'collection_order',
    href: '/shop/b2b/matrix',
    status: 'done',
  },
  {
    id: 'agent-mfr-handoff-anomaly-e2e',
    kind: 'add',
    priority: 'P1',
    title: 'mfr-op-handoff-queue: e2e factory-ack delay → order_anomaly prompt + core spec',
    roleId: 'manufacturer',
    pillarId: 'order_production',
    href: '/factory/production/handoff',
    status: 'done',
  },
  {
    id: 'agent-ui-improvement-platform-dedup',
    kind: 'improve',
    priority: 'P2',
    title: 'Platform Core UI dedup: ui_improvement scan → planner analyze gaps (tsx dedup rules)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/platform',
    status: 'done',
  },
  {
    id: 'agent-brand-dev-w2-hub-ai',
    kind: 'add',
    priority: 'P1',
    title: 'brand-dev-w2-hub: PlatformAiTaskStrip → product_architect (dossier completeness, без сезона)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/production/workshop2',
    status: 'open',
  },
  {
    id: 'agent-brand-dev-dossier-techpack-ai',
    kind: 'add',
    priority: 'P1',
    title: 'brand-dev-dossier: AI strip tech pack / phase gaps → product_architect + articleId',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/production/workshop2',
    status: 'open',
  },
  {
    id: 'agent-brand-dev-pg-sync-tech-debt',
    kind: 'improve',
    priority: 'P2',
    title: 'brand-dev-pg-sync: tech_debt scan strip (PG mirror drift, migration gaps)',
    roleId: 'brand',
    pillarId: 'development',
    href: '/brand/production/workshop2',
    status: 'open',
  },
  {
    id: 'agent-sup-dev-bom-architect',
    kind: 'add',
    priority: 'P2',
    title: 'sup-dev-bom: supplier BOM → product_architect AI strip (materials vs dossier)',
    roleId: 'supplier',
    pillarId: 'development',
    href: '/supplier/development/bom',
    status: 'open',
  },
  {
    id: 'agent-mfr-dev-dossier-upload',
    kind: 'add',
    priority: 'P2',
    title: 'mfr-dev-dossier: image upload / DAM hook → lookbook agent hint на dossier peer',
    roleId: 'manufacturer',
    pillarId: 'development',
    href: '/factory/development/dossier',
    status: 'open',
  },
  {
    id: 'agent-intel-refresh-memory',
    kind: 'add',
    priority: 'P2',
    title: 'GSD intel refresh (.planning/intel/) — долгая память для domain subagents',
    roleId: 'brand',
    pillarId: 'development',
    status: 'open',
  },
  {
    id: 'agent-ollama-qwen3-eval-live',
    kind: 'add',
    priority: 'P2',
    title: 'Прогнать npm run agent:eval:ollama на qwen3 (risk/quota/anomaly smoke)',
    roleId: 'shop',
    pillarId: 'collection_order',
    status: 'open',
  },
];
