/**
 * Platform Core · LEGACY / archived routes.
 *
 * Пути advanced-B2B и B2C-фич, которые НЕ входят в ядро v1 (5 столпов × 2 роли).
 * Они физически ещё лежат в `@/lib/platform-core-routes` (`ROUTES.*`), но не
 * должны появляться в baseline-навигации, hub-строках и audit-разделах.
 *
 * Этот модуль — реестр «что вне ядра» для линтеров/ревью и будущего физического
 * выноса в `_archive/` (см. `_platform-core-v1/migration-notes/`). Импортировать
 * в baseline-коде запрещено (rule: денилист навигации).
 */

/** Ключи `ROUTES.brand.*` вне ядра v1 → `_archive/b2b-advanced`. */
export const PLATFORM_CORE_LEGACY_BRAND_ROUTE_KEYS = [
  'b2bEngagement',
  'b2bLinesheetCampaigns',
  'b2bLinesheetVersions',
  'b2bPassport',
  'b2bPrivateInvites',
  'companyAccounts',
  'contentSyndication',
  'customerGroups',
  'lookbookProjects',
  'partnerMap',
  'priceLists',
  'tradeShows',
  'showroomVr',
] as const;

/** Ключи `ROUTES.shop.*` вне ядра v1 → `_archive/b2b-advanced` | `experiments`. */
export const PLATFORM_CORE_LEGACY_SHOP_ROUTE_KEYS = [
  'b2bCollaborativeOrder',
  'b2bCustomAssortments',
  'b2bGamification',
  'b2bPassport',
  'b2bRfq',
  'b2bRfqCreate',
  'b2bSalesRepPortal',
  'b2bShopifySync',
  'b2bSocialFeed',
  'b2bTenders',
  'b2bTradeShows',
  'b2bTradeShowAppointments',
  'b2bVideoConsultation',
  'b2bVipRoomBooking',
  'b2bWhiteboard',
  'b2bReplenishment',
] as const;

/** Префиксы путей, запрещённых внутри Platform Core навигации. */
export const PLATFORM_CORE_DENYLIST_PATH_PREFIXES = [
  '/client',
  '/brand/b2b/trade-shows',
  '/brand/b2b/passport',
  '/brand/b2b/private-invites',
  '/brand/b2b/linesheet-campaigns',
  '/brand/b2b/linesheet-versions',
  '/brand/b2b/linesheets',
  '/brand/b2b/content-syndication',
  '/brand/b2b/lookbook-projects',
  '/brand/b2b/partner-map',
  '/brand/b2b/company-accounts',
  '/brand/b2b/customer-groups',
  '/brand/b2b/engagement',
  '/brand/b2b/price-lists',
  '/brand/b2b/buyer-applications',
  '/brand/b2b/order-amendments',
  '/brand/b2b/order-approval-workflow',
  '/brand/b2b/catalog-quality',
  '/brand/b2b/campaigns',
  '/brand/b2b/credit',
  '/brand/b2b/po',
  '/brand/b2b/shipments',
  '/brand/b2b/territories',
  '/shop/b2b/gamification',
  '/shop/b2b/social-feed',
  '/shop/b2b/video-consultation',
  '/shop/b2b/vip-room-booking',
  '/shop/b2b/whiteboard',
  '/shop/b2b/shopify-sync',
  '/shop/b2b/collaborative-order',
  '/shop/b2b/custom-assortments',
  '/shop/b2b/tenders',
  '/shop/b2b/rfq',
  '/shop/b2b/sales-rep-portal',
  '/academy',
  '/marketplace',
  '/auctions',
  '/admin',
  '/vendor',
  '/kickstarter',
  '/metaverse',
  '/look-builder',
  '/try-on',
  '/store-locator',
  '/outlet',
  '/quiz',
  '/looks',
  '/project-info',
  '/embed',
  '/search',
  '/qc-terminal',
  '/u',
  '/supplier',
  '/brand/analytics',
  '/brand/marketing',
  '/brand/finance',
  '/brand/dashboard',
  '/brand/products',
  '/brand/settings',
  '/brand/promotions',
  '/brand/academy',
  '/brand/auctions',
  '/brand/distributor',
  '/brand/inventory',
  '/brand/organization',
  '/shop/analytics',
  '/shop/orders',
  '/shop/inventory',
  '/shop/staff',
  '/shop/b2b-orders',
  '/shop/promotions',
  '/shop/settings',
  '/b',
] as const;
