import React from 'react';
import {
  ShieldCheck,
  Leaf,
  Heart,
  Zap,
  Check,
  Sparkles,
  Star,
  Handshake,
  Clock,
  MessageSquare,
  Ruler,
  Activity,
  Trophy,
} from 'lucide-react';

export const defaultSettings = {
  logo: true,
  name: true,
  description: true,
  action_button: true,
  full_description: true,
  founded_year: true,
  country: true,
  segment: true,
  website: true,
  public_email: true,
  phone: true,
  social_links: true,
  instagram: true,
  telegram: true,
  youtube: true,
  locations: true,
  key_people: true,
  esg_info: true,
  b2b_info: false,
  legal_info: false,
  press_mentions: true,
  nameRU: true,
  priceRange: true,
  startDate: true,
  subscriptionTier: true,
  community_looks_section: true,
  brand_articles_section: true,
  active_promotions_section: true,
  brand_stories_section: true,
  brand_videos_section: true,
  social_mentions_section: true,
  events_section: true,
};

export const brandStatuses = [
  {
    id: 'reputation',
    name: 'Безупречная репутация',
    icon: <ShieldCheck className="h-3 w-3" />,
    color: 'text-yellow-500',
    description: 'Топ-1% в категории Luxury Heritage',
    fullDesc:
      'Этот статус присваивается брендам с рейтингом выше 4.9 и отсутствием критических отзывов за последние 12 месяцев.',
    active: true,
  },
  {
    id: 'eco',
    name: 'Эко-Лидер',
    icon: <Leaf className="h-3 w-3" />,
    color: 'text-emerald-500',
    description: 'Zero Waste & Bio Materials',
    fullDesc:
      'Бренд использует 100% перерабатываемую упаковку и сертифицированные органические материалы.',
    active: true,
  },
  {
    id: 'loyalty',
    name: 'Топ по лояльности',
    icon: <Heart className="h-3 w-3" />,
    color: 'text-red-500',
    description: '98% возвратных клиентов',
    fullDesc: 'Самый высокий показатель повторных покупок в сегменте за текущий квартал.',
    active: true,
  },
  {
    id: 'innovation',
    name: 'Инноватор года',
    icon: <Zap className="h-3 w-3" />,
    color: 'text-blue-500',
    description: 'AI-дизайн и Smart Fit',
    fullDesc:
      'Применение передовых технологий в проектировании лекал и персонализации клиентского опыта.',
    active: false,
  },
  {
    id: 'quality',
    name: 'Мастер Качества',
    icon: <Check className="h-3 w-3" />,
    color: 'text-accent-primary',
    description: 'Ручная работа & Контроль',
    fullDesc: 'Многоступенчатая система проверки качества каждого изделия перед отправкой.',
    active: true,
  },
  {
    id: 'trend',
    name: 'Трендсеттер',
    icon: <Sparkles className="h-3 w-3" />,
    color: 'text-accent-primary',
    description: 'Задает вектор моды',
    fullDesc: 'Коллекции бренда чаще всего попадают в подборки ведущих стилистов и инфлюенсеров.',
    active: false,
  },
  {
    id: 'experts',
    name: 'Выбор экспертов',
    icon: <Star className="h-3 w-3" />,
    color: 'text-amber-500',
    description: 'Рекомендовано Syntha',
    fullDesc: 'Бренд прошел независимый аудит экспертного совета платформы по 50 параметрам.',
    active: false,
  },
  {
    id: 'social',
    name: 'Социальный вклад',
    icon: <Handshake className="h-3 w-3" />,
    color: 'text-cyan-500',
    description: 'Поддержка ремесел',
    fullDesc: 'Часть прибыли направляется на развитие локальных мастерских и сохранение традиций.',
    active: false,
  },
  {
    id: 'delivery',
    name: 'Скорость света',
    icon: <Clock className="h-3 w-3" />,
    color: 'text-orange-500',
    description: 'Доставка за 24 часа',
    fullDesc: 'Лучший показатель по скорости логистики и обработки заказов среди всех брендов.',
    active: false,
  },
  {
    id: 'service',
    name: 'Премиум Сервис',
    icon: <MessageSquare className="h-3 w-3" />,
    color: 'text-accent-primary',
    description: 'Персональный консьерж',
    fullDesc: 'Мгновенная поддержка клиентов и услуга выездной примерки в день заказа.',
    active: false,
  },
];

export const quizResults = {
  archetype: 'Luxury Visionary',
  segment: 'Premium / Contemporary',
  targetSegment: 'Luxury Heritage',
  description:
    'Ваш бренд сочетает в себе глубокое уважение к традициям и смелый взгляд в будущее. Вы создаете не просто вещи, а объекты культурного наследия.',
  traits: [
    { name: 'Качество', value: 98 },
    { name: 'Эксклюзивность', value: 95 },
    { name: 'Инновации', value: 88 },
  ],
  roadmap: [
    {
      stage: 'Интеграция ДНК',
      status: 'completed',
      description: 'Оформление страницы бренда и описание ценностей.',
    },
    {
      stage: 'Социальное доказательство',
      status: 'in_progress',
      description: 'Сбор 50+ верифицированных отзывов от Gold-клиентов.',
    },
    {
      stage: 'Эксклюзивность',
      status: 'pending',
      description: 'Запуск лимитированной коллекции с ручной нумерацией изделий.',
    },
    {
      stage: 'Аудит Syntha',
      status: 'pending',
      description: 'Прохождение независимой экспертизы качества материалов.',
    },
  ],
};

export const retailStores = [
  {
    city: 'Москва',
    name: 'ЦУМ',
    address: 'ул. Петровка, 2',
    phone: '+7 (495) 933-73-00',
    hours: '10:00 – 22:00',
  },
  {
    city: 'Москва',
    name: 'Bosco di Ciliegi',
    address: 'Красная площадь, 3 (ГУМ)',
    phone: '+7 (495) 620-31-39',
    hours: '10:00 – 22:00',
  },
  {
    city: 'Санкт-Петербург',
    name: 'ДЛТ',
    address: 'ул. Б. Конюшенная, 21-23',
    phone: '+7 (812) 648-08-48',
    hours: '10:00 – 22:00',
  },
  {
    city: 'Екатеринбург',
    name: 'Покровский Пассаж',
    address: 'ул. Розы Люксембург, 4',
    phone: '+7 (343) 365-87-87',
    hours: '11:00 – 21:00',
  },
  {
    city: 'Сочи',
    name: 'Grand Marina Gallery',
    address: 'ул. Несебрская, 1а',
    phone: '+7 (862) 227-10-00',
    hours: '10:00 – 22:00',
  },
  {
    city: 'Краснодар',
    name: 'ТРЦ Галерея',
    address: 'ул. В. Головатого, 313',
    phone: '+7 (861) 278-80-00',
    hours: '10:00 – 22:00',
  },
  {
    city: 'Новосибирск',
    name: 'Luxury Store',
    address: 'ул. Советская, 33',
    phone: '+7 (383) 222-11-11',
    hours: '11:00 – 20:00',
  },
  {
    city: 'Казань',
    name: 'Korston Tower',
    address: 'ул. Н. Ершова, 1а',
    phone: '+7 (843) 279-30-00',
    hours: '10:00 – 22:00',
  },
  {
    city: 'Ростов-на-Дону',
    name: 'Astor',
    address: 'пр. Буденновский, 49/97',
    phone: '+7 (863) 291-00-00',
    hours: '10:00 – 21:00',
  },
  {
    city: 'Самара',
    name: 'Lotte Fashion',
    address: 'ул. Самарская, 110',
    phone: '+7 (846) 300-40-00',
    hours: '10:00 – 21:00',
  },
  {
    city: 'Нижний Новгород',
    name: 'LP Fashion Gallery',
    address: 'ул. Алексеевская, 10/16',
    phone: '+7 (831) 233-11-11',
    hours: '10:00 – 21:00',
  },
  {
    city: 'Владивосток',
    name: 'Игнат',
    address: 'ул. Комсомольская, 13',
    phone: '+7 (423) 240-00-00',
    hours: '10:00 – 20:00',
  },
];

export const brandMedalsByPeriod: Record<string, any[]> = {
  month: [
    {
      id: 'style',
      name: 'Стиль и дизайн',
      rank: 1,
      type: 'gold',
      category: 'Luxury Heritage',
      date: 'Январь 2024',
    },
    {
      id: 'quality',
      name: 'Качество пошива',
      rank: 2,
      type: 'silver',
      category: 'Luxury Heritage',
      date: 'Январь 2024',
    },
    {
      id: 'loyalty',
      name: 'Лояльность',
      rank: 1,
      type: 'gold',
      category: 'Luxury Heritage',
      date: 'Январь 2024',
    },
  ],
  '6months': [
    {
      id: 'style',
      name: 'Стиль и дизайн',
      rank: 1,
      type: 'gold',
      category: 'Luxury Heritage',
      date: 'Июль-Дек 2023',
    },
    {
      id: 'materials',
      name: 'Материалы',
      rank: 3,
      type: 'bronze',
      category: 'Luxury Heritage',
      date: 'Июль-Дек 2023',
    },
  ],
  year: [
    {
      id: 'quality',
      name: 'Качество пошива',
      rank: 1,
      type: 'gold',
      category: 'Global Luxury',
      date: '2023',
    },
    {
      id: 'loyalty',
      name: 'Лояльность',
      rank: 2,
      type: 'silver',
      category: 'Global Luxury',
      date: '2023',
    },
  ],
  all: [
    {
      id: 'style',
      name: 'Стиль и дизайн',
      rank: 1,
      type: 'gold',
      category: 'Luxury Heritage',
      date: 'Январь 2024',
    },
    {
      id: 'quality',
      name: 'Качество пошива',
      rank: 2,
      type: 'silver',
      category: 'Luxury Heritage',
      date: 'Январь 2024',
    },
    {
      id: 'loyalty',
      name: 'Лояльность',
      rank: 1,
      type: 'gold',
      category: 'Luxury Heritage',
      date: 'Январь 2024',
    },
  ],
};

export const brandStatsByPeriod: Record<string, any[]> = {
  month: [
    {
      id: 'quality',
      name: 'Качество пошива',
      score: 4.9,
      icon: <ShieldCheck className="h-4 w-4" />,
    },
    { id: 'delivery', name: 'Скорость доставки', score: 4.8, icon: <Clock className="h-4 w-4" /> },
    {
      id: 'service',
      name: 'Клиентский сервис',
      score: 4.7,
      icon: <MessageSquare className="h-4 w-4" />,
    },
    { id: 'size', name: 'Точность размеров', score: 4.6, icon: <Ruler className="h-4 w-4" /> },
    { id: 'style', name: 'Стиль и дизайн', score: 5.0, icon: <Sparkles className="h-4 w-4" /> },
    { id: 'materials', name: 'Качество материалов', score: 4.9, icon: <Zap className="h-4 w-4" /> },
    {
      id: 'durability',
      name: 'Износостойкость',
      score: 4.5,
      icon: <Activity className="h-4 w-4" />,
    },
    { id: 'eco', name: 'Экологичность', score: 4.8, icon: <Leaf className="h-4 w-4" /> },
    { id: 'value', name: 'Цена / Качество', score: 4.6, icon: <Trophy className="h-4 w-4" /> },
    {
      id: 'loyalty',
      name: 'Лояльность аудитории',
      score: 5.0,
      icon: <Heart className="h-4 w-4" />,
    },
  ],
  '6months': [
    {
      id: 'quality',
      name: 'Качество пошива',
      score: 4.8,
      icon: <ShieldCheck className="h-4 w-4" />,
    },
    { id: 'delivery', name: 'Скорость доставки', score: 4.5, icon: <Clock className="h-4 w-4" /> },
    {
      id: 'service',
      name: 'Клиентский сервис',
      score: 4.6,
      icon: <MessageSquare className="h-4 w-4" />,
    },
    { id: 'size', name: 'Точность размеров', score: 4.7, icon: <Ruler className="h-4 w-4" /> },
    { id: 'style', name: 'Стиль и дизайн', score: 4.9, icon: <Sparkles className="h-4 w-4" /> },
    { id: 'materials', name: 'Качество материалов', score: 4.8, icon: <Zap className="h-4 w-4" /> },
    {
      id: 'durability',
      name: 'Износостойкость',
      score: 4.7,
      icon: <Activity className="h-4 w-4" />,
    },
    { id: 'eco', name: 'Экологичность', score: 4.7, icon: <Leaf className="h-4 w-4" /> },
    { id: 'value', name: 'Цена / Качество', score: 4.4, icon: <Trophy className="h-4 w-4" /> },
    {
      id: 'loyalty',
      name: 'Лояльность аудитории',
      score: 4.8,
      icon: <Heart className="h-4 w-4" />,
    },
  ],
  year: [
    {
      id: 'quality',
      name: 'Качество пошива',
      score: 4.7,
      icon: <ShieldCheck className="h-4 w-4" />,
    },
    { id: 'delivery', name: 'Скорость доставки', score: 4.4, icon: <Clock className="h-4 w-4" /> },
    {
      id: 'service',
      name: 'Клиентский сервис',
      score: 4.5,
      icon: <MessageSquare className="h-4 w-4" />,
    },
    { id: 'size', name: 'Точность размеров', score: 4.8, icon: <Ruler className="h-4 w-4" /> },
    { id: 'style', name: 'Стиль и дизайн', score: 4.8, icon: <Sparkles className="h-4 w-4" /> },
    { id: 'materials', name: 'Качество материалов', score: 4.7, icon: <Zap className="h-4 w-4" /> },
    {
      id: 'durability',
      name: 'Износостойкость',
      score: 4.8,
      icon: <Activity className="h-4 w-4" />,
    },
    { id: 'eco', name: 'Экологичность', score: 4.6, icon: <Leaf className="h-4 w-4" /> },
    { id: 'value', name: 'Цена / Качество', score: 4.3, icon: <Trophy className="h-4 w-4" /> },
    {
      id: 'loyalty',
      name: 'Лояльность аудитории',
      score: 4.7,
      icon: <Heart className="h-4 w-4" />,
    },
  ],
  all: [
    {
      id: 'quality',
      name: 'Качество пошива',
      score: 4.8,
      icon: <ShieldCheck className="h-4 w-4" />,
    },
    { id: 'delivery', name: 'Скорость доставки', score: 4.6, icon: <Clock className="h-4 w-4" /> },
    {
      id: 'service',
      name: 'Клиентский сервис',
      score: 4.7,
      icon: <MessageSquare className="h-4 w-4" />,
    },
    { id: 'size', name: 'Точность размеров', score: 4.7, icon: <Ruler className="h-4 w-4" /> },
    { id: 'style', name: 'Стиль и дизайн', score: 4.9, icon: <Sparkles className="h-4 w-4" /> },
    { id: 'materials', name: 'Качество материалов', score: 4.8, icon: <Zap className="h-4 w-4" /> },
    {
      id: 'durability',
      name: 'Износостойкость',
      score: 4.7,
      icon: <Activity className="h-4 w-4" />,
    },
    { id: 'eco', name: 'Экологичность', score: 4.7, icon: <Leaf className="h-4 w-4" /> },
    { id: 'value', name: 'Цена / Качество', score: 4.5, icon: <Trophy className="h-4 w-4" /> },
    {
      id: 'loyalty',
      name: 'Лояльность аудитории',
      score: 4.9,
      icon: <Heart className="h-4 w-4" />,
    },
  ],
};

export const detailedReviews = [
  {
    id: 1,
    author: 'Александра М.',
    avatar: 'https://i.pravatar.cc/150?u=1',
    rating: 5,
    date: '12.01.2024',
    status: 'Gold Client',
    text: 'Обожаю этот бренд! Качество материалов всегда на высоте. Купила кашемировый свитер, ношу второй сезон, выглядит как новый. Очень рекомендую тем, кто ценит долговечность.',
    images: [
      {
        id: 'r1',
        url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&q=80',
        alt: 'Свитер в интерьере',
      },
      {
        id: 'r2',
        url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80',
        alt: 'Детали ткани',
      },
    ],
    likes: 12,
    dislikes: 0,
    tags: ['Качество материалов', 'Решено: Идеально'],
    chat: [
      {
        sender: 'brand',
        text: 'Александра, спасибо за доверие! Рады, что свитер вас радует.',
        date: '13.01.2024',
      },
    ],
  },
  {
    id: 2,
    author: 'Игорь В.',
    avatar: 'https://i.pravatar.cc/150?u=2',
    rating: 4,
    date: '05.01.2024',
    status: 'Verified Buyer',
    text: 'Заказывал джинсовую куртку. Села идеально по плечам, но доставка задержалась на 2 дня. В остальном претензий нет, вещь отличная.',
    likes: 5,
    dislikes: 1,
    tags: ['Точность размеров', 'Решено: Компенсация бонусами'],
    chat: [
      {
        sender: 'brand',
        text: 'Игорь, приносим извинения за задержку. Мы начислили вам 500 бонусов в качестве компенсации.',
        date: '06.01.2024',
      },
      {
        sender: 'client',
        text: 'Спасибо, бонусы получил. Куртку уже ношу, качество супер.',
        date: '06.01.2024',
      },
    ],
  },
  {
    id: 3,
    author: 'Елена К.',
    avatar: 'https://i.pravatar.cc/150?u=3',
    rating: 2,
    date: '28.12.2023',
    status: 'Fashion Expert',
    text: 'Коллекции Syntha Lab — это всегда про стиль. Но в этот раз размер L оказался как S. Пришлось оформлять возврат. Очень жаль, так как дизайн понравился.',
    images: [
      {
        id: 'r3',
        url: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&q=80',
        alt: 'Образ',
      },
    ],
    likes: 2,
    dislikes: 14,
    tags: ['Маломерит', 'В процессе: Возврат'],
    chat: [
      {
        sender: 'brand',
        text: 'Елена, добрый день! Нам очень жаль, что размер не подошел. Мы уже оформляем возврат. Подскажите, прислать вам замеры изделия для выбора верного размера?',
        date: '29.12.2023',
      },
    ],
  },
];

export const measurementLabels: Record<string, string> = {
  height: 'Рост',
  bust: 'Обхват груди',
  waist: 'Обхват талии',
  hips: 'Обхват бедер',
  shoulder: 'Ширина плеч',
  sleeve: 'Длина рукава',
  back: 'Ширина спины',
  length: 'Длина изделия',
  underbust: 'Обхват под грудью',
  difference: 'Разница',
  braSizeEU: 'Размер бра (EU)',
  braSizeUKUS: 'Размер бра (UK/US)',
  cupEU: 'Чашка (EU)',
  cupUKUS: 'Чашка (UK/US)',
  cupRU: 'Чашка (RU)',
  footLength: 'Длина стопы',
  bottomLength: 'Длина дна',
  bottomWidth: 'Ширина дна',
  handleDrop: 'Высота ручек',
  strapLength: 'Длина ремня',
  strapWidth: 'Ширина ремня',
  depth: 'Глубина',
};

export type AudienceFilter =
  | 'Все'
  | 'Взрослые - Женщины'
  | 'Взрослые - Мужчины'
  | 'Взрослые - Унисекс'
  | 'Дети - Девочки'
  | 'Дети - Мальчики'
  | 'Дети - Новорожденные'
  | 'Дети - Унисекс'
  | 'Non-Fashion';

export const audienceAttributeMap: Record<AudienceFilter, string[]> = {
  Все: [
    'fit',
    'length',
    'sleeveLength',
    'collar',
    'fastening',
    'waist',
    'pockets',
    'stitching',
    'decor',
    'hardware',
    'fabricTexture',
    'pattern',
  ],
  'Взрослые - Женщины': [
    'fit',
    'length',
    'sleeveLength',
    'collar',
    'fastening',
    'waist',
    'pockets',
    'stitching',
    'decor',
    'hardware',
    'fabricTexture',
    'pattern',
    'backDetails',
    'hemType',
    'drapery',
  ],
  'Взрослые - Мужчины': [
    'fit',
    'length',
    'sleeveLength',
    'collar',
    'fastening',
    'waist',
    'pockets',
    'stitching',
    'hardware',
    'fabricTexture',
    'pattern',
    'shoulder',
    'seam',
  ],
  'Взрослые - Унисекс': [
    'fit',
    'length',
    'sleeveLength',
    'collar',
    'fastening',
    'waist',
    'pockets',
    'stitching',
    'decor',
    'hardware',
    'fabricTexture',
    'pattern',
  ],
  'Дети - Девочки': [
    'fit',
    'length',
    'sleeveLength',
    'fastening',
    'waist',
    'pockets',
    'stitching',
    'decor',
    'hardware',
    'fabricTexture',
    'pattern',
    'transformation',
  ],
  'Дети - Мальчики': [
    'fit',
    'length',
    'sleeveLength',
    'fastening',
    'waist',
    'pockets',
    'stitching',
    'decor',
    'hardware',
    'fabricTexture',
    'pattern',
    'transformation',
  ],
  'Дети - Новорожденные': ['fabricTexture', 'pattern', 'fastening', 'transformation'],
  'Дети - Унисекс': [
    'fit',
    'length',
    'sleeveLength',
    'fastening',
    'waist',
    'pockets',
    'stitching',
    'decor',
    'hardware',
    'fabricTexture',
    'pattern',
    'transformation',
  ],
  'Non-Fashion': [
    'fabricTexture',
    'decor',
    'hardware',
    'pattern',
    'processingTech',
    'stitching',
    'lining',
    'combination',
  ],
};

export const audienceCategoryMap: Record<AudienceFilter, string[]> = {
  Все: ['Одежда', 'Обувь', 'Сумки', 'Аксессуары', 'Beauty & Grooming', 'Home & Lifestyle'],
  'Взрослые - Женщины': ['Одежда', 'Обувь', 'Сумки', 'Аксессуары'],
  'Взрослые - Мужчины': ['Одежда', 'Обувь', 'Сумки', 'Аксессуары'],
  'Взрослые - Унисекс': ['Одежда', 'Обувь', 'Сумки', 'Аксессуары'],
  'Дети - Девочки': ['Одежда', 'Обувь', 'Сумки', 'Аксессуары'],
  'Дети - Мальчики': ['Одежда', 'Обувь', 'Сумки', 'Аксессуары'],
  'Дети - Новорожденные': ['Одежда', 'Аксессуары'],
  'Дети - Унисекс': ['Одежда', 'Обувь', 'Сумки', 'Аксессуары'],
  'Non-Fashion': ['Beauty & Grooming', 'Home & Lifestyle'],
};

export const categoryAttributeMap: Record<string, string[]> = {
  Одежда: [
    'fit',
    'length',
    'sleeveLength',
    'collar',
    'fastening',
    'waist',
    'pockets',
    'stitching',
    'decor',
    'hardware',
    'fabricTexture',
    'pattern',
    'backDetails',
    'hemType',
    'transformation',
  ],
  Обувь: ['fit', 'fastening', 'decor', 'hardware', 'fabricTexture', 'pattern', 'footLength'],
  Сумки: [
    'fit',
    'fastening',
    'pockets',
    'decor',
    'hardware',
    'fabricTexture',
    'pattern',
    'bottomLength',
    'bottomWidth',
    'handleDrop',
    'strapLength',
    'strapWidth',
    'depth',
  ],
  Аксессуары: ['fit', 'fastening', 'decor', 'hardware', 'fabricTexture', 'pattern'],
  'Beauty & Grooming': ['fabricTexture', 'pattern'],
  'Home & Lifestyle': ['fit', 'fabricTexture', 'pattern'],
};

export const sizeTemplates = [
  { id: 'standard', name: 'Стандартный RU', sizes: ['40', '42', '44', '46', '48', '50'] },
  { id: 'international', name: 'Международный', sizes: ['XXS', 'XS', 'S', 'M', 'L', 'XL'] },
  { id: 'european', name: 'Европейский (EU)', sizes: ['34', '36', '38', '40', '42', '44'] },
  { id: 'uk', name: 'Британский (UK)', sizes: ['6', '8', '10', '12', '14', '16'] },
];

export const capsuleCollections = [
  { id: 'arctic', label: 'Arctic Minimal', desc: 'Зимняя капсула из мериноса' },
  { id: 'urban', label: 'Urban Wool', desc: 'Городской гардероб' },
  { id: 'silence', label: 'Evening Silence', desc: 'Вечерняя коллекция' },
];

export const brandMediaData = {
  blog: [
    {
      id: 1,
      title: 'Тренды весна-лето 2024: Минимализм и Лён',
      type: 'Журнал',
      date: '15 Января, 12:45',
      imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80',
    },
    {
      id: 2,
      title: 'Интервью с главным дизайнером Syntha Lab',
      type: 'Интервью',
      date: '10 Января, 10:20',
      imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80',
    },
    {
      id: 3,
      title: "История создания нашей коллекции 'Arctica'",
      type: 'Бренд-стори',
      date: '5 Января, 16:15',
      imageUrl: 'https://images.unsplash.com/photo-1520975916090-3105956dac38?w=800&q=80',
    },
  ],
  social: [
    {
      id: 1,
      platform: 'instagram',
      likes: '1.2k',
      date: '15 Января, 14:30',
      imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&q=80',
    },
    {
      id: 2,
      platform: 'telegram',
      views: '5.4k',
      date: '14 Января, 18:10',
      text: 'Новая подборка образов для офиса уже в нашем канале!',
      imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400&q=80',
    },
    {
      id: 3,
      platform: 'youtube',
      title: 'Backstage: Съемки лукбука в горах',
      date: '12 Января, 11:45',
      duration: '12:45',
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80',
    },
  ],
  customerMentions: [
    {
      id: 1,
      user: 'olga_fashion',
      avatar: 'https://i.pravatar.cc/150?u=10',
      date: '15 Января, 15:20',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&q=80',
      text: 'Лучшее пальто в моей жизни! @SynthaLab',
    },
    {
      id: 2,
      user: 'mark_urban',
      avatar: 'https://i.pravatar.cc/150?u=11',
      date: '14 Января, 20:15',
      imageUrl: 'https://images.unsplash.com/photo-1503910367177-33bd2142449e?w=400&q=80',
      text: 'Стиль и качество. Рекомендую всем.',
    },
  ],
  video: [
    {
      id: 1,
      title: 'Мастер-класс: Уход за шерстью',
      type: 'Tutorial',
      date: '15 Января, 12:00',
      duration: '15:20',
      imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
    },
    {
      id: 2,
      title: 'Производство Syntha Lab: Изнутри',
      type: 'Documentary',
      date: '10 Января, 09:30',
      duration: '10:45',
      imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80',
    },
  ],
  press: [
    {
      id: 1,
      title: 'Vogue: Выбор года — Syntha Lab',
      name: 'Vogue',
      date: 'Декабрь 2023, 11:00',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Vogue_logo.svg',
      imageUrl: 'https://images.unsplash.com/photo-1537832816519-689ad163238b?w=800&q=80',
    },
    {
      id: 2,
      title: 'РБК Стиль: Как нейросети меняют моду',
      name: 'РБК',
      date: 'Январь 2024, 14:00',
      logoUrl: '',
      imageUrl: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=80',
    },
  ],
  events: [
    {
      id: 1,
      title: 'Клиентский день в шоуруме',
      date: '20 Января, 12:00',
      type: 'Мероприятие',
      location: 'Москва, Петровка 2',
      imageUrl: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&q=80',
    },
    {
      id: 2,
      title: 'Показ новой коллекции SS24',
      date: '25 Января, 19:00',
      type: 'Fashion Show',
      location: 'Гостиный Двор',
      imageUrl: 'https://images.unsplash.com/photo-1551232864-3f0890e580d9?w=800&q=80',
    },
    {
      id: 3,
      title: 'Workshop: Стилизация трикотажа',
      date: '30 Января, 15:00',
      type: 'Воркшоп',
      location: 'Шоурум Nordic Wool',
      imageUrl: 'https://images.unsplash.com/photo-1542037104857-e6e23e20e153?w=800&q=80',
    },
    {
      id: 4,
      title: 'Public Talk: Устойчивая мода',
      date: '5 Февраля, 18:00',
      type: 'Мероприятие',
      location: 'Лекторий ЦУМ',
      imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74ec0f77995?w=800&q=80',
    },
    {
      id: 5,
      title: 'VIP-превью коллекции',
      date: '10 Февраля, 20:00',
      type: 'Fashion Show',
      location: 'Особняк на Волхонке',
      imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    },
  ],
  live: [
    {
      id: 1,
      title: 'Разбор весенней коллекции с основателем',
      status: 'live',
      viewers: 842,
      type: 'Live Shopping',
      date: 'Идет сейчас',
      imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80',
    },
    {
      id: 2,
      title: 'Подкаст #13: Будущее AI в дизайне одежды',
      status: 'planned',
      date: 'Завтра в 18:00',
      type: 'Podcast',
      imageUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&q=80',
    },
    {
      id: 3,
      title: 'Мастер-класс: Как сочетать принты',
      status: 'planned',
      date: '18 Января, 12:00',
      type: 'Webinar',
      imageUrl: 'https://images.unsplash.com/photo-1556740758-90de374c12ad?w=800&q=80',
    },
  ],
  bts: [],
  podcasts: [],
};
