import { LEGACY_ROUTES } from '@/lib/platform-core-legacy-routes';
import { ROUTES } from '@/lib/routes';
import type { LiveProcessDefinition } from './types';

/** Все определения LIVE-процессов с детальными этапами. */
export const LIVE_PROCESS_DEFINITIONS: LiveProcessDefinition[] = [
  {
    id: 'production',
    name: 'Производство: от идеи до склада',
    description:
      'Поэтапная схема коллекции: бриф, ассортимент, себестоимость, материалы, техпак, сэмплы, лайншиты, PO, QC, приёмка, ESG.',
    contextKey: 'collectionId',
    stages: [
      {
        id: 'brief',
        title: 'Бриф коллекции и цели',
        description: 'Цели сезона (выручка, маржа), целевая аудитория, позиционирование.',
        area: 'Ассортимент',
        mandatory: true,
        dependsOn: [],
      },
      {
        id: 'assortment-map',
        title: 'Карта ассортимента (SKU / категории)',
        description: 'Сетка категорий и объёмов, связь с PIM и матрицей закупок.',
        area: 'Ассортимент',
        mandatory: true,
        dependsOn: ['brief'],
        href: ROUTES.brand.products,
      },
      {
        id: 'costing',
        title: 'Себестоимость и маржа',
        description: 'Цены поставки, оптовые и розничные цены, маржа по категориям.',
        area: 'Финансы',
        mandatory: true,
        dependsOn: ['assortment-map'],
        href: ROUTES.brand.budgetActual,
      },
      {
        id: 'materials',
        title: 'Материалы и поставщики',
        description: 'BOM: ткани, фурнитура, привязка к поставщикам и срокам.',
        area: 'Производство',
        mandatory: true,
        dependsOn: ['assortment-map'],
        href: ROUTES.brand.suppliersRfq,
      },
      {
        id: 'tech-pack',
        title: 'Tech Pack и размерная спецификация',
        description: 'Полный техпак по каждому стилю: чертежи, измерения, градация.',
        area: 'Производство',
        mandatory: true,
        dependsOn: ['materials'],
        href: `${ROUTES.brand.production}/tech-pack/TP-9921-A`,
      },
      {
        id: 'samples',
        title: 'Сэмплы: Proto / Fit / Gold Sample',
        description: 'Цикл сэмплов до утверждения золотого образца.',
        area: 'Производство',
        mandatory: true,
        dependsOn: ['tech-pack'],
        href: ROUTES.brand.productionGoldSample,
      },
      {
        id: 'b2b-linesheets',
        title: 'B2B лукбук и лайншиты',
        description: 'Цифровые лукбуки и лайншиты для байеров.',
        area: 'B2B',
        mandatory: false,
        dependsOn: ['samples'],
        href: ROUTES.brand.b2bLinesheets,
      },
      {
        id: 'po',
        title: 'Производственные заказы (PO) и мощности',
        description: 'Разнарядка по фабрикам, загрузка мощностей, календарь поставок.',
        area: 'Производство',
        mandatory: true,
        dependsOn: ['samples', 'costing'],
        href: ROUTES.brand.productionGantt,
      },
      {
        id: 'qc',
        title: 'Контроль качества и инспекции',
        description: 'Планы инспекций, чек-листы QC, мобильное приложение приёмки.',
        area: 'Производство',
        mandatory: true,
        dependsOn: ['po'],
        href: ROUTES.brand.productionQcApp,
      },
      {
        id: 'ready-made',
        title: 'Готовый товар и приёмка на склад',
        description: 'Приёмка коллекции на склад, сверка с PO, статусы отгрузки.',
        area: 'Производство',
        mandatory: true,
        dependsOn: ['qc'],
        href: ROUTES.brand.productionReadyMade,
      },
      {
        id: 'sustainability',
        title: 'ESG и устойчивость по коллекции',
        description: 'Материалы, сертификаты, паспорт изделия.',
        area: 'Устойчивость',
        mandatory: false,
        dependsOn: ['materials', 'po'],
      },
    ],
  },
  {
    id: 'b2b',
    name: 'B2B: от заявки до отгрузки',
    description:
      'Оптовый заказ: заявка байера, апрув партнёра, оформление, согласование, оплата, отгрузка, документы.',
    contextKey: 'orderId',
    stages: [
      {
        id: 'application',
        title: 'Заявка байера / инвайт',
        description: 'Заявка на партнёрство или приглашение в лайншит.',
        area: 'B2B',
        mandatory: true,
        dependsOn: [],
        href: LEGACY_ROUTES.brand.buyerApplications,
      },
      {
        id: 'partner-approval',
        title: 'Апрув партнёра',
        description: 'Проверка и одобрение партнёра брендом.',
        area: 'B2B',
        mandatory: true,
        dependsOn: ['application'],
      },
      {
        id: 'draft-order',
        title: 'Оформление заказа (драфт)',
        description: 'Черновик заказа: позиции, объёмы, цены.',
        area: 'B2B',
        mandatory: true,
        dependsOn: ['partner-approval'],
        href: ROUTES.brand.b2bOrders,
      },
      {
        id: 'approval-workflow',
        title: 'Согласование заказа',
        description: 'Многошаговое согласование: байер → магазин → бренд.',
        area: 'B2B',
        mandatory: true,
        dependsOn: ['draft-order'],
        href: LEGACY_ROUTES.brand.orderApprovalWorkflow,
      },
      {
        id: 'order-confirmed',
        title: 'Подтверждение заказа',
        description: 'Финальное подтверждение, фиксация дат поставки.',
        area: 'B2B',
        mandatory: true,
        dependsOn: ['approval-workflow'],
      },
      {
        id: 'payment',
        title: 'Оплата / кредит / эскроу',
        description: 'Оплата или открытие кредитной линии, эскроу при необходимости.',
        area: 'Финансы',
        mandatory: true,
        dependsOn: ['order-confirmed'],
        href: ROUTES.brand.financeEmbeddedPayment,
      },
      {
        id: 'allocation-shipment',
        title: 'Аллокация и отгрузка',
        description: 'Резервирование остатков, сборка, отгрузка.',
        area: 'Логистика',
        mandatory: true,
        dependsOn: ['payment'],
        href: LEGACY_ROUTES.brand.b2bShipments,
      },
      {
        id: 'documents',
        title: 'Документы (инвойс, накладная)',
        description: 'Выставление и отправка документов.',
        area: 'B2B',
        mandatory: true,
        dependsOn: ['allocation-shipment'],
        href: ROUTES.brand.documents,
      },
    ],
    processLinks: [
      {
        sourceProcessId: 'b2b',
        sourceStageId: 'order-confirmed',
        targetProcessId: 'logistics',
        targetStageId: 'start',
        condition: 'order_confirmed',
      },
    ],
  },
  {
    id: 'logistics',
    name: 'Логистика: от цеха до полки',
    description: 'Приёмка на складе, маркировка, перевозка, таможня, доставка до точки.',
    contextKey: 'shipmentId',
    stages: [
      {
        id: 'warehouse-receipt',
        title: 'Приёмка на складе бренда',
        description: 'Приёмка партии, сверка с PO, занесение в WMS.',
        area: 'Логистика',
        mandatory: true,
        dependsOn: [],
        href: ROUTES.brand.warehouse,
      },
      {
        id: 'marking',
        title: 'Маркировка / КИЗ (РФ)',
        description: 'Нанесение маркировки, регистрация в ГИС МТ при необходимости.',
        area: 'ЭДО',
        mandatory: true,
        dependsOn: ['warehouse-receipt'],
        href: ROUTES.brand.compliance,
      },
      {
        id: 'carrier-order',
        title: 'Заказ перевозки',
        description: 'Выбор перевозчика, заказ доставки, трекинг.',
        area: 'Логистика',
        mandatory: true,
        dependsOn: ['marking'],
        href: ROUTES.brand.logistics,
      },
      {
        id: 'consolidation',
        title: 'Консолидация (при необходимости)',
        description: 'Группировка партий разных брендов.',
        area: 'Логистика',
        mandatory: false,
        dependsOn: ['carrier-order'],
        href: ROUTES.brand.logisticsConsolidation,
      },
      {
        id: 'customs',
        title: 'Таможня (импорт)',
        description: 'Таможенное оформление, пошлины, документы.',
        area: 'Логистика',
        mandatory: false,
        dependsOn: ['carrier-order'],
        href: ROUTES.brand.logisticsDutyCalculator,
      },
      {
        id: 'delivery',
        title: 'Доставка до склада получателя',
        description: 'Транзит до склада дистрибутора или магазина.',
        area: 'Логистика',
        mandatory: true,
        dependsOn: ['carrier-order'],
      },
      {
        id: 'recipient-acceptance',
        title: 'Приёмка и актирование',
        description: 'Приёмка получателем, подписание акта, закрытие поставки.',
        area: 'Логистика',
        mandatory: true,
        dependsOn: ['delivery'],
      },
    ],
  },
  {
    id: 'sourcing',
    name: 'Сорсинг и закупки',
    description: 'От запроса цен до поставки материалов на фабрику.',
    contextKey: 'rfqId',
    stages: [
      {
        id: 'rfq',
        title: 'Запрос цен / RFQ',
        description: 'Формирование запроса поставщикам, спецификации.',
        area: 'Закупки',
        mandatory: true,
        dependsOn: [],
        href: ROUTES.brand.suppliersRfq,
      },
      {
        id: 'supplier-responses',
        title: 'Ответы поставщиков',
        description: 'Получение и первичный разбор коммерческих предложений.',
        area: 'Закупки',
        mandatory: true,
        dependsOn: ['rfq'],
      },
      {
        id: 'comparison-selection',
        title: 'Сравнение и выбор поставщика',
        description: 'Сравнение условий, выбор поставщика, переговоры.',
        area: 'Закупки',
        mandatory: true,
        dependsOn: ['supplier-responses'],
      },
      {
        id: 'po-placement',
        title: 'Размещение PO поставщику',
        description: 'Оформление заказа на материалы/фурнитуру.',
        area: 'Закупки',
        mandatory: true,
        dependsOn: ['comparison-selection'],
      },
      {
        id: 'supplier-confirm',
        title: 'Подтверждение поставщика',
        description: 'Подтверждение сроков и объёмов поставки.',
        area: 'Закупки',
        mandatory: true,
        dependsOn: ['po-placement'],
      },
      {
        id: 'supplier-shipment',
        title: 'Отгрузка у поставщика',
        description: 'Производство/комплектация и отгрузка со склада поставщика.',
        area: 'Закупки',
        mandatory: true,
        dependsOn: ['supplier-confirm'],
      },
      {
        id: 'factory-receipt',
        title: 'Приёмка на фабрике / склад материалов',
        description: 'Приёмка материалов на фабрике, контроль качества.',
        area: 'Производство',
        mandatory: true,
        dependsOn: ['supplier-shipment'],
        href: ROUTES.brand.materials,
      },
    ],
  },
  {
    id: 'qc',
    name: 'Контроль качества (ОТК)',
    description: 'План инспекций, пре- и финальная инспекция, протоколы, претензии.',
    contextKey: 'orderId',
    stages: [
      {
        id: 'inspection-plan',
        title: 'План инспекций по заказу',
        description: 'Определение точек инспекции, AQL, объёмы выборки.',
        area: 'QC',
        mandatory: true,
        dependsOn: [],
        href: ROUTES.brand.productionQcApp,
      },
      {
        id: 'pre-inspection',
        title: 'Pre-production / in-line инспекция',
        description: 'Проверка материалов и первых единиц.',
        area: 'QC',
        mandatory: true,
        dependsOn: ['inspection-plan'],
      },
      {
        id: 'final-inspection',
        title: 'Финальная инспекция (AQL)',
        description: 'Финальная проверка партии, чек-лист, фотофиксация брака.',
        area: 'QC',
        mandatory: true,
        dependsOn: ['pre-inspection'],
        href: ROUTES.brand.productionQcApp,
      },
      {
        id: 'protocol',
        title: 'Протокол и отчёт',
        description: 'Оформление протокола ОТК, отчёт для бренда.',
        area: 'QC',
        mandatory: true,
        dependsOn: ['final-inspection'],
      },
      {
        id: 'acceptance-claim',
        title: 'Приёмка / рекламация',
        description: 'Решение о приёмке или рекламация поставщику.',
        area: 'QC',
        mandatory: true,
        dependsOn: ['protocol'],
      },
      {
        id: 'claim-closure',
        title: 'Закрытие претензий',
        description: 'Устранение дефектов, повторная проверка, закрытие.',
        area: 'QC',
        mandatory: true,
        dependsOn: ['acceptance-claim'],
      },
    ],
  },
  {
    id: 'finance-escrow',
    name: 'Финансы: этапы оплаты (эскроу)',
    description: 'Создание сделки, аванс, отгрузка, приёмка, разблокировка, комиссии.',
    contextKey: 'dealId',
    stages: [
      {
        id: 'deal-created',
        title: 'Создание сделки',
        description: 'Регистрация сделки, условия, стороны.',
        area: 'Финансы',
        mandatory: true,
        dependsOn: [],
        href: ROUTES.brand.financeEscrow,
      },
      {
        id: 'advance',
        title: 'Аванс (эскроу)',
        description: 'Внесение аванса, блокировка средств.',
        area: 'Финансы',
        mandatory: true,
        dependsOn: ['deal-created'],
        href: ROUTES.brand.financeEmbeddedPayment,
      },
      {
        id: 'shipment-confirmed',
        title: 'Подтверждение отгрузки',
        description: 'Документальное подтверждение отгрузки.',
        area: 'Финансы',
        mandatory: true,
        dependsOn: ['advance'],
      },
      {
        id: 'buyer-acceptance',
        title: 'Приёмка покупателем',
        description: 'Подтверждение приёмки товара покупателем.',
        area: 'Финансы',
        mandatory: true,
        dependsOn: ['shipment-confirmed'],
      },
      {
        id: 'escrow-release',
        title: 'Разблокировка эскроу / финальный платёж',
        description: 'Перевод средств продавцу по условиям.',
        area: 'Финансы',
        mandatory: true,
        dependsOn: ['buyer-acceptance'],
        href: ROUTES.brand.financeEscrow,
      },
      {
        id: 'commissions-reporting',
        title: 'Комиссии и отчётность',
        description: 'Расчёт комиссий, отчётность, закрытие сделки.',
        area: 'Финансы',
        mandatory: true,
        dependsOn: ['escrow-release'],
      },
    ],
  },
  {
    id: 'order-approval',
    name: 'Согласование заказа (workflow)',
    description: 'Многошаговое согласование заказа: байер → магазин → бренд.',
    contextKey: 'orderId',
    stages: [
      {
        id: 'buyer-submit',
        title: 'Байер отправил заказ',
        description: 'Заказ сформирован и отправлен на согласование.',
        area: 'B2B',
        mandatory: true,
        dependsOn: [],
        href: ROUTES.brand.b2bOrders,
      },
      {
        id: 'shop-review',
        title: 'Проверка магазином',
        description: 'Проверка условий, MOV/MOQ, передача бренду.',
        area: 'B2B',
        mandatory: true,
        dependsOn: ['buyer-submit'],
        href: LEGACY_ROUTES.brand.orderApprovalWorkflow,
      },
      {
        id: 'brand-review',
        title: 'Проверка брендом',
        description: 'Проверка MOQ/MOV, кредитного лимита, остатков.',
        area: 'B2B',
        mandatory: true,
        dependsOn: ['shop-review'],
        href: LEGACY_ROUTES.brand.orderApprovalWorkflow,
      },
      {
        id: 'approved-rejected',
        title: 'Подтверждение или отклонение',
        description: 'Финальное решение: подтвердить заказ или отклонить с комментарием.',
        area: 'B2B',
        mandatory: true,
        dependsOn: ['brand-review'],
        href: LEGACY_ROUTES.brand.orderAmendments,
      },
      {
        id: 'amendments',
        title: 'Правки (amendments) при необходимости',
        description: 'Запрос изменений от байера, повторное согласование.',
        area: 'B2B',
        mandatory: false,
        dependsOn: ['approved-rejected'],
        href: LEGACY_ROUTES.brand.orderAmendments,
      },
    ],
  },
  {
    id: 'compliance',
    name: 'ЭДО и маркировка (РФ)',
    description: 'Регистрация в ГИС МТ, заказ кодов, маркировка, учёт, отчётность.',
    contextKey: 'batchId',
    stages: [
      {
        id: 'gis-registration',
        title: 'Регистрация в ГИС МТ',
        description: 'Регистрация участника оборота в ГИС МТ.',
        area: 'ЭДО',
        mandatory: true,
        dependsOn: [],
        href: ROUTES.brand.compliance,
      },
      {
        id: 'code-order',
        title: 'Заказ кодов маркировки',
        description: 'Заказ кодов КИЗ для партии товара.',
        area: 'ЭДО',
        mandatory: true,
        dependsOn: ['gis-registration'],
        href: ROUTES.brand.compliance,
      },
      {
        id: 'marking-apply',
        title: 'Нанесение маркировки на товар',
        description: 'Нанесение КИЗ на единицы товара.',
        area: 'ЭДО',
        mandatory: true,
        dependsOn: ['code-order'],
      },
      {
        id: 'warehouse-accounting',
        title: 'Приёмка на склад и учёт КИЗ',
        description: 'Оприходование маркированных остатков, синхронизация с ГИС.',
        area: 'ЭДО',
        mandatory: true,
        dependsOn: ['marking-apply'],
        href: ROUTES.brand.complianceStock,
      },
      {
        id: 'disposal-reporting',
        title: 'Выбытие и отчётность в ГИС',
        description: 'Продажа/возврат, передача сведений в ГИС МТ.',
        area: 'ЭДО',
        mandatory: true,
        dependsOn: ['warehouse-accounting'],
        href: ROUTES.brand.compliance,
      },
    ],
  },
];

export function getLiveProcessDefinition(processId: string): LiveProcessDefinition | null {
  return LIVE_PROCESS_DEFINITIONS.find((p) => p.id === processId) ?? null;
}

export function getAllLiveProcessIds(): string[] {
  return LIVE_PROCESS_DEFINITIONS.map((p) => p.id);
}
