import type { Dispatch, SetStateAction } from 'react';
import type { ModuleStatPatch } from './organization-navigation-cards';
import type { RecentActivity } from './organization-recent-activity';
import type { HistoryEntry } from '@/components/brand/SectionBlock';
import type { ActivityPeriod } from './_components/organization-overview-lib';
import type { HealthMetric, OrgOverviewProfileView } from '@/lib/brand/organization-types';
import type { AttentionAlertsState } from './use-attention-alerts';
import type { useToast } from '@/hooks/use-toast';

export type OrganizationToastFn = ReturnType<typeof useToast>['toast'];

export type OrganizationOverviewContentProps = {
  modulesPeriodKey: '7d' | '30d';
  orgProfile: OrgOverviewProfileView | null;
  healthMetrics: HealthMetric[];
  overallHealth: number;
  lastCheck: string;
  healthLoading: boolean;
  healthError: Error | null;
  refetchHealth: () => void;
  activityPeriod: ActivityPeriod;
  setActivityPeriod: (p: ActivityPeriod) => void;
  customRange: { from?: Date; to?: Date };
  setCustomRange: (r: { from?: Date; to?: Date }) => void;
  activityParticipant: string;
  setActivityParticipant: (p: string) => void;
  setBlockedActivities: Dispatch<SetStateAction<RecentActivity[]>>;
  openBlockFor: number | null;
  setOpenBlockFor: (n: number | null) => void;
  openCommentFor: number | null;
  setOpenCommentFor: (n: number | null) => void;
  commentText: string;
  setCommentText: (s: string) => void;
  toast: OrganizationToastFn;
  alerts: AttentionAlertsState;
  getBlockLabel: (key: string) => string;
  dismissCertificate: (id: string) => void;
  dismissProfile: (id: string) => void;
  dismissTask: (id: string) => void;
  dismissIntegrationIssue: (id: string) => void;
  filteredActivities: RecentActivity[];
  globalHistory: HistoryEntry[];
  activityKey: (a: RecentActivity) => string;
  isBlocked: (a: RecentActivity) => boolean;
  getCorrectionHref: (act: RecentActivity) => string;
  participantsCount?: number;
  onlineCount?: number;
  partialLoadWarning?: string | null;
  moduleStatsByHref?: Record<string, ModuleStatPatch> | null;
  partnerEcosystem?: unknown;
};
