import test from 'node:test';
import assert from 'node:assert/strict';
import { approveFitSample, approveMeasurementChart, createFitSample, createMeasurementChart, createTechPack, evaluateFitSample, recordFitSampleMeasurement, rejectFitSample, submitMeasurementChart, upsertMeasurementPoint } from '../src/modules/measurements/public.mjs';

const style = Object.freeze({ id: 'style-1', brandId: 'brand-1', styleCode: 'JK-100', name: 'Tailored Jacket', category: 'Jackets', gender: 'women', status: 'approved', version: 4, sizeGrid: Object.freeze({ id: 'grid-1', code: 'EU-W', name: 'EU Women', status: 'published', version: 2, sizes: Object.freeze(['36', '38', '40']), baseSize: '38' }) });
const bom = Object.freeze({ id: 'bom-2', styleId: 'style-1', brandId: 'brand-1', revisionNumber: 2, status: 'approved', version: 5, currency: 'EUR', materialCostMinor: 4321, lines: Object.freeze([{ componentKey: 'shell', materialRevisionId: 'mr-1', lineCostMinor: 4321 }]) });
function approvedChart() { let chart = createMeasurementChart({ id: 'chart-1', style, revisionNumber: 1, createdAt: '2026-08-07T10:00:00.000Z' }); chart = upsertMeasurementPoint(chart, { code: 'CHEST', description: 'Chest circumference', baseTargetMm: 920, gradeStepMm: 40, toleranceMinusMm: 5, tolerancePlusMm: 7 }, '2026-08-07T10:01:00.000Z'); chart = upsertMeasurementPoint(chart, { code: 'LENGTH', description: 'Center back length', baseTargetMm: 620, gradeStepMm: 5, toleranceMinusMm: 4, tolerancePlusMm: 4, manualTargetsMm: { '40': 633 } }, '2026-08-07T10:02:00.000Z'); chart = submitMeasurementChart(chart, '2026-08-07T10:03:00.000Z'); return approveMeasurementChart(chart, '2026-08-07T10:04:00.000Z'); }

test('measurement chart grades all sizes deterministically and keeps manual overrides', () => { const chart = approvedChart(); const chest = chart.points.find((item) => item.code === 'CHEST'); const length = chart.points.find((item) => item.code === 'LENGTH'); assert.deepEqual(chest.targetsMm, { '36': 880, '38': 920, '40': 960 }); assert.deepEqual(length.targetsMm, { '36': 615, '38': 620, '40': 633 }); assert.equal(chart.status, 'approved'); assert.ok(Object.isFrozen(chart.points)); });
test('fit sample cannot be approved with failed tolerance and can be rejected', () => { const chart = approvedChart(); let sample = createFitSample({ id: 'fit-fail', chart, sampleType: 'fit', sampleNumber: 1, size: '38', createdAt: '2026-08-07T11:00:00.000Z' }); sample = recordFitSampleMeasurement(sample, 'CHEST', 930, '2026-08-07T11:01:00.000Z'); sample = recordFitSampleMeasurement(sample, 'LENGTH', 620, '2026-08-07T11:02:00.000Z'); sample = evaluateFitSample(sample, '2026-08-07T11:03:00.000Z'); assert.equal(sample.result.verdict, 'fail'); assert.throws(() => approveFitSample(sample, '2026-08-07T11:04:00.000Z'), (error) => error.code === 'FIT_SAMPLE_OUT_OF_TOLERANCE'); const rejected = rejectFitSample(sample, 'Chest exceeds tolerance', '2026-08-07T11:05:00.000Z'); assert.equal(rejected.status, 'rejected'); });
test('Tech Pack snapshots approved style, BOM, chart and fit measurements immutably', () => { const chart = approvedChart(); let sample = createFitSample({ id: 'fit-pass', chart, sampleType: 'pps', sampleNumber: 2, size: '38', createdAt: '2026-08-07T12:00:00.000Z' }); sample = recordFitSampleMeasurement(sample, 'CHEST', 925, '2026-08-07T12:01:00.000Z'); sample = recordFitSampleMeasurement(sample, 'LENGTH', 618, '2026-08-07T12:02:00.000Z'); sample = approveFitSample(evaluateFitSample(sample, '2026-08-07T12:03:00.000Z'), '2026-08-07T12:04:00.000Z'); const pack = createTechPack({ id: 'tp-1', revisionNumber: 1, style, bom, chart, fitSample: sample, generatedBy: 'product-1', generatedAt: '2026-08-07T12:05:00.000Z' }); assert.equal(pack.status, 'generated'); assert.equal(pack.manifest.billOfMaterials.materialCostMinor, 4321); assert.equal(pack.manifest.fitApproval.result.verdict, 'pass'); assert.equal(pack.manifest.measurementChart.points[0].targetsMm['38'], 920); assert.ok(Object.isFrozen(pack.manifest)); });
