import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createOrganisation } from '../src/modules/organisations/public.mjs';
import { createMembership } from '../src/modules/access-control/public.mjs';
import { migratePostgres } from '../src/infrastructure/postgres-migrator.mjs';
import { createPostgresWholesaleRuntime } from '../src/runtime/postgres-runtime.mjs';
const databaseUrl=process.env.POSTGRES_TEST_URL;
test('PostgreSQL materializes immutable Tech Pack HTML+ZIP artifacts with checksums, replay and RBAC',{skip:!databaseUrl},async()=>{const{Pool}=await import('pg');const pool=new Pool({connectionString:databaseUrl,max:4});const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');let id=0;let tick=0;const nextId=(prefix)=>`${prefix}_artifact_pg_${++id}`;const base=Date.parse('2026-08-07T16:00:00.000Z');const clock=()=>new Date(base+tick++*1000).toISOString();try{
await pool.query('DROP SCHEMA public CASCADE; CREATE SCHEMA public;');await migratePostgres({pool,migrationsDir:path.join(root,'db','migrations'),clock});const runtime=createPostgresWholesaleRuntime({pool,clock,nextId});await runtime.platform.registerOrganisation('artifact-brand','system',createOrganisation({id:'brand-artifact',type:'brand',name:'Artifact Brand'}));await runtime.platform.grantMembership('artifact-owner','system',createMembership({id:'m-owner-artifact',organisationId:'brand-artifact',organisationType:'brand',userId:'owner-artifact',role:'owner',createdAt:clock()}));for(const[userId,role]of[['product-artifact','product'],['sales-artifact','sales'],['finance-artifact','finance']])await runtime.platform.grantMembership(`artifact-${role}`,'owner-artifact',createMembership({id:`m-${role}-artifact`,organisationId:'brand-artifact',organisationType:'brand',userId,role,createdAt:clock()}));
const campaign=await runtime.platform.createCampaign('artifact-campaign','owner-artifact',{brandId:'brand-artifact',name:'SS32',season:'SS32',startsAt:'2031-01-01T00:00:00.000Z',endsAt:'2032-01-01T00:00:00.000Z'});await runtime.platform.openCampaign('artifact-campaign-open','owner-artifact',campaign.id);const collection=await runtime.platform.createCollection('artifact-collection','owner-artifact',{campaignId:campaign.id,brandId:'brand-artifact',name:'SS32 Main',currency:'EUR'});const gridDraft=await runtime.productDevelopment.createSizeGrid('artifact-grid','product-artifact',{brandId:'brand-artifact',code:'EU-W',name:'EU Women',sizes:['36','38','40'],baseSize:'38'});const grid=await runtime.productDevelopment.publishSizeGrid('artifact-grid-publish','product-artifact',gridDraft.id);const styleDraft=await runtime.productDevelopment.createStyle('artifact-style','product-artifact',{brandId:'brand-artifact',collectionId:collection.id,styleCode:'TP-ART-1',name:'\u0416\u0430\u043a\u0435\u0442 Artifact',category:'Jackets',gender:'women',sizeGridId:grid.id});const style=await runtime.productDevelopment.approveStyle('artifact-style-approve','product-artifact',styleDraft.id);const generatedAt=clock();
const pack=Object.freeze({id:'tech-pack-artifact-1',brandId:style.brandId,styleId:style.id,styleCode:style.styleCode,revisionNumber:1,status:'generated',sourceFingerprint:`style:${style.id}@${style.version}|bom:fixture@1|chart:fixture@1|sample:fixture@1`,sources:Object.freeze({styleId:style.id,styleVersion:style.version,bomId:'fixture-bom',bomRevisionNumber:1,bomVersion:1,measurementChartId:'fixture-chart',measurementChartRevisionNumber:1,measurementChartVersion:1,fitSampleId:'fixture-fit',fitSampleVersion:1}),manifest:Object.freeze({schemaVersion:1,style:Object.freeze({id:style.id,code:style.styleCode,name:style.name,category:style.category,gender:style.gender,version:style.version,sizeGrid:style.sizeGrid}),billOfMaterials:Object.freeze({id:'fixture-bom',revisionNumber:1,currency:'EUR',materialCostMinor:0,lines:Object.freeze([])}),measurementChart:Object.freeze({id:'fixture-chart',revisionNumber:1,points:Object.freeze([{code:'CHEST',description:'Chest',toleranceMinusMm:5,tolerancePlusMm:7,targetsMm:Object.freeze({'36':880,'38':920,'40':960}),manualTargetsMm:Object.freeze({})}])}),fitApproval:Object.freeze({id:'fixture-fit',sampleType:'pps',sampleNumber:1,size:'38',result:Object.freeze({verdict:'pass',passCount:1,failCount:0,measuredCount:1,totalCount:1}),measurements:Object.freeze([{pointCode:'CHEST',description:'Chest',targetMm:920,actualMm:921,deviationMm:1,withinTolerance:true}]),approvedAt:generatedAt})}),generatedBy:'product-artifact',generatedAt,version:1});await pool.query('INSERT INTO product_tech_packs (id, style_id, brand_id, revision_number, source_fingerprint, status, generated_at, version, payload) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb)',[pack.id,pack.styleId,pack.brandId,pack.revisionNumber,pack.sourceFingerprint,pack.status,pack.generatedAt,pack.version,JSON.stringify(pack)]);
const zip=await runtime.techPackArtifacts.exportTechPack('artifact-export-zip','product-artifact',pack.id,'zip');assert.equal(zip.content.subarray(0,4).toString('hex'),'504b0304');assert.equal(zip.sha256,createHash('sha256').update(zip.content).digest('hex'));const replay=await runtime.techPackArtifacts.exportTechPack('artifact-export-zip','product-artifact',pack.id,'zip');assert.equal(replay.sha256,zip.sha256);const html=await runtime.techPackArtifacts.exportTechPack('artifact-export-html','product-artifact',pack.id,'html');assert.match(html.content.toString('utf8'),/\u0416\u0430\u043a\u0435\u0442 Artifact/);assert.equal(html.sha256,createHash('sha256').update(html.content).digest('hex'));
const rows=await pool.query("SELECT format, size_bytes, length(sha256) AS hash_length FROM product_tech_pack_artifacts WHERE tech_pack_id = $1 ORDER BY format",[pack.id]);assert.deepEqual(rows.rows,[{format:'html',size_bytes:html.sizeBytes,hash_length:64},{format:'zip',size_bytes:zip.sizeBytes,hash_length:64}]);const events=await pool.query("SELECT count(*)::int AS count FROM outbox_events WHERE event_type = 'tech-pack.artifacts-materialized' AND aggregate_id = $1",[pack.id]);assert.equal(events.rows[0].count,1);for(const actorId of['sales-artifact','finance-artifact'])await assert.rejects(()=>runtime.techPackArtifacts.exportTechPack(`artifact-blocked-${actorId}`,actorId,pack.id,'zip'),error=>error.code==='CAPABILITY_DENIED');
await pool.query("UPDATE product_tech_pack_artifacts SET content = set_byte(content, 0, (get_byte(content, 0) + 1) % 256) WHERE tech_pack_id = $1 AND format = 'zip'",[pack.id]);await assert.rejects(()=>runtime.techPackArtifacts.exportTechPack('artifact-corruption-check','product-artifact',pack.id,'zip'),error=>error.code==='TECH_PACK_ARTIFACT_INTEGRITY_FAILED');
}finally{await pool.end();}});
