import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createOrganisation } from '../src/modules/organisations/public.mjs';
import { createMembership } from '../src/modules/access-control/public.mjs';
import { createPostgresWholesaleRuntime } from '../src/runtime/postgres-runtime.mjs';
import { migratePostgres } from '../src/infrastructure/postgres-migrator.mjs';
const databaseUrl = process.env.POSTGRES_TEST_URL;
test('PostgreSQL completes Measurement Chart -> failed fit -> revision -> approved fit -> immutable Tech Pack with RBAC', { skip: !databaseUrl }, async () => {
  const { Pool } = await import('pg'); const pool = new Pool({ connectionString: databaseUrl, max: 6 }); const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'); let id = 0; let tick = 0; const nextId = (prefix) => `${prefix}_measure_pg_${++id}`; const baseTime = Date.parse('2026-08-07T14:00:00.000Z'); const clock = () => new Date(baseTime + tick++ * 1000).toISOString();
  try {
    await pool.query('DROP SCHEMA public CASCADE; CREATE SCHEMA public;'); await migratePostgres({ pool, migrationsDir: path.join(root, 'db', 'migrations'), clock }); const runtime = createPostgresWholesaleRuntime({ pool, clock, nextId }); const { platform, productDevelopment, productSpecification, measurements, workspace } = runtime;
    await platform.registerOrganisation('measure-org-brand', 'system', createOrganisation({ id: 'brand-measure', type: 'brand', name: 'Measurement Brand' })); await platform.grantMembership('measure-owner', 'system', createMembership({ id: 'm-owner', organisationId: 'brand-measure', organisationType: 'brand', userId: 'owner-measure', role: 'owner', createdAt: clock() })); for (const [userId, role] of [['product-measure', 'product'], ['sales-measure', 'sales'], ['finance-measure', 'finance'], ['viewer-measure', 'viewer']]) await platform.grantMembership(`measure-${role}`, 'owner-measure', createMembership({ id: `m-${role}`, organisationId: 'brand-measure', organisationType: 'brand', userId, role, createdAt: clock() }));
    const campaign = await platform.createCampaign('measure-campaign', 'owner-measure', { brandId: 'brand-measure', name: 'AW31', season: 'AW31', startsAt: '2030-01-01T00:00:00.000Z', endsAt: '2031-01-01T00:00:00.000Z' }); await platform.openCampaign('measure-campaign-open', 'owner-measure', campaign.id); const collection = await platform.createCollection('measure-collection', 'owner-measure', { campaignId: campaign.id, brandId: 'brand-measure', name: 'AW31 Main', currency: 'EUR' });
    const gridDraft = await productDevelopment.createSizeGrid('measure-grid', 'product-measure', { brandId: 'brand-measure', code: 'EU-W', name: 'EU Women', sizes: ['36', '38', '40'], baseSize: '38' }); const grid = await productDevelopment.publishSizeGrid('measure-grid-publish', 'product-measure', gridDraft.id); const styleDraft = await productDevelopment.createStyle('measure-style', 'product-measure', { brandId: 'brand-measure', collectionId: collection.id, styleCode: 'JK-3100', name: 'Tailored Jacket', category: 'Jackets', gender: 'women', sizeGridId: grid.id }); const style = await productDevelopment.approveStyle('measure-style-approve', 'product-measure', styleDraft.id);
    const material = await productSpecification.createMaterial('measure-material', 'product-measure', { brandId: 'brand-measure', code: 'FAB-WOOL-1', name: 'Wool Twill', type: 'fabric', specification: { uom: 'm', composition: '100% wool', colorCode: 'BLACK', supplierName: 'Mill', unitCostMinor: 1800, currency: 'EUR', leadTimeDays: 40 } }); const materialRevision = await productSpecification.approveMaterialRevision('measure-material-approve', 'product-measure', material.revision.id); let bom = await productSpecification.createBom('measure-bom', 'product-measure', style.id); bom = await productSpecification.upsertBomLine('measure-bom-line', 'product-measure', bom.id, { componentKey: 'shell', componentRole: 'Main shell', materialRevisionId: materialRevision.id, consumptionMicrounits: 1_800_000, wasteBasisPoints: 500 }); bom = await productSpecification.submitBom('measure-bom-submit', 'product-measure', bom.id); await productSpecification.approveBom('measure-bom-approve', 'product-measure', bom.id);
    let chart1 = await measurements.createMeasurementChart('measure-chart-1', 'product-measure', style.id); chart1 = await measurements.upsertMeasurementPoint('measure-chart-1-chest', 'product-measure', chart1.id, { code: 'CHEST', description: 'Chest circumference', baseTargetMm: 920, gradeStepMm: 40, toleranceMinusMm: 5, tolerancePlusMm: 7 }); chart1 = await measurements.upsertMeasurementPoint('measure-chart-1-length', 'product-measure', chart1.id, { code: 'LENGTH', description: 'Center back length', baseTargetMm: 620, gradeStepMm: 5, toleranceMinusMm: 4, tolerancePlusMm: 4 }); chart1 = await measurements.submitMeasurementChart('measure-chart-1-submit', 'product-measure', chart1.id); chart1 = await measurements.approveMeasurementChart('measure-chart-1-approve', 'product-measure', chart1.id);
    let failed = await measurements.createFitSample('measure-fit-fail', 'product-measure', chart1.id, { sampleType: 'fit', sampleNumber: 1, size: '38', notes: 'First fit' }); failed = await measurements.recordFitMeasurement('measure-fit-fail-chest', 'product-measure', failed.id, 'CHEST', 931); failed = await measurements.recordFitMeasurement('measure-fit-fail-length', 'product-measure', failed.id, 'LENGTH', 620); failed = await measurements.evaluateFitSample('measure-fit-fail-evaluate', 'product-measure', failed.id); assert.equal(failed.result.verdict, 'fail'); await assert.rejects(() => measurements.approveFitSample('measure-fit-fail-bad-approve', 'product-measure', failed.id), (error) => error.code === 'FIT_SAMPLE_OUT_OF_TOLERANCE'); failed = await measurements.rejectFitSample('measure-fit-fail-reject', 'product-measure', failed.id, 'Chest too large'); assert.equal(failed.status, 'rejected');
    let chart2 = await measurements.reviseMeasurementChart('measure-chart-2', 'product-measure', chart1.id); chart2 = await measurements.upsertMeasurementPoint('measure-chart-2-chest', 'product-measure', chart2.id, { code: 'CHEST', description: 'Chest circumference', baseTargetMm: 926, gradeStepMm: 40, toleranceMinusMm: 5, tolerancePlusMm: 7 }); chart2 = await measurements.submitMeasurementChart('measure-chart-2-submit', 'product-measure', chart2.id); chart2 = await measurements.approveMeasurementChart('measure-chart-2-approve', 'product-measure', chart2.id);
    let passed = await measurements.createFitSample('measure-fit-pass', 'product-measure', chart2.id, { sampleType: 'pps', sampleNumber: 1, size: '38', notes: 'PPS' }); passed = await measurements.recordFitMeasurement('measure-fit-pass-chest', 'product-measure', passed.id, 'CHEST', 927); passed = await measurements.recordFitMeasurement('measure-fit-pass-length', 'product-measure', passed.id, 'LENGTH', 619); passed = await measurements.evaluateFitSample('measure-fit-pass-evaluate', 'product-measure', passed.id); passed = await measurements.approveFitSample('measure-fit-pass-approve', 'product-measure', passed.id); assert.equal(passed.status, 'approved');
    const pack = await measurements.generateTechPack('measure-techpack', 'product-measure', { styleId: style.id, fitSampleId: passed.id }); assert.equal(pack.revisionNumber, 1); assert.equal(pack.manifest.measurementChart.revisionNumber, 2); assert.equal(pack.manifest.fitApproval.result.verdict, 'pass'); const manifest = await measurements.getTechPackManifest('product-measure', pack.id); assert.equal(manifest.manifest.billOfMaterials.materialCostMinor, bom.materialCostMinor); await assert.rejects(() => measurements.generateTechPack('measure-techpack-duplicate', 'product-measure', { styleId: style.id, fitSampleId: passed.id }), (error) => error.code === 'TECH_PACK_ALREADY_GENERATED_FOR_SOURCES');
    const productWorkspace = await workspace.loadForActor('product-measure'); assert.equal(productWorkspace.measurementCharts.length, 2); assert.equal(productWorkspace.fitSamples.length, 2); assert.equal(productWorkspace.techPacks.length, 1); for (const actorId of ['sales-measure', 'finance-measure', 'viewer-measure']) { const blockedWorkspace = await workspace.loadForActor(actorId); assert.deepEqual(blockedWorkspace.measurementCharts, []); assert.deepEqual(blockedWorkspace.fitSamples, []); assert.deepEqual(blockedWorkspace.techPacks, []); await assert.rejects(() => measurements.createMeasurementChart(`blocked-${actorId}`, actorId, style.id), (error) => error.code === 'CAPABILITY_DENIED'); }
    const rows = await pool.query(`SELECT (SELECT count(*)::int FROM product_measurement_charts) AS charts, (SELECT count(*)::int FROM product_measurement_charts WHERE status = 'approved') AS approved_charts, (SELECT count(*)::int FROM product_measurement_charts WHERE status = 'superseded') AS superseded_charts, (SELECT count(*)::int FROM product_fit_samples WHERE status = 'rejected') AS rejected_samples, (SELECT count(*)::int FROM product_fit_samples WHERE status = 'approved') AS approved_samples, (SELECT count(*)::int FROM product_tech_packs) AS tech_packs, (SELECT count(*)::int FROM outbox_events WHERE event_type LIKE 'measurement-%' OR event_type LIKE 'fit-%' OR event_type = 'tech-pack.generated') AS event_count`); assert.deepEqual(rows.rows[0], { charts: 2, approved_charts: 1, superseded_charts: 1, rejected_samples: 1, approved_samples: 1, tech_packs: 1, event_count: 20 });
  } finally { await pool.end(); }
});
